/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface IntegrationsServiceTrackRequest {
    slug: string;
}

/**
 * IntegrationsServiceApi - interface
 * 
 * @export
 * @interface IntegrationsServiceApiInterface
 */
export interface IntegrationsServiceApiInterface {
    /**
     * Creates request options for integrationsServiceTrack without sending the request
     * @param {string} slug The slug identifying the integration being installed
     * @throws {RequiredError}
     * @memberof IntegrationsServiceApiInterface
     */
    integrationsServiceTrackRequestOpts(requestParameters: IntegrationsServiceTrackRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Track notifies when an integration installation is attempted
     * @param {string} slug The slug identifying the integration being installed
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IntegrationsServiceApiInterface
     */
    integrationsServiceTrackRaw(requestParameters: IntegrationsServiceTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Track notifies when an integration installation is attempted
     */
    integrationsServiceTrack(requestParameters: IntegrationsServiceTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

}

/**
 * 
 */
export class IntegrationsServiceApi extends runtime.BaseAPI implements IntegrationsServiceApiInterface {

    /**
     * Creates request options for integrationsServiceTrack without sending the request
     */
    async integrationsServiceTrackRequestOpts(requestParameters: IntegrationsServiceTrackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['slug'] == null) {
            throw new runtime.RequiredError(
                'slug',
                'Required parameter "slug" was null or undefined when calling integrationsServiceTrack().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/integrations/{slug}`;
        urlPath = urlPath.replace(`{${"slug"}}`, encodeURIComponent(String(requestParameters['slug'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Track notifies when an integration installation is attempted
     */
    async integrationsServiceTrackRaw(requestParameters: IntegrationsServiceTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.integrationsServiceTrackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Track notifies when an integration installation is attempted
     */
    async integrationsServiceTrack(requestParameters: IntegrationsServiceTrackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.integrationsServiceTrackRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
