/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddWorkflowStepRelationshipResponse,
  CreateWorkflowStepResponse,
  ErrorResponse,
  GetWorkflowStepResponse,
  ListWorkflowStepsResponse,
  RemoveWorkflowStepRelationshipResponse,
  UpdateWorkflowStepResponse,
  WorkflowStepsServiceAddRelationshipBody,
  WorkflowStepsServiceCreateBody,
  WorkflowStepsServiceUpdateBody,
} from '../models/index';
import {
    AddWorkflowStepRelationshipResponseFromJSON,
    AddWorkflowStepRelationshipResponseToJSON,
    CreateWorkflowStepResponseFromJSON,
    CreateWorkflowStepResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetWorkflowStepResponseFromJSON,
    GetWorkflowStepResponseToJSON,
    ListWorkflowStepsResponseFromJSON,
    ListWorkflowStepsResponseToJSON,
    RemoveWorkflowStepRelationshipResponseFromJSON,
    RemoveWorkflowStepRelationshipResponseToJSON,
    UpdateWorkflowStepResponseFromJSON,
    UpdateWorkflowStepResponseToJSON,
    WorkflowStepsServiceAddRelationshipBodyFromJSON,
    WorkflowStepsServiceAddRelationshipBodyToJSON,
    WorkflowStepsServiceCreateBodyFromJSON,
    WorkflowStepsServiceCreateBodyToJSON,
    WorkflowStepsServiceUpdateBodyFromJSON,
    WorkflowStepsServiceUpdateBodyToJSON,
} from '../models/index';

export interface WorkflowStepsServiceAddRelationshipRequest {
    linkId: string;
    parentStepId: string;
    workflowStepsServiceAddRelationshipBody: WorkflowStepsServiceAddRelationshipBody;
}

export interface WorkflowStepsServiceCreateRequest {
    linkId: string;
    workflowStepsServiceCreateBody: WorkflowStepsServiceCreateBody;
}

export interface WorkflowStepsServiceDeleteRequest {
    linkId: string;
    id: string;
}

export interface WorkflowStepsServiceGetRequest {
    linkId: string;
    id: string;
}

export interface WorkflowStepsServiceListRequest {
    linkId: string;
    pageSize?: number;
    pageToken?: string;
}

export interface WorkflowStepsServiceRemoveRelationshipRequest {
    linkId: string;
    parentStepId: string;
    childStepId: string;
}

export interface WorkflowStepsServiceUpdateRequest {
    linkId: string;
    id: string;
    workflowStepsServiceUpdateBody: WorkflowStepsServiceUpdateBody;
}

/**
 * WorkflowStepsApi - interface
 * 
 * @export
 * @interface WorkflowStepsApiInterface
 */
export interface WorkflowStepsApiInterface {
    /**
     * Creates request options for workflowStepsServiceAddRelationship without sending the request
     * @param {string} linkId The ID of the link (UUID)
     * @param {string} parentStepId The ID of the parent workflow step (UUID)
     * @param {WorkflowStepsServiceAddRelationshipBody} workflowStepsServiceAddRelationshipBody 
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceAddRelationshipRequestOpts(requestParameters: WorkflowStepsServiceAddRelationshipRequest): Promise<runtime.RequestOpts>;

    /**
     * Creates a parent-child relationship between two workflow steps.  IMPORTANT: This endpoint cannot be used to create connections FROM composite nodes (forms, multi-links, conditions). Composite nodes manage their own routing through their payload structure (e.g., button.next_step_id, option.next_step_id).  Connections TO composite nodes are allowed. Only atomic nodes (redirects, passwords, etc.) can use this endpoint as the parent.
     * @summary Add relationship between workflow steps
     * @param {string} linkId The ID of the link (UUID)
     * @param {string} parentStepId The ID of the parent workflow step (UUID)
     * @param {WorkflowStepsServiceAddRelationshipBody} workflowStepsServiceAddRelationshipBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceAddRelationshipRaw(requestParameters: WorkflowStepsServiceAddRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddWorkflowStepRelationshipResponse>>;

    /**
     * Creates a parent-child relationship between two workflow steps.  IMPORTANT: This endpoint cannot be used to create connections FROM composite nodes (forms, multi-links, conditions). Composite nodes manage their own routing through their payload structure (e.g., button.next_step_id, option.next_step_id).  Connections TO composite nodes are allowed. Only atomic nodes (redirects, passwords, etc.) can use this endpoint as the parent.
     * Add relationship between workflow steps
     */
    workflowStepsServiceAddRelationship(requestParameters: WorkflowStepsServiceAddRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddWorkflowStepRelationshipResponse>;

    /**
     * Creates request options for workflowStepsServiceCreate without sending the request
     * @param {string} linkId The ID of the link to create the workflow step for (UUID)
     * @param {WorkflowStepsServiceCreateBody} workflowStepsServiceCreateBody 
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceCreateRequestOpts(requestParameters: WorkflowStepsServiceCreateRequest): Promise<runtime.RequestOpts>;

    /**
     * This endpoint allows users to create a new workflow step for a link. Workflow steps define the behavior of links, such as redirection destinations.
     * @summary Create a new workflow step
     * @param {string} linkId The ID of the link to create the workflow step for (UUID)
     * @param {WorkflowStepsServiceCreateBody} workflowStepsServiceCreateBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceCreateRaw(requestParameters: WorkflowStepsServiceCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateWorkflowStepResponse>>;

    /**
     * This endpoint allows users to create a new workflow step for a link. Workflow steps define the behavior of links, such as redirection destinations.
     * Create a new workflow step
     */
    workflowStepsServiceCreate(requestParameters: WorkflowStepsServiceCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateWorkflowStepResponse>;

    /**
     * Creates request options for workflowStepsServiceDelete without sending the request
     * @param {string} linkId The ID of the link (UUID)
     * @param {string} id The ID of the workflow step to delete (UUID)
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceDeleteRequestOpts(requestParameters: WorkflowStepsServiceDeleteRequest): Promise<runtime.RequestOpts>;

    /**
     * Removes a workflow step from the link. This operation cannot be undone.
     * @summary Delete a workflow step
     * @param {string} linkId The ID of the link (UUID)
     * @param {string} id The ID of the workflow step to delete (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceDeleteRaw(requestParameters: WorkflowStepsServiceDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Removes a workflow step from the link. This operation cannot be undone.
     * Delete a workflow step
     */
    workflowStepsServiceDelete(requestParameters: WorkflowStepsServiceDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Creates request options for workflowStepsServiceGet without sending the request
     * @param {string} linkId The ID of the link (UUID)
     * @param {string} id The ID of the workflow step to retrieve (UUID)
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceGetRequestOpts(requestParameters: WorkflowStepsServiceGetRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves information about a specific workflow step.
     * @summary Get workflow step details
     * @param {string} linkId The ID of the link (UUID)
     * @param {string} id The ID of the workflow step to retrieve (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceGetRaw(requestParameters: WorkflowStepsServiceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWorkflowStepResponse>>;

    /**
     * Retrieves information about a specific workflow step.
     * Get workflow step details
     */
    workflowStepsServiceGet(requestParameters: WorkflowStepsServiceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWorkflowStepResponse>;

    /**
     * Creates request options for workflowStepsServiceList without sending the request
     * @param {string} linkId The ID of the link to list workflow steps for (UUID)
     * @param {number} [pageSize] The maximum number of workflow steps to return (optional)
     * @param {string} [pageToken] The token for retrieving the next page of results (optional)
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceListRequestOpts(requestParameters: WorkflowStepsServiceListRequest): Promise<runtime.RequestOpts>;

    /**
     * Retrieves all workflow steps for a specific link
     * @summary List workflow steps for a link
     * @param {string} linkId The ID of the link to list workflow steps for (UUID)
     * @param {number} [pageSize] The maximum number of workflow steps to return (optional)
     * @param {string} [pageToken] The token for retrieving the next page of results (optional)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceListRaw(requestParameters: WorkflowStepsServiceListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkflowStepsResponse>>;

    /**
     * Retrieves all workflow steps for a specific link
     * List workflow steps for a link
     */
    workflowStepsServiceList(requestParameters: WorkflowStepsServiceListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkflowStepsResponse>;

    /**
     * Creates request options for workflowStepsServiceRemoveRelationship without sending the request
     * @param {string} linkId The ID of the link (UUID)
     * @param {string} parentStepId The ID of the parent workflow step (UUID)
     * @param {string} childStepId The ID of the child workflow step (UUID)
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceRemoveRelationshipRequestOpts(requestParameters: WorkflowStepsServiceRemoveRelationshipRequest): Promise<runtime.RequestOpts>;

    /**
     * Removes a parent-child relationship between two workflow steps.
     * @summary Remove relationship between workflow steps
     * @param {string} linkId The ID of the link (UUID)
     * @param {string} parentStepId The ID of the parent workflow step (UUID)
     * @param {string} childStepId The ID of the child workflow step (UUID)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceRemoveRelationshipRaw(requestParameters: WorkflowStepsServiceRemoveRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoveWorkflowStepRelationshipResponse>>;

    /**
     * Removes a parent-child relationship between two workflow steps.
     * Remove relationship between workflow steps
     */
    workflowStepsServiceRemoveRelationship(requestParameters: WorkflowStepsServiceRemoveRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoveWorkflowStepRelationshipResponse>;

    /**
     * Creates request options for workflowStepsServiceUpdate without sending the request
     * @param {string} linkId The ID of the link (UUID)
     * @param {string} id The ID of the workflow step to update (UUID)
     * @param {WorkflowStepsServiceUpdateBody} workflowStepsServiceUpdateBody 
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceUpdateRequestOpts(requestParameters: WorkflowStepsServiceUpdateRequest): Promise<runtime.RequestOpts>;

    /**
     * Updates an existing workflow step for a link.
     * @summary Update a workflow step
     * @param {string} linkId The ID of the link (UUID)
     * @param {string} id The ID of the workflow step to update (UUID)
     * @param {WorkflowStepsServiceUpdateBody} workflowStepsServiceUpdateBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkflowStepsApiInterface
     */
    workflowStepsServiceUpdateRaw(requestParameters: WorkflowStepsServiceUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateWorkflowStepResponse>>;

    /**
     * Updates an existing workflow step for a link.
     * Update a workflow step
     */
    workflowStepsServiceUpdate(requestParameters: WorkflowStepsServiceUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateWorkflowStepResponse>;

}

/**
 * 
 */
export class WorkflowStepsApi extends runtime.BaseAPI implements WorkflowStepsApiInterface {

    /**
     * Creates request options for workflowStepsServiceAddRelationship without sending the request
     */
    async workflowStepsServiceAddRelationshipRequestOpts(requestParameters: WorkflowStepsServiceAddRelationshipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['linkId'] == null) {
            throw new runtime.RequiredError(
                'linkId',
                'Required parameter "linkId" was null or undefined when calling workflowStepsServiceAddRelationship().'
            );
        }

        if (requestParameters['parentStepId'] == null) {
            throw new runtime.RequiredError(
                'parentStepId',
                'Required parameter "parentStepId" was null or undefined when calling workflowStepsServiceAddRelationship().'
            );
        }

        if (requestParameters['workflowStepsServiceAddRelationshipBody'] == null) {
            throw new runtime.RequiredError(
                'workflowStepsServiceAddRelationshipBody',
                'Required parameter "workflowStepsServiceAddRelationshipBody" was null or undefined when calling workflowStepsServiceAddRelationship().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/links/{linkId}/workflow-steps/{parentStepId}/relationships`;
        urlPath = urlPath.replace(`{${"linkId"}}`, encodeURIComponent(String(requestParameters['linkId'])));
        urlPath = urlPath.replace(`{${"parentStepId"}}`, encodeURIComponent(String(requestParameters['parentStepId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkflowStepsServiceAddRelationshipBodyToJSON(requestParameters['workflowStepsServiceAddRelationshipBody']),
        };
    }

    /**
     * Creates a parent-child relationship between two workflow steps.  IMPORTANT: This endpoint cannot be used to create connections FROM composite nodes (forms, multi-links, conditions). Composite nodes manage their own routing through their payload structure (e.g., button.next_step_id, option.next_step_id).  Connections TO composite nodes are allowed. Only atomic nodes (redirects, passwords, etc.) can use this endpoint as the parent.
     * Add relationship between workflow steps
     */
    async workflowStepsServiceAddRelationshipRaw(requestParameters: WorkflowStepsServiceAddRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddWorkflowStepRelationshipResponse>> {
        const requestOptions = await this.workflowStepsServiceAddRelationshipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddWorkflowStepRelationshipResponseFromJSON(jsonValue));
    }

    /**
     * Creates a parent-child relationship between two workflow steps.  IMPORTANT: This endpoint cannot be used to create connections FROM composite nodes (forms, multi-links, conditions). Composite nodes manage their own routing through their payload structure (e.g., button.next_step_id, option.next_step_id).  Connections TO composite nodes are allowed. Only atomic nodes (redirects, passwords, etc.) can use this endpoint as the parent.
     * Add relationship between workflow steps
     */
    async workflowStepsServiceAddRelationship(requestParameters: WorkflowStepsServiceAddRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddWorkflowStepRelationshipResponse> {
        const response = await this.workflowStepsServiceAddRelationshipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workflowStepsServiceCreate without sending the request
     */
    async workflowStepsServiceCreateRequestOpts(requestParameters: WorkflowStepsServiceCreateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['linkId'] == null) {
            throw new runtime.RequiredError(
                'linkId',
                'Required parameter "linkId" was null or undefined when calling workflowStepsServiceCreate().'
            );
        }

        if (requestParameters['workflowStepsServiceCreateBody'] == null) {
            throw new runtime.RequiredError(
                'workflowStepsServiceCreateBody',
                'Required parameter "workflowStepsServiceCreateBody" was null or undefined when calling workflowStepsServiceCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/links/{linkId}/workflow-steps`;
        urlPath = urlPath.replace(`{${"linkId"}}`, encodeURIComponent(String(requestParameters['linkId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkflowStepsServiceCreateBodyToJSON(requestParameters['workflowStepsServiceCreateBody']),
        };
    }

    /**
     * This endpoint allows users to create a new workflow step for a link. Workflow steps define the behavior of links, such as redirection destinations.
     * Create a new workflow step
     */
    async workflowStepsServiceCreateRaw(requestParameters: WorkflowStepsServiceCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateWorkflowStepResponse>> {
        const requestOptions = await this.workflowStepsServiceCreateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateWorkflowStepResponseFromJSON(jsonValue));
    }

    /**
     * This endpoint allows users to create a new workflow step for a link. Workflow steps define the behavior of links, such as redirection destinations.
     * Create a new workflow step
     */
    async workflowStepsServiceCreate(requestParameters: WorkflowStepsServiceCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateWorkflowStepResponse> {
        const response = await this.workflowStepsServiceCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workflowStepsServiceDelete without sending the request
     */
    async workflowStepsServiceDeleteRequestOpts(requestParameters: WorkflowStepsServiceDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['linkId'] == null) {
            throw new runtime.RequiredError(
                'linkId',
                'Required parameter "linkId" was null or undefined when calling workflowStepsServiceDelete().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workflowStepsServiceDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/links/{linkId}/workflow-steps/{id}`;
        urlPath = urlPath.replace(`{${"linkId"}}`, encodeURIComponent(String(requestParameters['linkId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes a workflow step from the link. This operation cannot be undone.
     * Delete a workflow step
     */
    async workflowStepsServiceDeleteRaw(requestParameters: WorkflowStepsServiceDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.workflowStepsServiceDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Removes a workflow step from the link. This operation cannot be undone.
     * Delete a workflow step
     */
    async workflowStepsServiceDelete(requestParameters: WorkflowStepsServiceDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.workflowStepsServiceDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workflowStepsServiceGet without sending the request
     */
    async workflowStepsServiceGetRequestOpts(requestParameters: WorkflowStepsServiceGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['linkId'] == null) {
            throw new runtime.RequiredError(
                'linkId',
                'Required parameter "linkId" was null or undefined when calling workflowStepsServiceGet().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workflowStepsServiceGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/links/{linkId}/workflow-steps/{id}`;
        urlPath = urlPath.replace(`{${"linkId"}}`, encodeURIComponent(String(requestParameters['linkId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves information about a specific workflow step.
     * Get workflow step details
     */
    async workflowStepsServiceGetRaw(requestParameters: WorkflowStepsServiceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWorkflowStepResponse>> {
        const requestOptions = await this.workflowStepsServiceGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetWorkflowStepResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves information about a specific workflow step.
     * Get workflow step details
     */
    async workflowStepsServiceGet(requestParameters: WorkflowStepsServiceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWorkflowStepResponse> {
        const response = await this.workflowStepsServiceGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workflowStepsServiceList without sending the request
     */
    async workflowStepsServiceListRequestOpts(requestParameters: WorkflowStepsServiceListRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['linkId'] == null) {
            throw new runtime.RequiredError(
                'linkId',
                'Required parameter "linkId" was null or undefined when calling workflowStepsServiceList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['pageToken'] != null) {
            queryParameters['pageToken'] = requestParameters['pageToken'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/links/{linkId}/workflow-steps`;
        urlPath = urlPath.replace(`{${"linkId"}}`, encodeURIComponent(String(requestParameters['linkId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves all workflow steps for a specific link
     * List workflow steps for a link
     */
    async workflowStepsServiceListRaw(requestParameters: WorkflowStepsServiceListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWorkflowStepsResponse>> {
        const requestOptions = await this.workflowStepsServiceListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWorkflowStepsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves all workflow steps for a specific link
     * List workflow steps for a link
     */
    async workflowStepsServiceList(requestParameters: WorkflowStepsServiceListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWorkflowStepsResponse> {
        const response = await this.workflowStepsServiceListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workflowStepsServiceRemoveRelationship without sending the request
     */
    async workflowStepsServiceRemoveRelationshipRequestOpts(requestParameters: WorkflowStepsServiceRemoveRelationshipRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['linkId'] == null) {
            throw new runtime.RequiredError(
                'linkId',
                'Required parameter "linkId" was null or undefined when calling workflowStepsServiceRemoveRelationship().'
            );
        }

        if (requestParameters['parentStepId'] == null) {
            throw new runtime.RequiredError(
                'parentStepId',
                'Required parameter "parentStepId" was null or undefined when calling workflowStepsServiceRemoveRelationship().'
            );
        }

        if (requestParameters['childStepId'] == null) {
            throw new runtime.RequiredError(
                'childStepId',
                'Required parameter "childStepId" was null or undefined when calling workflowStepsServiceRemoveRelationship().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/links/{linkId}/workflow-steps/{parentStepId}/relationships/{childStepId}`;
        urlPath = urlPath.replace(`{${"linkId"}}`, encodeURIComponent(String(requestParameters['linkId'])));
        urlPath = urlPath.replace(`{${"parentStepId"}}`, encodeURIComponent(String(requestParameters['parentStepId'])));
        urlPath = urlPath.replace(`{${"childStepId"}}`, encodeURIComponent(String(requestParameters['childStepId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Removes a parent-child relationship between two workflow steps.
     * Remove relationship between workflow steps
     */
    async workflowStepsServiceRemoveRelationshipRaw(requestParameters: WorkflowStepsServiceRemoveRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RemoveWorkflowStepRelationshipResponse>> {
        const requestOptions = await this.workflowStepsServiceRemoveRelationshipRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RemoveWorkflowStepRelationshipResponseFromJSON(jsonValue));
    }

    /**
     * Removes a parent-child relationship between two workflow steps.
     * Remove relationship between workflow steps
     */
    async workflowStepsServiceRemoveRelationship(requestParameters: WorkflowStepsServiceRemoveRelationshipRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RemoveWorkflowStepRelationshipResponse> {
        const response = await this.workflowStepsServiceRemoveRelationshipRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for workflowStepsServiceUpdate without sending the request
     */
    async workflowStepsServiceUpdateRequestOpts(requestParameters: WorkflowStepsServiceUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['linkId'] == null) {
            throw new runtime.RequiredError(
                'linkId',
                'Required parameter "linkId" was null or undefined when calling workflowStepsServiceUpdate().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling workflowStepsServiceUpdate().'
            );
        }

        if (requestParameters['workflowStepsServiceUpdateBody'] == null) {
            throw new runtime.RequiredError(
                'workflowStepsServiceUpdateBody',
                'Required parameter "workflowStepsServiceUpdateBody" was null or undefined when calling workflowStepsServiceUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/links/{linkId}/workflow-steps/{id}`;
        urlPath = urlPath.replace(`{${"linkId"}}`, encodeURIComponent(String(requestParameters['linkId'])));
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: WorkflowStepsServiceUpdateBodyToJSON(requestParameters['workflowStepsServiceUpdateBody']),
        };
    }

    /**
     * Updates an existing workflow step for a link.
     * Update a workflow step
     */
    async workflowStepsServiceUpdateRaw(requestParameters: WorkflowStepsServiceUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateWorkflowStepResponse>> {
        const requestOptions = await this.workflowStepsServiceUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateWorkflowStepResponseFromJSON(jsonValue));
    }

    /**
     * Updates an existing workflow step for a link.
     * Update a workflow step
     */
    async workflowStepsServiceUpdate(requestParameters: WorkflowStepsServiceUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateWorkflowStepResponse> {
        const response = await this.workflowStepsServiceUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
