/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.110.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - AGENT_CONTEXT_TYPE_LINK_ANALYTICS: Building a link's analytics dashboard. context_id is the LINK id, not a
 * dashboard id — the dashboard does not exist yet while the user and the
 * assistant are still agreeing on what it should show. Once it exists,
 * editing it happens under AGENT_CONTEXT_TYPE_ANALYTICS_DASHBOARD instead.
 * @export
 */
export const AgentContextType = {
    AgentContextTypeUnspecified: 'AGENT_CONTEXT_TYPE_UNSPECIFIED',
    AgentContextTypeAnalyticsDashboard: 'AGENT_CONTEXT_TYPE_ANALYTICS_DASHBOARD',
    AgentContextTypeWorkflow: 'AGENT_CONTEXT_TYPE_WORKFLOW',
    AgentContextTypeLink: 'AGENT_CONTEXT_TYPE_LINK',
    AgentContextTypeQrcodeDesign: 'AGENT_CONTEXT_TYPE_QRCODE_DESIGN',
    AgentContextTypePageTheme: 'AGENT_CONTEXT_TYPE_PAGE_THEME',
    AgentContextTypeLinkAnalytics: 'AGENT_CONTEXT_TYPE_LINK_ANALYTICS'
} as const;
export type AgentContextType = typeof AgentContextType[keyof typeof AgentContextType];


export function instanceOfAgentContextType(value: any): boolean {
    for (const key in AgentContextType) {
        if (Object.prototype.hasOwnProperty.call(AgentContextType, key)) {
            if (AgentContextType[key as keyof typeof AgentContextType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AgentContextTypeFromJSON(json: any): AgentContextType {
    return AgentContextTypeFromJSONTyped(json, false);
}

export function AgentContextTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentContextType {
    return json as AgentContextType;
}

export function AgentContextTypeToJSON(value?: AgentContextType | null): any {
    return value as any;
}

export function AgentContextTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AgentContextType {
    return value as AgentContextType;
}

