/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.111.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatUIAction } from './ChatUIAction';
import {
    ChatUIActionFromJSON,
    ChatUIActionFromJSONTyped,
    ChatUIActionToJSON,
    ChatUIActionToJSONTyped,
} from './ChatUIAction';

/**
 * 
 * @export
 * @interface AgentSendMessageResponse
 */
export interface AgentSendMessageResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof AgentSendMessageResponse
     */
    appliedActions?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AgentSendMessageResponse
     */
    contextUpdated?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AgentSendMessageResponse
     */
    responseText?: string;
    /**
     * 
     * @type {Array<ChatUIAction>}
     * @memberof AgentSendMessageResponse
     */
    uiActions?: Array<ChatUIAction>;
}

/**
 * Check if a given object implements the AgentSendMessageResponse interface.
 */
export function instanceOfAgentSendMessageResponse(value: object): value is AgentSendMessageResponse {
    return true;
}

export function AgentSendMessageResponseFromJSON(json: any): AgentSendMessageResponse {
    return AgentSendMessageResponseFromJSONTyped(json, false);
}

export function AgentSendMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentSendMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appliedActions': json['appliedActions'] == null ? undefined : json['appliedActions'],
        'contextUpdated': json['contextUpdated'] == null ? undefined : json['contextUpdated'],
        'responseText': json['responseText'] == null ? undefined : json['responseText'],
        'uiActions': json['uiActions'] == null ? undefined : ((json['uiActions'] as Array<any>).map(ChatUIActionFromJSON)),
    };
}

export function AgentSendMessageResponseToJSON(json: any): AgentSendMessageResponse {
    return AgentSendMessageResponseToJSONTyped(json, false);
}

export function AgentSendMessageResponseToJSONTyped(value?: AgentSendMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appliedActions': value['appliedActions'],
        'contextUpdated': value['contextUpdated'],
        'responseText': value['responseText'],
        'uiActions': value['uiActions'] == null ? undefined : ((value['uiActions'] as Array<any>).map(ChatUIActionToJSON)),
    };
}

