/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.110.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsDashboardServiceGenerateWidgetSummaryBody
 */
export interface AnalyticsDashboardServiceGenerateWidgetSummaryBody {
    /**
     * 
     * @type {boolean}
     * @memberof AnalyticsDashboardServiceGenerateWidgetSummaryBody
     */
    force?: boolean;
}

/**
 * Check if a given object implements the AnalyticsDashboardServiceGenerateWidgetSummaryBody interface.
 */
export function instanceOfAnalyticsDashboardServiceGenerateWidgetSummaryBody(value: object): value is AnalyticsDashboardServiceGenerateWidgetSummaryBody {
    return true;
}

export function AnalyticsDashboardServiceGenerateWidgetSummaryBodyFromJSON(json: any): AnalyticsDashboardServiceGenerateWidgetSummaryBody {
    return AnalyticsDashboardServiceGenerateWidgetSummaryBodyFromJSONTyped(json, false);
}

export function AnalyticsDashboardServiceGenerateWidgetSummaryBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsDashboardServiceGenerateWidgetSummaryBody {
    if (json == null) {
        return json;
    }
    return {
        
        'force': json['force'] == null ? undefined : json['force'],
    };
}

export function AnalyticsDashboardServiceGenerateWidgetSummaryBodyToJSON(json: any): AnalyticsDashboardServiceGenerateWidgetSummaryBody {
    return AnalyticsDashboardServiceGenerateWidgetSummaryBodyToJSONTyped(json, false);
}

export function AnalyticsDashboardServiceGenerateWidgetSummaryBodyToJSONTyped(value?: AnalyticsDashboardServiceGenerateWidgetSummaryBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'force': value['force'],
    };
}

