/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.39.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Provides lightweight segmentation metadata Linkbreakers attaches to links and analytics so teams can group campaigns
 * and filter dashboards.
 * @export
 * @interface ApiTag
 */
export interface ApiTag {
    /**
     * 
     * @type {Date}
     * @memberof ApiTag
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ApiTag
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTag
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApiTag
     */
    readonly updatedAt?: Date;
}

/**
 * Check if a given object implements the ApiTag interface.
 */
export function instanceOfApiTag(value: object): value is ApiTag {
    return true;
}

export function ApiTagFromJSON(json: any): ApiTag {
    return ApiTagFromJSONTyped(json, false);
}

export function ApiTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTag {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ApiTagToJSON(json: any): ApiTag {
    return ApiTagToJSONTyped(json, false);
}

export function ApiTagToJSONTyped(value?: Omit<ApiTag, 'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

