/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.135.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplyPageThemeTemplateRequest
 */
export interface ApplyPageThemeTemplateRequest {
    /**
     * 
     * @type {string}
     * @memberof ApplyPageThemeTemplateRequest
     */
    linkId: string;
    /**
     * Template to apply, addressed by ID. Use this for workspace templates that have not been published and therefore have no slug.
     * @type {string}
     * @memberof ApplyPageThemeTemplateRequest
     */
    pageThemeTemplateId?: string;
    /**
     * Slug of the page theme template to apply.
     * 
     * Only published and built-in templates carry a slug: it is the public
     * identifier the gallery and the marketing site address them by. Supply
     * page_theme_template_id instead for a workspace's own drafts, which have
     * none. Exactly one of the two is required.
     * @type {string}
     * @memberof ApplyPageThemeTemplateRequest
     */
    slug?: string;
}

/**
 * Check if a given object implements the ApplyPageThemeTemplateRequest interface.
 */
export function instanceOfApplyPageThemeTemplateRequest(value: object): value is ApplyPageThemeTemplateRequest {
    if (!('linkId' in value) || value['linkId'] === undefined) return false;
    return true;
}

export function ApplyPageThemeTemplateRequestFromJSON(json: any): ApplyPageThemeTemplateRequest {
    return ApplyPageThemeTemplateRequestFromJSONTyped(json, false);
}

export function ApplyPageThemeTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyPageThemeTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'linkId': json['linkId'],
        'pageThemeTemplateId': json['pageThemeTemplateId'] == null ? undefined : json['pageThemeTemplateId'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function ApplyPageThemeTemplateRequestToJSON(json: any): ApplyPageThemeTemplateRequest {
    return ApplyPageThemeTemplateRequestToJSONTyped(json, false);
}

export function ApplyPageThemeTemplateRequestToJSONTyped(value?: ApplyPageThemeTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'linkId': value['linkId'],
        'pageThemeTemplateId': value['pageThemeTemplateId'],
        'slug': value['slug'],
    };
}

