/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.137.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssistantUploadFileRequest
 */
export interface AssistantUploadFileRequest {
    /**
     * 
     * @type {string}
     * @memberof AssistantUploadFileRequest
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantUploadFileRequest
     */
    mimeType?: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantUploadFileRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the AssistantUploadFileRequest interface.
 */
export function instanceOfAssistantUploadFileRequest(value: object): value is AssistantUploadFileRequest {
    return true;
}

export function AssistantUploadFileRequestFromJSON(json: any): AssistantUploadFileRequest {
    return AssistantUploadFileRequestFromJSONTyped(json, false);
}

export function AssistantUploadFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssistantUploadFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AssistantUploadFileRequestToJSON(json: any): AssistantUploadFileRequest {
    return AssistantUploadFileRequestToJSONTyped(json, false);
}

export function AssistantUploadFileRequestToJSONTyped(value?: AssistantUploadFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'mimeType': value['mimeType'],
        'name': value['name'],
    };
}

