/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.137.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AttributeWrite } from './AttributeWrite';
import {
    AttributeWriteFromJSON,
    AttributeWriteFromJSONTyped,
    AttributeWriteToJSON,
    AttributeWriteToJSONTyped,
} from './AttributeWrite';

/**
 * A step's opt-in to save values to the visitor's profile, so a workflow can
 * record qualification without a form: a tapped choice, a milestone reached,
 * or the context of the link that was scanned.
 * 
 * Available on every step except conditions, which only route on what is
 * already known. A failed password attempt or a skipped form saves nothing.
 * On forms it saves on top of the answers, which forms already save.
 * @export
 * @interface AttributeCapture
 */
export interface AttributeCapture {
    /**
     * Off keeps the configured writes without running them.
     * @type {boolean}
     * @memberof AttributeCapture
     */
    enabled?: boolean;
    /**
     * Up to 20 values to save. Each runs when the visitor goes through the step.
     * @type {Array<AttributeWrite>}
     * @memberof AttributeCapture
     */
    writes?: Array<AttributeWrite>;
}

/**
 * Check if a given object implements the AttributeCapture interface.
 */
export function instanceOfAttributeCapture(value: object): value is AttributeCapture {
    return true;
}

export function AttributeCaptureFromJSON(json: any): AttributeCapture {
    return AttributeCaptureFromJSONTyped(json, false);
}

export function AttributeCaptureFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeCapture {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'writes': json['writes'] == null ? undefined : ((json['writes'] as Array<any>).map(AttributeWriteFromJSON)),
    };
}

export function AttributeCaptureToJSON(json: any): AttributeCapture {
    return AttributeCaptureToJSONTyped(json, false);
}

export function AttributeCaptureToJSONTyped(value?: AttributeCapture | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'writes': value['writes'] == null ? undefined : ((value['writes'] as Array<any>).map(AttributeWriteToJSON)),
    };
}

