/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.85.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SlackIntegration } from './SlackIntegration';
import {
    SlackIntegrationFromJSON,
    SlackIntegrationFromJSONTyped,
    SlackIntegrationToJSON,
    SlackIntegrationToJSONTyped,
} from './SlackIntegration';

/**
 * 
 * @export
 * @interface CompleteSlackOAuthResponse
 */
export interface CompleteSlackOAuthResponse {
    /**
     * 
     * @type {SlackIntegration}
     * @memberof CompleteSlackOAuthResponse
     */
    slackIntegration?: SlackIntegration;
}

/**
 * Check if a given object implements the CompleteSlackOAuthResponse interface.
 */
export function instanceOfCompleteSlackOAuthResponse(value: object): value is CompleteSlackOAuthResponse {
    return true;
}

export function CompleteSlackOAuthResponseFromJSON(json: any): CompleteSlackOAuthResponse {
    return CompleteSlackOAuthResponseFromJSONTyped(json, false);
}

export function CompleteSlackOAuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteSlackOAuthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'slackIntegration': json['slackIntegration'] == null ? undefined : SlackIntegrationFromJSON(json['slackIntegration']),
    };
}

export function CompleteSlackOAuthResponseToJSON(json: any): CompleteSlackOAuthResponse {
    return CompleteSlackOAuthResponseToJSONTyped(json, false);
}

export function CompleteSlackOAuthResponseToJSONTyped(value?: CompleteSlackOAuthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slackIntegration': SlackIntegrationToJSON(value['slackIntegration']),
    };
}

