/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers.  ## Authentication  All API endpoints require Bearer token authentication. Obtain your workspace API token from the Linkbreakers dashboard, then include it in the `Authorization` header as `Bearer YOUR_TOKEN`.  When using official SDKs, pass your token to the `accessToken` parameter (NOT `apiKey`) in the Configuration constructor:  ```typescript const config = new Configuration({   accessToken: \'your-workspace-token\',   basePath: \'https://api.linkbreakers.com\', }); ```
 *
 * The version of the OpenAPI document: 1.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContactCardTraceCard } from './ContactCardTraceCard';
import {
    ContactCardTraceCardFromJSON,
    ContactCardTraceCardFromJSONTyped,
    ContactCardTraceCardToJSON,
    ContactCardTraceCardToJSONTyped,
} from './ContactCardTraceCard';

/**
 * ContactCardTraceData stores contact card engagement details.
 * @export
 * @interface ContactCardTraceData
 */
export interface ContactCardTraceData {
    /**
     * 
     * @type {ContactCardTraceCard}
     * @memberof ContactCardTraceData
     */
    card?: ContactCardTraceCard;
}

/**
 * Check if a given object implements the ContactCardTraceData interface.
 */
export function instanceOfContactCardTraceData(value: object): value is ContactCardTraceData {
    return true;
}

export function ContactCardTraceDataFromJSON(json: any): ContactCardTraceData {
    return ContactCardTraceDataFromJSONTyped(json, false);
}

export function ContactCardTraceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactCardTraceData {
    if (json == null) {
        return json;
    }
    return {
        
        'card': json['card'] == null ? undefined : ContactCardTraceCardFromJSON(json['card']),
    };
}

export function ContactCardTraceDataToJSON(json: any): ContactCardTraceData {
    return ContactCardTraceDataToJSONTyped(json, false);
}

export function ContactCardTraceDataToJSONTyped(value?: ContactCardTraceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'card': ContactCardTraceCardToJSON(value['card']),
    };
}

