/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.131.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactSupportResponse
 */
export interface ContactSupportResponse {
    /**
     * Email address the support team will reply to.
     * @type {string}
     * @memberof ContactSupportResponse
     */
    replyToEmail?: string;
}

/**
 * Check if a given object implements the ContactSupportResponse interface.
 */
export function instanceOfContactSupportResponse(value: object): value is ContactSupportResponse {
    return true;
}

export function ContactSupportResponseFromJSON(json: any): ContactSupportResponse {
    return ContactSupportResponseFromJSONTyped(json, false);
}

export function ContactSupportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactSupportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'replyToEmail': json['replyToEmail'] == null ? undefined : json['replyToEmail'],
    };
}

export function ContactSupportResponseToJSON(json: any): ContactSupportResponse {
    return ContactSupportResponseToJSONTyped(json, false);
}

export function ContactSupportResponseToJSONTyped(value?: ContactSupportResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'replyToEmail': value['replyToEmail'],
    };
}

