/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.33.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CountryConditionTraceOption
 */
export interface CountryConditionTraceOption {
    /**
     * 
     * @type {string}
     * @memberof CountryConditionTraceOption
     */
    countryCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CountryConditionTraceOption
     */
    hasRoute?: boolean;
}

/**
 * Check if a given object implements the CountryConditionTraceOption interface.
 */
export function instanceOfCountryConditionTraceOption(value: object): value is CountryConditionTraceOption {
    return true;
}

export function CountryConditionTraceOptionFromJSON(json: any): CountryConditionTraceOption {
    return CountryConditionTraceOptionFromJSONTyped(json, false);
}

export function CountryConditionTraceOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CountryConditionTraceOption {
    if (json == null) {
        return json;
    }
    return {
        
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'hasRoute': json['hasRoute'] == null ? undefined : json['hasRoute'],
    };
}

export function CountryConditionTraceOptionToJSON(json: any): CountryConditionTraceOption {
    return CountryConditionTraceOptionToJSONTyped(json, false);
}

export function CountryConditionTraceOptionToJSONTyped(value?: CountryConditionTraceOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'countryCode': value['countryCode'],
        'hasRoute': value['hasRoute'],
    };
}

