/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.108.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DashboardConfig } from './DashboardConfig';
import {
    DashboardConfigFromJSON,
    DashboardConfigFromJSONTyped,
    DashboardConfigToJSON,
    DashboardConfigToJSONTyped,
} from './DashboardConfig';

/**
 * 
 * @export
 * @interface CreateDashboardRequest
 */
export interface CreateDashboardRequest {
    /**
     * Initial widgets. When empty, a workspace-wide dashboard is seeded with the
     * default widget set and a link-scoped dashboard starts with no widgets.
     * @type {DashboardConfig}
     * @memberof CreateDashboardRequest
     */
    config?: DashboardConfig;
    /**
     * Client-supplied dashboard id. Generated server-side when empty.
     * @type {string}
     * @memberof CreateDashboardRequest
     */
    id?: string;
    /**
     * Link to scope this dashboard to. Empty creates the workspace-wide dashboard.
     * @type {string}
     * @memberof CreateDashboardRequest
     */
    linkId?: string;
    /**
     * Display name. Defaults to "Default Dashboard" when empty.
     * @type {string}
     * @memberof CreateDashboardRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the CreateDashboardRequest interface.
 */
export function instanceOfCreateDashboardRequest(value: object): value is CreateDashboardRequest {
    return true;
}

export function CreateDashboardRequestFromJSON(json: any): CreateDashboardRequest {
    return CreateDashboardRequestFromJSONTyped(json, false);
}

export function CreateDashboardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDashboardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : DashboardConfigFromJSON(json['config']),
        'id': json['id'] == null ? undefined : json['id'],
        'linkId': json['linkId'] == null ? undefined : json['linkId'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CreateDashboardRequestToJSON(json: any): CreateDashboardRequest {
    return CreateDashboardRequestToJSONTyped(json, false);
}

export function CreateDashboardRequestToJSONTyped(value?: CreateDashboardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': DashboardConfigToJSON(value['config']),
        'id': value['id'],
        'linkId': value['linkId'],
        'name': value['name'],
    };
}

