/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.81.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsDashboard } from './AnalyticsDashboard';
import {
    AnalyticsDashboardFromJSON,
    AnalyticsDashboardFromJSONTyped,
    AnalyticsDashboardToJSON,
    AnalyticsDashboardToJSONTyped,
} from './AnalyticsDashboard';

/**
 * 
 * @export
 * @interface CreateDashboardResponse
 */
export interface CreateDashboardResponse {
    /**
     * 
     * @type {AnalyticsDashboard}
     * @memberof CreateDashboardResponse
     */
    dashboard?: AnalyticsDashboard;
}

/**
 * Check if a given object implements the CreateDashboardResponse interface.
 */
export function instanceOfCreateDashboardResponse(value: object): value is CreateDashboardResponse {
    return true;
}

export function CreateDashboardResponseFromJSON(json: any): CreateDashboardResponse {
    return CreateDashboardResponseFromJSONTyped(json, false);
}

export function CreateDashboardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDashboardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'dashboard': json['dashboard'] == null ? undefined : AnalyticsDashboardFromJSON(json['dashboard']),
    };
}

export function CreateDashboardResponseToJSON(json: any): CreateDashboardResponse {
    return CreateDashboardResponseToJSONTyped(json, false);
}

export function CreateDashboardResponseToJSONTyped(value?: CreateDashboardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dashboard': AnalyticsDashboardToJSON(value['dashboard']),
    };
}

