/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
    MediaToJSONTyped,
} from './Media';

/**
 * 
 * @export
 * @interface CreateMediaResponse
 */
export interface CreateMediaResponse {
    /**
     * 
     * @type {Media}
     * @memberof CreateMediaResponse
     */
    media?: Media;
}

/**
 * Check if a given object implements the CreateMediaResponse interface.
 */
export function instanceOfCreateMediaResponse(value: object): value is CreateMediaResponse {
    return true;
}

export function CreateMediaResponseFromJSON(json: any): CreateMediaResponse {
    return CreateMediaResponseFromJSONTyped(json, false);
}

export function CreateMediaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMediaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'media': json['media'] == null ? undefined : MediaFromJSON(json['media']),
    };
}

export function CreateMediaResponseToJSON(json: any): CreateMediaResponse {
    return CreateMediaResponseToJSONTyped(json, false);
}

export function CreateMediaResponseToJSONTyped(value?: CreateMediaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'media': MediaToJSON(value['media']),
    };
}

