/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.122.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VCardData } from './VCardData';
import {
    VCardDataFromJSON,
    VCardDataFromJSONTyped,
    VCardDataToJSON,
    VCardDataToJSONTyped,
} from './VCardData';

/**
 * Request to create a new contact card link.
 * @export
 * @interface CreateContactLinkRequest
 */
export interface CreateContactLinkRequest {
    /**
     * Optional custom domain ID (UUID). Leave empty to use the default domain.
     * Only provide if the user explicitly asks for a specific custom domain.
     * @type {string}
     * @memberof CreateContactLinkRequest
     */
    customDomainId?: string;
    /**
     * Directory to organize this link into. If empty, link is created at root level.
     * @type {string}
     * @memberof CreateContactLinkRequest
     */
    directoryId?: string;
    /**
     * Where visitors are sent once the link has expired.
     * Empty serves the built-in expired page instead.
     * @type {string}
     * @memberof CreateContactLinkRequest
     */
    expiredDestination?: string;
    /**
     * When the link stops resolving. Empty means it never expires.
     * Must be in the future. Once it passes the link is removed from the
     * workspace and only the expired destination is served.
     * @type {Date}
     * @memberof CreateContactLinkRequest
     */
    expiresAt?: Date;
    /**
     * Optional fallback URL if vCard download fails or is not supported.
     * @type {string}
     * @memberof CreateContactLinkRequest
     */
    fallbackDestination?: string;
    /**
     * Optional pre-generated link ID (UUID).
     * The create wizard generates the id up front and navigates to it, so the
     * link has to be created with that id or the page waits on a link that never
     * arrives. Skipped from the AI tool schema for the same reason as on
     * CreateLinkRequest: on a create there is nothing to alias, and exposing it
     * only invites the model to invent a UUID.
     * @type {string}
     * @memberof CreateContactLinkRequest
     */
    id?: string;
    /**
     * A map of string key-value pairs. All values must be strings. Nested objects or arrays are not supported. Maximum of 50 keys.
     * @type {{ [key: string]: string; }}
     * @memberof CreateContactLinkRequest
     */
    metadata?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof CreateContactLinkRequest
     */
    name?: string;
    /**
     * What the user is trying to achieve with this link, in one or two sentences.
     * Lead scoring weights the link from this, and the link's assistant
     * conversations read it as context, so it is restated whenever the workflow
     * changes shape.
     * @type {string}
     * @memberof CreateContactLinkRequest
     */
    purpose?: string;
    /**
     * The QR Code design ID (UUID).
     * If you include this value, the specified design will be associated to this link only.
     * A design can belong to one record at a time (Link or QR Code Template).
     * Trying to use a design that's already assigned will cause an error.
     * @type {string}
     * @memberof CreateContactLinkRequest
     */
    qrcodeDesignId?: string;
    /**
     * The ID of the QR Code template (UUID)
     * If not given, the default QR Code template will be used to generate the QR Code design.
     * @type {string}
     * @memberof CreateContactLinkRequest
     */
    qrcodeTemplateId?: string;
    /**
     * The shortlink for the link
     * If not given, the shortlink will be generated by the system.
     * @type {string}
     * @memberof CreateContactLinkRequest
     */
    shortlink?: string;
    /**
     * List of tags to associate with the link. If a tag doesn't exist, it will be created.
     * @type {Array<string>}
     * @memberof CreateContactLinkRequest
     */
    tags?: Array<string>;
    /**
     * Contact information for the vCard link. This field is required.
     * @type {VCardData}
     * @memberof CreateContactLinkRequest
     */
    vcardData: VCardData;
    /**
     * Wait for QR code generation to complete. Note: This makes the request slower compared to asynchronous generation.
     * @type {boolean}
     * @memberof CreateContactLinkRequest
     */
    waitForQrcode?: boolean;
}

/**
 * Check if a given object implements the CreateContactLinkRequest interface.
 */
export function instanceOfCreateContactLinkRequest(value: object): value is CreateContactLinkRequest {
    if (!('vcardData' in value) || value['vcardData'] === undefined) return false;
    return true;
}

export function CreateContactLinkRequestFromJSON(json: any): CreateContactLinkRequest {
    return CreateContactLinkRequestFromJSONTyped(json, false);
}

export function CreateContactLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateContactLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customDomainId': json['customDomainId'] == null ? undefined : json['customDomainId'],
        'directoryId': json['directoryId'] == null ? undefined : json['directoryId'],
        'expiredDestination': json['expiredDestination'] == null ? undefined : json['expiredDestination'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'fallbackDestination': json['fallbackDestination'] == null ? undefined : json['fallbackDestination'],
        'id': json['id'] == null ? undefined : json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'name': json['name'] == null ? undefined : json['name'],
        'purpose': json['purpose'] == null ? undefined : json['purpose'],
        'qrcodeDesignId': json['qrcodeDesignId'] == null ? undefined : json['qrcodeDesignId'],
        'qrcodeTemplateId': json['qrcodeTemplateId'] == null ? undefined : json['qrcodeTemplateId'],
        'shortlink': json['shortlink'] == null ? undefined : json['shortlink'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'vcardData': VCardDataFromJSON(json['vcardData']),
        'waitForQrcode': json['waitForQrcode'] == null ? undefined : json['waitForQrcode'],
    };
}

export function CreateContactLinkRequestToJSON(json: any): CreateContactLinkRequest {
    return CreateContactLinkRequestToJSONTyped(json, false);
}

export function CreateContactLinkRequestToJSONTyped(value?: CreateContactLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customDomainId': value['customDomainId'],
        'directoryId': value['directoryId'],
        'expiredDestination': value['expiredDestination'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'fallbackDestination': value['fallbackDestination'],
        'id': value['id'],
        'metadata': value['metadata'],
        'name': value['name'],
        'purpose': value['purpose'],
        'qrcodeDesignId': value['qrcodeDesignId'],
        'qrcodeTemplateId': value['qrcodeTemplateId'],
        'shortlink': value['shortlink'],
        'tags': value['tags'],
        'vcardData': VCardDataToJSON(value['vcardData']),
        'waitForQrcode': value['waitForQrcode'],
    };
}

