/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QrcodeTemplate } from './QrcodeTemplate';
import {
    QrcodeTemplateFromJSON,
    QrcodeTemplateFromJSONTyped,
    QrcodeTemplateToJSON,
    QrcodeTemplateToJSONTyped,
} from './QrcodeTemplate';

/**
 * 
 * @export
 * @interface CreateQrcodeTemplateResponse
 */
export interface CreateQrcodeTemplateResponse {
    /**
     * 
     * @type {QrcodeTemplate}
     * @memberof CreateQrcodeTemplateResponse
     */
    qrcodeTemplate?: QrcodeTemplate;
}

/**
 * Check if a given object implements the CreateQrcodeTemplateResponse interface.
 */
export function instanceOfCreateQrcodeTemplateResponse(value: object): value is CreateQrcodeTemplateResponse {
    return true;
}

export function CreateQrcodeTemplateResponseFromJSON(json: any): CreateQrcodeTemplateResponse {
    return CreateQrcodeTemplateResponseFromJSONTyped(json, false);
}

export function CreateQrcodeTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateQrcodeTemplateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'qrcodeTemplate': json['qrcodeTemplate'] == null ? undefined : QrcodeTemplateFromJSON(json['qrcodeTemplate']),
    };
}

export function CreateQrcodeTemplateResponseToJSON(json: any): CreateQrcodeTemplateResponse {
    return CreateQrcodeTemplateResponseToJSONTyped(json, false);
}

export function CreateQrcodeTemplateResponseToJSONTyped(value?: CreateQrcodeTemplateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qrcodeTemplate': QrcodeTemplateToJSON(value['qrcodeTemplate']),
    };
}

