/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.118.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Captures a branded hostname that Linkbreakers provisions for a workspace so scans and shortlinks resolve
 * under the customer's domain, including verification and certificate lifecycle state.
 * @export
 * @interface CustomDomain
 */
export interface CustomDomain {
    /**
     * Timestamp when the domain became active after passing verification and certificate checks.
     * @type {Date}
     * @memberof CustomDomain
     */
    readonly activatedAt?: Date;
    /**
     * When the certificate currently serving this domain expires. While the status is STATUS_RENEWAL_PENDING the domain keeps working until this date, then stops.
     * @type {Date}
     * @memberof CustomDomain
     */
    readonly certificateExpiresAt?: Date;
    /**
     * Raw hostname status reported by the certificate provider, recorded at the last check.
     * @type {string}
     * @memberof CustomDomain
     */
    readonly cloudflareHostnameStatus?: string;
    /**
     * Raw SSL status reported by the certificate provider, recorded at the last check.
     * @type {string}
     * @memberof CustomDomain
     */
    readonly cloudflareSslStatus?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomDomain
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomDomain
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomDomain
     */
    readonly lastCheckedAt?: Date;
    /**
     * Human-readable reason the domain is not fully active, as reported at the last check. Empty when the domain is healthy.
     * @type {string}
     * @memberof CustomDomain
     */
    readonly lastError?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomDomain
     */
    name?: string;
    /**
     * URL where visitors are redirected when accessing your custom domain without a path (e.g., qr.yourdomain.com). This redirect is not tracked and serves purely for white-label purposes—preventing visitors from seeing linkbreakers.com branding. If not specified, redirects to linkbreakers.com by default.
     * @type {string}
     * @memberof CustomDomain
     */
    rootDestination?: string;
    /**
     * The status of a custom domain
     * 
     *  - STATUS_UNSPECIFIED: The status is not specified
     *  - STATUS_INACTIVE: The domain is inactive. It was created but not checked yet.
     *  - STATUS_DOMAIN_PENDING: The domain is pending. Last time it was checked, it was not pointing to the correct Linkbreakers subdomain.
     *  - STATUS_VERIFICATION_PENDING: The domain is pending verification. Please verify through TXT record.
     *  - STATUS_CERTIFICATE_PENDING: The domain is pending certificate. The SSL certificate is not yet ready.
     *  - STATUS_ACTIVE: The domain is fully active
     *  - STATUS_RENEWAL_PENDING: The domain is still serving traffic on a valid certificate, but the renewal
     * of that certificate cannot be validated. It stops working at certificate_expires_at.
     *  - STATUS_EXPIRED: The certificate expired or was withdrawn. The domain no longer serves HTTPS.
     * @type {CustomDomainStatusEnum}
     * @memberof CustomDomain
     */
    status?: CustomDomainStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof CustomDomain
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomDomain
     */
    workspaceId?: string;
}


/**
 * @export
 */
export const CustomDomainStatusEnum = {
    StatusUnspecified: 'STATUS_UNSPECIFIED',
    StatusInactive: 'STATUS_INACTIVE',
    StatusDomainPending: 'STATUS_DOMAIN_PENDING',
    StatusVerificationPending: 'STATUS_VERIFICATION_PENDING',
    StatusCertificatePending: 'STATUS_CERTIFICATE_PENDING',
    StatusActive: 'STATUS_ACTIVE',
    StatusRenewalPending: 'STATUS_RENEWAL_PENDING',
    StatusExpired: 'STATUS_EXPIRED'
} as const;
export type CustomDomainStatusEnum = typeof CustomDomainStatusEnum[keyof typeof CustomDomainStatusEnum];


/**
 * Check if a given object implements the CustomDomain interface.
 */
export function instanceOfCustomDomain(value: object): value is CustomDomain {
    return true;
}

export function CustomDomainFromJSON(json: any): CustomDomain {
    return CustomDomainFromJSONTyped(json, false);
}

export function CustomDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDomain {
    if (json == null) {
        return json;
    }
    return {
        
        'activatedAt': json['activatedAt'] == null ? undefined : (new Date(json['activatedAt'])),
        'certificateExpiresAt': json['certificateExpiresAt'] == null ? undefined : (new Date(json['certificateExpiresAt'])),
        'cloudflareHostnameStatus': json['cloudflareHostnameStatus'] == null ? undefined : json['cloudflareHostnameStatus'],
        'cloudflareSslStatus': json['cloudflareSslStatus'] == null ? undefined : json['cloudflareSslStatus'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'lastCheckedAt': json['lastCheckedAt'] == null ? undefined : (new Date(json['lastCheckedAt'])),
        'lastError': json['lastError'] == null ? undefined : json['lastError'],
        'name': json['name'] == null ? undefined : json['name'],
        'rootDestination': json['rootDestination'] == null ? undefined : json['rootDestination'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'workspaceId': json['workspaceId'] == null ? undefined : json['workspaceId'],
    };
}

export function CustomDomainToJSON(json: any): CustomDomain {
    return CustomDomainToJSONTyped(json, false);
}

export function CustomDomainToJSONTyped(value?: Omit<CustomDomain, 'activatedAt'|'certificateExpiresAt'|'cloudflareHostnameStatus'|'cloudflareSslStatus'|'createdAt'|'lastCheckedAt'|'lastError'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'rootDestination': value['rootDestination'],
        'status': value['status'],
        'workspaceId': value['workspaceId'],
    };
}

