/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.149.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - CUSTOM_DOMAIN_SETUP_HINT_UNSPECIFIED: Not specified
 *  - CUSTOM_DOMAIN_SETUP_HINT_CLOUDFLARE_DNS_ONLY: Cloudflare: the CNAME's proxy status must be "DNS only" (grey cloud), or Linkbreakers cannot see it
 *  - CUSTOM_DOMAIN_SETUP_HINT_APEX_DOMAIN: The domain is a root domain: most providers do not allow a CNAME there, a subdomain such as qr.example.com is recommended
 *  - CUSTOM_DOMAIN_SETUP_HINT_NAMESERVERS_NOT_FOUND: The nameservers could not be read: the domain may not be registered yet, or its DNS is not set up
 *  - CUSTOM_DOMAIN_SETUP_HINT_GOOGLE_DOMAINS_MOVED: The nameservers are Google's. Domains bought through Google Domains use them too and are now managed at Squarespace
 * @export
 */
export const CustomDomainSetupHint = {
    CustomDomainSetupHintUnspecified: 'CUSTOM_DOMAIN_SETUP_HINT_UNSPECIFIED',
    CustomDomainSetupHintCloudflareDnsOnly: 'CUSTOM_DOMAIN_SETUP_HINT_CLOUDFLARE_DNS_ONLY',
    CustomDomainSetupHintApexDomain: 'CUSTOM_DOMAIN_SETUP_HINT_APEX_DOMAIN',
    CustomDomainSetupHintNameserversNotFound: 'CUSTOM_DOMAIN_SETUP_HINT_NAMESERVERS_NOT_FOUND',
    CustomDomainSetupHintGoogleDomainsMoved: 'CUSTOM_DOMAIN_SETUP_HINT_GOOGLE_DOMAINS_MOVED'
} as const;
export type CustomDomainSetupHint = typeof CustomDomainSetupHint[keyof typeof CustomDomainSetupHint];


export function instanceOfCustomDomainSetupHint(value: any): boolean {
    for (const key in CustomDomainSetupHint) {
        if (Object.prototype.hasOwnProperty.call(CustomDomainSetupHint, key)) {
            if (CustomDomainSetupHint[key as keyof typeof CustomDomainSetupHint] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CustomDomainSetupHintFromJSON(json: any): CustomDomainSetupHint {
    return CustomDomainSetupHintFromJSONTyped(json, false);
}

export function CustomDomainSetupHintFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDomainSetupHint {
    return json as CustomDomainSetupHint;
}

export function CustomDomainSetupHintToJSON(value?: CustomDomainSetupHint | null): any {
    return value as any;
}

export function CustomDomainSetupHintToJSONTyped(value: any, ignoreDiscriminator: boolean): CustomDomainSetupHint {
    return value as CustomDomainSetupHint;
}

