/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DnsRecordPurpose } from './DnsRecordPurpose';
import {
    DnsRecordPurposeFromJSON,
    DnsRecordPurposeFromJSONTyped,
    DnsRecordPurposeToJSON,
    DnsRecordPurposeToJSONTyped,
} from './DnsRecordPurpose';
import type { DnsRecordType } from './DnsRecordType';
import {
    DnsRecordTypeFromJSON,
    DnsRecordTypeFromJSONTyped,
    DnsRecordTypeToJSON,
    DnsRecordTypeToJSONTyped,
} from './DnsRecordType';

/**
 * 
 * @export
 * @interface CustomDomainDnsRecord
 */
export interface CustomDomainDnsRecord {
    /**
     * 
     * @type {boolean}
     * @memberof CustomDomainDnsRecord
     */
    detected?: boolean;
    /**
     * What to type in the provider's host field: the name relative to the zone,
     * e.g. "qr". For the zone apex, "@", or empty when the provider wants the
     * field left blank.
     * @type {string}
     * @memberof CustomDomainDnsRecord
     */
    host?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomDomainDnsRecord
     */
    name?: string;
    /**
     * 
     * @type {DnsRecordPurpose}
     * @memberof CustomDomainDnsRecord
     */
    purpose?: DnsRecordPurpose;
    /**
     * Whether setup is incomplete without it. The routing record and the
     * certificate delegation record (which keeps HTTPS renewing on its own) are
     * both required.
     * @type {boolean}
     * @memberof CustomDomainDnsRecord
     */
    required?: boolean;
    /**
     * 
     * @type {DnsRecordType}
     * @memberof CustomDomainDnsRecord
     */
    type?: DnsRecordType;
    /**
     * 
     * @type {string}
     * @memberof CustomDomainDnsRecord
     */
    value?: string;
}



/**
 * Check if a given object implements the CustomDomainDnsRecord interface.
 */
export function instanceOfCustomDomainDnsRecord(value: object): value is CustomDomainDnsRecord {
    return true;
}

export function CustomDomainDnsRecordFromJSON(json: any): CustomDomainDnsRecord {
    return CustomDomainDnsRecordFromJSONTyped(json, false);
}

export function CustomDomainDnsRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDomainDnsRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'detected': json['detected'] == null ? undefined : json['detected'],
        'host': json['host'] == null ? undefined : json['host'],
        'name': json['name'] == null ? undefined : json['name'],
        'purpose': json['purpose'] == null ? undefined : DnsRecordPurposeFromJSON(json['purpose']),
        'required': json['required'] == null ? undefined : json['required'],
        'type': json['type'] == null ? undefined : DnsRecordTypeFromJSON(json['type']),
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function CustomDomainDnsRecordToJSON(json: any): CustomDomainDnsRecord {
    return CustomDomainDnsRecordToJSONTyped(json, false);
}

export function CustomDomainDnsRecordToJSONTyped(value?: CustomDomainDnsRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'detected': value['detected'],
        'host': value['host'],
        'name': value['name'],
        'purpose': DnsRecordPurposeToJSON(value['purpose']),
        'required': value['required'],
        'type': DnsRecordTypeToJSON(value['type']),
        'value': value['value'],
    };
}

