/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.33.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Captures a branded hostname that Linkbreakers provisions for a workspace so scans and shortlinks resolve
 * under the customer's domain, including verification and certificate lifecycle state.
 * @export
 * @interface CustomDomain
 */
export interface CustomDomain {
    /**
     * Timestamp when the domain became active after passing verification and certificate checks.
     * @type {Date}
     * @memberof CustomDomain
     */
    readonly activatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomDomain
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomDomain
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomDomain
     */
    readonly lastCheckedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomDomain
     */
    name?: string;
    /**
     * The status of a custom domain
     * 
     *  - STATUS_UNSPECIFIED: The status is not specified
     *  - STATUS_INACTIVE: The domain is inactive. It was created but not checked yet.
     *  - STATUS_DOMAIN_PENDING: The domain is pending. Last time it was checked, it was not pointing to the correct Linkbreakers subdomain.
     *  - STATUS_VERIFICATION_PENDING: The domain is pending verification. Please verify through TXT record.
     *  - STATUS_CERTIFICATE_PENDING: The domain is pending certificate. The SSL certificate is not yet ready.
     *  - STATUS_ACTIVE: The domain is fully active
     * @type {CustomDomainStatusEnum}
     * @memberof CustomDomain
     */
    status?: CustomDomainStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof CustomDomain
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomDomain
     */
    workspaceId?: string;
}


/**
 * @export
 */
export const CustomDomainStatusEnum = {
    StatusUnspecified: 'STATUS_UNSPECIFIED',
    StatusInactive: 'STATUS_INACTIVE',
    StatusDomainPending: 'STATUS_DOMAIN_PENDING',
    StatusVerificationPending: 'STATUS_VERIFICATION_PENDING',
    StatusCertificatePending: 'STATUS_CERTIFICATE_PENDING',
    StatusActive: 'STATUS_ACTIVE'
} as const;
export type CustomDomainStatusEnum = typeof CustomDomainStatusEnum[keyof typeof CustomDomainStatusEnum];


/**
 * Check if a given object implements the CustomDomain interface.
 */
export function instanceOfCustomDomain(value: object): value is CustomDomain {
    return true;
}

export function CustomDomainFromJSON(json: any): CustomDomain {
    return CustomDomainFromJSONTyped(json, false);
}

export function CustomDomainFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomDomain {
    if (json == null) {
        return json;
    }
    return {
        
        'activatedAt': json['activatedAt'] == null ? undefined : (new Date(json['activatedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'lastCheckedAt': json['lastCheckedAt'] == null ? undefined : (new Date(json['lastCheckedAt'])),
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'workspaceId': json['workspaceId'] == null ? undefined : json['workspaceId'],
    };
}

export function CustomDomainToJSON(json: any): CustomDomain {
    return CustomDomainToJSONTyped(json, false);
}

export function CustomDomainToJSONTyped(value?: Omit<CustomDomain, 'activatedAt'|'createdAt'|'lastCheckedAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'status': value['status'],
        'workspaceId': value['workspaceId'],
    };
}

