/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.111.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DashboardScope selects dashboards by whether they are tied to a link.
 * 
 *  - DASHBOARD_SCOPE_UNSPECIFIED: Every dashboard in the workspace, link-scoped or not.
 *  - DASHBOARD_SCOPE_WORKSPACE: Only the workspace-wide dashboard, the one with no link.
 *  - DASHBOARD_SCOPE_LINK: Only dashboards tied to a link.
 * @export
 */
export const DashboardScope = {
    DashboardScopeUnspecified: 'DASHBOARD_SCOPE_UNSPECIFIED',
    DashboardScopeWorkspace: 'DASHBOARD_SCOPE_WORKSPACE',
    DashboardScopeLink: 'DASHBOARD_SCOPE_LINK'
} as const;
export type DashboardScope = typeof DashboardScope[keyof typeof DashboardScope];


export function instanceOfDashboardScope(value: any): boolean {
    for (const key in DashboardScope) {
        if (Object.prototype.hasOwnProperty.call(DashboardScope, key)) {
            if (DashboardScope[key as keyof typeof DashboardScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DashboardScopeFromJSON(json: any): DashboardScope {
    return DashboardScopeFromJSONTyped(json, false);
}

export function DashboardScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardScope {
    return json as DashboardScope;
}

export function DashboardScopeToJSON(value?: DashboardScope | null): any {
    return value as any;
}

export function DashboardScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): DashboardScope {
    return value as DashboardScope;
}

