/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.77.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WidgetPosition } from './WidgetPosition';
import {
    WidgetPositionFromJSON,
    WidgetPositionFromJSONTyped,
    WidgetPositionToJSON,
    WidgetPositionToJSONTyped,
} from './WidgetPosition';
import type { WidgetSize } from './WidgetSize';
import {
    WidgetSizeFromJSON,
    WidgetSizeFromJSONTyped,
    WidgetSizeToJSON,
    WidgetSizeToJSONTyped,
} from './WidgetSize';
import type { WidgetDataSource } from './WidgetDataSource';
import {
    WidgetDataSourceFromJSON,
    WidgetDataSourceFromJSONTyped,
    WidgetDataSourceToJSON,
    WidgetDataSourceToJSONTyped,
} from './WidgetDataSource';
import type { WidgetVisualization } from './WidgetVisualization';
import {
    WidgetVisualizationFromJSON,
    WidgetVisualizationFromJSONTyped,
    WidgetVisualizationToJSON,
    WidgetVisualizationToJSONTyped,
} from './WidgetVisualization';

/**
 * 
 * @export
 * @interface DashboardWidget
 */
export interface DashboardWidget {
    /**
     * 
     * @type {WidgetDataSource}
     * @memberof DashboardWidget
     */
    dataSource?: WidgetDataSource;
    /**
     * 
     * @type {string}
     * @memberof DashboardWidget
     */
    id?: string;
    /**
     * 
     * @type {WidgetPosition}
     * @memberof DashboardWidget
     */
    position?: WidgetPosition;
    /**
     * 
     * @type {WidgetSize}
     * @memberof DashboardWidget
     */
    size?: WidgetSize;
    /**
     * 
     * @type {string}
     * @memberof DashboardWidget
     */
    title?: string;
    /**
     * 
     * @type {WidgetVisualization}
     * @memberof DashboardWidget
     */
    visualization?: WidgetVisualization;
}

/**
 * Check if a given object implements the DashboardWidget interface.
 */
export function instanceOfDashboardWidget(value: object): value is DashboardWidget {
    return true;
}

export function DashboardWidgetFromJSON(json: any): DashboardWidget {
    return DashboardWidgetFromJSONTyped(json, false);
}

export function DashboardWidgetFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardWidget {
    if (json == null) {
        return json;
    }
    return {
        
        'dataSource': json['dataSource'] == null ? undefined : WidgetDataSourceFromJSON(json['dataSource']),
        'id': json['id'] == null ? undefined : json['id'],
        'position': json['position'] == null ? undefined : WidgetPositionFromJSON(json['position']),
        'size': json['size'] == null ? undefined : WidgetSizeFromJSON(json['size']),
        'title': json['title'] == null ? undefined : json['title'],
        'visualization': json['visualization'] == null ? undefined : WidgetVisualizationFromJSON(json['visualization']),
    };
}

export function DashboardWidgetToJSON(json: any): DashboardWidget {
    return DashboardWidgetToJSONTyped(json, false);
}

export function DashboardWidgetToJSONTyped(value?: DashboardWidget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dataSource': WidgetDataSourceToJSON(value['dataSource']),
        'id': value['id'],
        'position': WidgetPositionToJSON(value['position']),
        'size': WidgetSizeToJSON(value['size']),
        'title': value['title'],
        'visualization': WidgetVisualizationToJSON(value['visualization']),
    };
}

