/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DayOfWeekOption
 */
export interface DayOfWeekOption {
    /**
     * Days of the week: 0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday
     * @type {Array<number>}
     * @memberof DayOfWeekOption
     */
    daysOfWeek?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof DayOfWeekOption
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DayOfWeekOption
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DayOfWeekOption
     */
    nextStepId?: string;
}

/**
 * Check if a given object implements the DayOfWeekOption interface.
 */
export function instanceOfDayOfWeekOption(value: object): value is DayOfWeekOption {
    return true;
}

export function DayOfWeekOptionFromJSON(json: any): DayOfWeekOption {
    return DayOfWeekOptionFromJSONTyped(json, false);
}

export function DayOfWeekOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayOfWeekOption {
    if (json == null) {
        return json;
    }
    return {
        
        'daysOfWeek': json['daysOfWeek'] == null ? undefined : json['daysOfWeek'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'nextStepId': json['nextStepId'] == null ? undefined : json['nextStepId'],
    };
}

export function DayOfWeekOptionToJSON(json: any): DayOfWeekOption {
    return DayOfWeekOptionToJSONTyped(json, false);
}

export function DayOfWeekOptionToJSONTyped(value?: DayOfWeekOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'daysOfWeek': value['daysOfWeek'],
        'id': value['id'],
        'name': value['name'],
        'nextStepId': value['nextStepId'],
    };
}

