/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DayOfWeekConditionTraceOption } from './DayOfWeekConditionTraceOption';
import {
    DayOfWeekConditionTraceOptionFromJSON,
    DayOfWeekConditionTraceOptionFromJSONTyped,
    DayOfWeekConditionTraceOptionToJSON,
    DayOfWeekConditionTraceOptionToJSONTyped,
} from './DayOfWeekConditionTraceOption';

/**
 * DayOfWeekConditionTraceData stores day-of-week condition routing metadata.
 * @export
 * @interface DayOfWeekConditionTraceData
 */
export interface DayOfWeekConditionTraceData {
    /**
     * 
     * @type {boolean}
     * @memberof DayOfWeekConditionTraceData
     */
    hasElse?: boolean;
    /**
     * 
     * @type {Array<DayOfWeekConditionTraceOption>}
     * @memberof DayOfWeekConditionTraceData
     */
    options?: Array<DayOfWeekConditionTraceOption>;
}

/**
 * Check if a given object implements the DayOfWeekConditionTraceData interface.
 */
export function instanceOfDayOfWeekConditionTraceData(value: object): value is DayOfWeekConditionTraceData {
    return true;
}

export function DayOfWeekConditionTraceDataFromJSON(json: any): DayOfWeekConditionTraceData {
    return DayOfWeekConditionTraceDataFromJSONTyped(json, false);
}

export function DayOfWeekConditionTraceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DayOfWeekConditionTraceData {
    if (json == null) {
        return json;
    }
    return {
        
        'hasElse': json['hasElse'] == null ? undefined : json['hasElse'],
        'options': json['options'] == null ? undefined : ((json['options'] as Array<any>).map(DayOfWeekConditionTraceOptionFromJSON)),
    };
}

export function DayOfWeekConditionTraceDataToJSON(json: any): DayOfWeekConditionTraceData {
    return DayOfWeekConditionTraceDataToJSONTyped(json, false);
}

export function DayOfWeekConditionTraceDataToJSONTyped(value?: DayOfWeekConditionTraceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasElse': value['hasElse'],
        'options': value['options'] == null ? undefined : ((value['options'] as Array<any>).map(DayOfWeekConditionTraceOptionToJSON)),
    };
}

