/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Tracks the fingerprint of a visitor's hardware/software so Linkbreakers can de-duplicate scans, enrich analytics,
 * and power security heuristics.
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    asn?: number;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    browserLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    browserName?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    browserVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    country?: string;
    /**
     * 
     * @type {Date}
     * @memberof Device
     */
    createdAt?: Date;
    /**
     * DeviceActor represents WHO or WHAT is operating the device.
     * This distinguishes between a real human visitor, an automated crawler/scraper bot
     * (e.g. Googlebot, BingBot), and an AI/LLM agent acting on behalf of a user
     * (e.g. GPTBot, ClaudeBot, Gemini, Grok).
     * 
     *  - DEVICE_ACTOR_UNSPECIFIED: Actor not specified or not yet detected
     *  - DEVICE_ACTOR_HUMAN: Human visitor using a browser (covers MOBILE, TABLET, DESKTOP device types)
     *  - DEVICE_ACTOR_BOT: Automated crawler or scraper bot (e.g. Googlebot, BingBot, Applebot)
     *  - DEVICE_ACTOR_AGENT: AI/LLM agent browsing on behalf of a user (e.g. GPTBot, ClaudeBot, Gemini, Grok)
     *  - DEVICE_ACTOR_UNKNOWN: Unable to classify the actor
     * @type {DeviceDeviceActorEnum}
     * @memberof Device
     */
    deviceActor?: DeviceDeviceActorEnum;
    /**
     * Specific actor or crawler name for non-human traffic (e.g. "Googlebot", "GPTBot", "ClaudeBot").
     * Only populated when device_actor is BOT or AGENT. Null/empty for HUMAN visitors.
     * @type {string}
     * @memberof Device
     */
    deviceActorName?: string;
    /**
     * Company or organization behind the actor (e.g. "Google", "OpenAI", "Anthropic").
     * Only populated when device_actor is BOT or AGENT. Null/empty for HUMAN visitors.
     * @type {string}
     * @memberof Device
     */
    deviceActorOrigin?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    deviceBrand?: string;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    deviceConcurrency?: number;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    deviceMemory?: number;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    deviceName?: string;
    /**
     * DeviceType represents the physical form factor of the device.
     * This describes the hardware category (phone, tablet, laptop, etc.),
     * NOT who or what is operating it — see DeviceActor for that.
     * 
     *  - DEVICE_TYPE_UNSPECIFIED: Device type not specified or not yet detected
     *  - DEVICE_TYPE_NATIVE: Native QR scanner (no browser capabilities reported)
     *  - DEVICE_TYPE_MOBILE: Mobile handset browser
     *  - DEVICE_TYPE_TABLET: Tablet browser
     *  - DEVICE_TYPE_DESKTOP: Desktop or laptop browser
     *  - DEVICE_TYPE_UNKNOWN: Unable to classify the device
     * @type {DeviceDeviceTypeEnum}
     * @memberof Device
     */
    deviceType?: DeviceDeviceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    gpu?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    ipAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    isp?: string;
    /**
     * 
     * @type {Date}
     * @memberof Device
     */
    lastUsedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    networkBandwidth?: number;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    networkConnection?: string;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    networkRtt?: number;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    platformName?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    platformVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    region?: string;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    screenHeight?: number;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    screenRatio?: number;
    /**
     * 
     * @type {number}
     * @memberof Device
     */
    screenWidth?: number;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    timezone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Device
     */
    touchScreen?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Device
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Device
     */
    userAgent?: string;
}


/**
 * @export
 */
export const DeviceDeviceActorEnum = {
    DeviceActorUnspecified: 'DEVICE_ACTOR_UNSPECIFIED',
    DeviceActorHuman: 'DEVICE_ACTOR_HUMAN',
    DeviceActorBot: 'DEVICE_ACTOR_BOT',
    DeviceActorAgent: 'DEVICE_ACTOR_AGENT',
    DeviceActorUnknown: 'DEVICE_ACTOR_UNKNOWN'
} as const;
export type DeviceDeviceActorEnum = typeof DeviceDeviceActorEnum[keyof typeof DeviceDeviceActorEnum];

/**
 * @export
 */
export const DeviceDeviceTypeEnum = {
    DeviceTypeUnspecified: 'DEVICE_TYPE_UNSPECIFIED',
    DeviceTypeNative: 'DEVICE_TYPE_NATIVE',
    DeviceTypeMobile: 'DEVICE_TYPE_MOBILE',
    DeviceTypeTablet: 'DEVICE_TYPE_TABLET',
    DeviceTypeDesktop: 'DEVICE_TYPE_DESKTOP',
    DeviceTypeUnknown: 'DEVICE_TYPE_UNKNOWN'
} as const;
export type DeviceDeviceTypeEnum = typeof DeviceDeviceTypeEnum[keyof typeof DeviceDeviceTypeEnum];


/**
 * Check if a given object implements the Device interface.
 */
export function instanceOfDevice(value: object): value is Device {
    return true;
}

export function DeviceFromJSON(json: any): Device {
    return DeviceFromJSONTyped(json, false);
}

export function DeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Device {
    if (json == null) {
        return json;
    }
    return {
        
        'asn': json['asn'] == null ? undefined : json['asn'],
        'browserLanguage': json['browserLanguage'] == null ? undefined : json['browserLanguage'],
        'browserName': json['browserName'] == null ? undefined : json['browserName'],
        'browserVersion': json['browserVersion'] == null ? undefined : json['browserVersion'],
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'deviceActor': json['deviceActor'] == null ? undefined : json['deviceActor'],
        'deviceActorName': json['deviceActorName'] == null ? undefined : json['deviceActorName'],
        'deviceActorOrigin': json['deviceActorOrigin'] == null ? undefined : json['deviceActorOrigin'],
        'deviceBrand': json['deviceBrand'] == null ? undefined : json['deviceBrand'],
        'deviceConcurrency': json['deviceConcurrency'] == null ? undefined : json['deviceConcurrency'],
        'deviceMemory': json['deviceMemory'] == null ? undefined : json['deviceMemory'],
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
        'deviceType': json['deviceType'] == null ? undefined : json['deviceType'],
        'gpu': json['gpu'] == null ? undefined : json['gpu'],
        'id': json['id'] == null ? undefined : json['id'],
        'ipAddress': json['ipAddress'] == null ? undefined : json['ipAddress'],
        'isp': json['isp'] == null ? undefined : json['isp'],
        'lastUsedAt': json['lastUsedAt'] == null ? undefined : (new Date(json['lastUsedAt'])),
        'networkBandwidth': json['networkBandwidth'] == null ? undefined : json['networkBandwidth'],
        'networkConnection': json['networkConnection'] == null ? undefined : json['networkConnection'],
        'networkRtt': json['networkRtt'] == null ? undefined : json['networkRtt'],
        'platformName': json['platformName'] == null ? undefined : json['platformName'],
        'platformVersion': json['platformVersion'] == null ? undefined : json['platformVersion'],
        'region': json['region'] == null ? undefined : json['region'],
        'screenHeight': json['screenHeight'] == null ? undefined : json['screenHeight'],
        'screenRatio': json['screenRatio'] == null ? undefined : json['screenRatio'],
        'screenWidth': json['screenWidth'] == null ? undefined : json['screenWidth'],
        'state': json['state'] == null ? undefined : json['state'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'touchScreen': json['touchScreen'] == null ? undefined : json['touchScreen'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
    };
}

export function DeviceToJSON(json: any): Device {
    return DeviceToJSONTyped(json, false);
}

export function DeviceToJSONTyped(value?: Device | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'asn': value['asn'],
        'browserLanguage': value['browserLanguage'],
        'browserName': value['browserName'],
        'browserVersion': value['browserVersion'],
        'city': value['city'],
        'country': value['country'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'deviceActor': value['deviceActor'],
        'deviceActorName': value['deviceActorName'],
        'deviceActorOrigin': value['deviceActorOrigin'],
        'deviceBrand': value['deviceBrand'],
        'deviceConcurrency': value['deviceConcurrency'],
        'deviceMemory': value['deviceMemory'],
        'deviceName': value['deviceName'],
        'deviceType': value['deviceType'],
        'gpu': value['gpu'],
        'id': value['id'],
        'ipAddress': value['ipAddress'],
        'isp': value['isp'],
        'lastUsedAt': value['lastUsedAt'] == null ? value['lastUsedAt'] : value['lastUsedAt'].toISOString(),
        'networkBandwidth': value['networkBandwidth'],
        'networkConnection': value['networkConnection'],
        'networkRtt': value['networkRtt'],
        'platformName': value['platformName'],
        'platformVersion': value['platformVersion'],
        'region': value['region'],
        'screenHeight': value['screenHeight'],
        'screenRatio': value['screenRatio'],
        'screenWidth': value['screenWidth'],
        'state': value['state'],
        'timezone': value['timezone'],
        'touchScreen': value['touchScreen'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'userAgent': value['userAgent'],
    };
}

