/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeviceBrandConditionValue } from './DeviceBrandConditionValue';
import {
    DeviceBrandConditionValueFromJSON,
    DeviceBrandConditionValueFromJSONTyped,
    DeviceBrandConditionValueToJSON,
    DeviceBrandConditionValueToJSONTyped,
} from './DeviceBrandConditionValue';

/**
 * Device brand condition option for EVENT_ACTION_DEVICE_BRAND_CONDITION.
 * @export
 * @interface DeviceBrandConditionOption
 */
export interface DeviceBrandConditionOption {
    /**
     * 
     * @type {string}
     * @memberof DeviceBrandConditionOption
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceBrandConditionOption
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceBrandConditionOption
     */
    nextStepId?: string;
    /**
     * Hardware brand to match.
     * @type {DeviceBrandConditionValue}
     * @memberof DeviceBrandConditionOption
     */
    value?: DeviceBrandConditionValue;
}



/**
 * Check if a given object implements the DeviceBrandConditionOption interface.
 */
export function instanceOfDeviceBrandConditionOption(value: object): value is DeviceBrandConditionOption {
    return true;
}

export function DeviceBrandConditionOptionFromJSON(json: any): DeviceBrandConditionOption {
    return DeviceBrandConditionOptionFromJSONTyped(json, false);
}

export function DeviceBrandConditionOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceBrandConditionOption {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'nextStepId': json['nextStepId'] == null ? undefined : json['nextStepId'],
        'value': json['value'] == null ? undefined : DeviceBrandConditionValueFromJSON(json['value']),
    };
}

export function DeviceBrandConditionOptionToJSON(json: any): DeviceBrandConditionOption {
    return DeviceBrandConditionOptionToJSONTyped(json, false);
}

export function DeviceBrandConditionOptionToJSONTyped(value?: DeviceBrandConditionOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'nextStepId': value['nextStepId'],
        'value': DeviceBrandConditionValueToJSON(value['value']),
    };
}

