/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceActorConditionTraceOption
 */
export interface DeviceActorConditionTraceOption {
    /**
     * 
     * @type {string}
     * @memberof DeviceActorConditionTraceOption
     */
    deviceActor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DeviceActorConditionTraceOption
     */
    hasRoute?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeviceActorConditionTraceOption
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceActorConditionTraceOption
     */
    name?: string;
}

/**
 * Check if a given object implements the DeviceActorConditionTraceOption interface.
 */
export function instanceOfDeviceActorConditionTraceOption(value: object): value is DeviceActorConditionTraceOption {
    return true;
}

export function DeviceActorConditionTraceOptionFromJSON(json: any): DeviceActorConditionTraceOption {
    return DeviceActorConditionTraceOptionFromJSONTyped(json, false);
}

export function DeviceActorConditionTraceOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceActorConditionTraceOption {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceActor': json['deviceActor'] == null ? undefined : json['deviceActor'],
        'hasRoute': json['hasRoute'] == null ? undefined : json['hasRoute'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DeviceActorConditionTraceOptionToJSON(json: any): DeviceActorConditionTraceOption {
    return DeviceActorConditionTraceOptionToJSONTyped(json, false);
}

export function DeviceActorConditionTraceOptionToJSONTyped(value?: DeviceActorConditionTraceOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deviceActor': value['deviceActor'],
        'hasRoute': value['hasRoute'],
        'id': value['id'],
        'name': value['name'],
    };
}

