/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.14
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DeviceActor represents WHO or WHAT is operating the device.
 * This distinguishes between a real human visitor, an automated crawler/scraper bot
 * (e.g. Googlebot, BingBot), and an AI/LLM agent acting on behalf of a user
 * (e.g. GPTBot, ClaudeBot, Gemini, Grok).
 * 
 *  - DEVICE_ACTOR_UNSPECIFIED: Actor not specified or not yet detected
 *  - DEVICE_ACTOR_HUMAN: Human visitor using a browser (covers MOBILE, TABLET, DESKTOP device types)
 *  - DEVICE_ACTOR_BOT: Automated crawler or scraper bot (e.g. Googlebot, BingBot, Applebot)
 *  - DEVICE_ACTOR_AGENT: AI/LLM agent browsing on behalf of a user (e.g. GPTBot, ClaudeBot, Gemini, Grok)
 *  - DEVICE_ACTOR_UNKNOWN: Unable to classify the actor
 * @export
 */
export const DeviceActor = {
    DeviceActorUnspecified: 'DEVICE_ACTOR_UNSPECIFIED',
    DeviceActorHuman: 'DEVICE_ACTOR_HUMAN',
    DeviceActorBot: 'DEVICE_ACTOR_BOT',
    DeviceActorAgent: 'DEVICE_ACTOR_AGENT',
    DeviceActorUnknown: 'DEVICE_ACTOR_UNKNOWN'
} as const;
export type DeviceActor = typeof DeviceActor[keyof typeof DeviceActor];


export function instanceOfDeviceActor(value: any): boolean {
    for (const key in DeviceActor) {
        if (Object.prototype.hasOwnProperty.call(DeviceActor, key)) {
            if (DeviceActor[key as keyof typeof DeviceActor] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DeviceActorFromJSON(json: any): DeviceActor {
    return DeviceActorFromJSONTyped(json, false);
}

export function DeviceActorFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceActor {
    return json as DeviceActor;
}

export function DeviceActorToJSON(value?: DeviceActor | null): any {
    return value as any;
}

export function DeviceActorToJSONTyped(value: any, ignoreDiscriminator: boolean): DeviceActor {
    return value as DeviceActor;
}

