/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.89.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - DIGEST_FREQUENCY_UNSPECIFIED: Not specified; defaults to monthly
 *  - DIGEST_FREQUENCY_NONE: No digest emails
 *  - DIGEST_FREQUENCY_WEEKLY: Weekly digest every Monday
 *  - DIGEST_FREQUENCY_MONTHLY: Monthly digest on the 1st of each month
 * @export
 */
export const DigestFrequency = {
    DigestFrequencyUnspecified: 'DIGEST_FREQUENCY_UNSPECIFIED',
    DigestFrequencyNone: 'DIGEST_FREQUENCY_NONE',
    DigestFrequencyWeekly: 'DIGEST_FREQUENCY_WEEKLY',
    DigestFrequencyMonthly: 'DIGEST_FREQUENCY_MONTHLY'
} as const;
export type DigestFrequency = typeof DigestFrequency[keyof typeof DigestFrequency];


export function instanceOfDigestFrequency(value: any): boolean {
    for (const key in DigestFrequency) {
        if (Object.prototype.hasOwnProperty.call(DigestFrequency, key)) {
            if (DigestFrequency[key as keyof typeof DigestFrequency] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DigestFrequencyFromJSON(json: any): DigestFrequency {
    return DigestFrequencyFromJSONTyped(json, false);
}

export function DigestFrequencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigestFrequency {
    return json as DigestFrequency;
}

export function DigestFrequencyToJSON(value?: DigestFrequency | null): any {
    return value as any;
}

export function DigestFrequencyToJSONTyped(value: any, ignoreDiscriminator: boolean): DigestFrequency {
    return value as DigestFrequency;
}

