/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.149.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanLimitKey } from './PlanLimitKey';
import {
    PlanLimitKeyFromJSON,
    PlanLimitKeyFromJSONTyped,
    PlanLimitKeyToJSON,
    PlanLimitKeyToJSONTyped,
} from './PlanLimitKey';

/**
 * 
 * @export
 * @interface DismissAllowanceNoticeRequest
 */
export interface DismissAllowanceNoticeRequest {
    /**
     * 
     * @type {PlanLimitKey}
     * @memberof DismissAllowanceNoticeRequest
     */
    key?: PlanLimitKey;
}



/**
 * Check if a given object implements the DismissAllowanceNoticeRequest interface.
 */
export function instanceOfDismissAllowanceNoticeRequest(value: object): value is DismissAllowanceNoticeRequest {
    return true;
}

export function DismissAllowanceNoticeRequestFromJSON(json: any): DismissAllowanceNoticeRequest {
    return DismissAllowanceNoticeRequestFromJSONTyped(json, false);
}

export function DismissAllowanceNoticeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DismissAllowanceNoticeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : PlanLimitKeyFromJSON(json['key']),
    };
}

export function DismissAllowanceNoticeRequestToJSON(json: any): DismissAllowanceNoticeRequest {
    return DismissAllowanceNoticeRequestToJSONTyped(json, false);
}

export function DismissAllowanceNoticeRequestToJSONTyped(value?: DismissAllowanceNoticeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': PlanLimitKeyToJSON(value['key']),
    };
}

