/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.143.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - DNS_PROVIDER_UNSPECIFIED: Not detected
 *  - DNS_PROVIDER_UNKNOWN: The nameservers do not match any provider Linkbreakers knows
 * @export
 */
export const DnsProvider = {
    DnsProviderUnspecified: 'DNS_PROVIDER_UNSPECIFIED',
    DnsProviderUnknown: 'DNS_PROVIDER_UNKNOWN',
    DnsProviderCloudflare: 'DNS_PROVIDER_CLOUDFLARE',
    DnsProviderGodaddy: 'DNS_PROVIDER_GODADDY',
    DnsProviderNamecheap: 'DNS_PROVIDER_NAMECHEAP',
    DnsProviderSquarespace: 'DNS_PROVIDER_SQUARESPACE',
    DnsProviderIonos: 'DNS_PROVIDER_IONOS',
    DnsProviderOvhcloud: 'DNS_PROVIDER_OVHCLOUD',
    DnsProviderGandi: 'DNS_PROVIDER_GANDI',
    DnsProviderHostinger: 'DNS_PROVIDER_HOSTINGER',
    DnsProviderWix: 'DNS_PROVIDER_WIX',
    DnsProviderAwsRoute53: 'DNS_PROVIDER_AWS_ROUTE53',
    DnsProviderGoogleCloudDns: 'DNS_PROVIDER_GOOGLE_CLOUD_DNS',
    DnsProviderDigitalocean: 'DNS_PROVIDER_DIGITALOCEAN',
    DnsProviderVercel: 'DNS_PROVIDER_VERCEL',
    DnsProviderPorkbun: 'DNS_PROVIDER_PORKBUN',
    DnsProviderNameCom: 'DNS_PROVIDER_NAME_COM',
    DnsProviderHover: 'DNS_PROVIDER_HOVER',
    DnsProviderNetworkSolutions: 'DNS_PROVIDER_NETWORK_SOLUTIONS',
    DnsProviderBluehost: 'DNS_PROVIDER_BLUEHOST',
    DnsProviderNetlify: 'DNS_PROVIDER_NETLIFY',
    DnsProviderAzureDns: 'DNS_PROVIDER_AZURE_DNS',
    DnsProviderDynadot: 'DNS_PROVIDER_DYNADOT',
    DnsProviderNamesilo: 'DNS_PROVIDER_NAMESILO'
} as const;
export type DnsProvider = typeof DnsProvider[keyof typeof DnsProvider];


export function instanceOfDnsProvider(value: any): boolean {
    for (const key in DnsProvider) {
        if (Object.prototype.hasOwnProperty.call(DnsProvider, key)) {
            if (DnsProvider[key as keyof typeof DnsProvider] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DnsProviderFromJSON(json: any): DnsProvider {
    return DnsProviderFromJSONTyped(json, false);
}

export function DnsProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): DnsProvider {
    return json as DnsProvider;
}

export function DnsProviderToJSON(value?: DnsProvider | null): any {
    return value as any;
}

export function DnsProviderToJSONTyped(value: any, ignoreDiscriminator: boolean): DnsProvider {
    return value as DnsProvider;
}

