/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.149.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - DNS_RECORD_TYPE_UNSPECIFIED: Not specified
 *  - DNS_RECORD_TYPE_CNAME: CNAME record
 *  - DNS_RECORD_TYPE_TXT: TXT record
 * @export
 */
export const DnsRecordType = {
    DnsRecordTypeUnspecified: 'DNS_RECORD_TYPE_UNSPECIFIED',
    DnsRecordTypeCname: 'DNS_RECORD_TYPE_CNAME',
    DnsRecordTypeTxt: 'DNS_RECORD_TYPE_TXT'
} as const;
export type DnsRecordType = typeof DnsRecordType[keyof typeof DnsRecordType];


export function instanceOfDnsRecordType(value: any): boolean {
    for (const key in DnsRecordType) {
        if (Object.prototype.hasOwnProperty.call(DnsRecordType, key)) {
            if (DnsRecordType[key as keyof typeof DnsRecordType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DnsRecordTypeFromJSON(json: any): DnsRecordType {
    return DnsRecordTypeFromJSONTyped(json, false);
}

export function DnsRecordTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DnsRecordType {
    return json as DnsRecordType;
}

export function DnsRecordTypeToJSON(value?: DnsRecordType | null): any {
    return value as any;
}

export function DnsRecordTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DnsRecordType {
    return value as DnsRecordType;
}

