/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.79.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DotsType = {
    DotsTypeUnspecified: 'DOTS_TYPE_UNSPECIFIED',
    DotsTypeSquare: 'DOTS_TYPE_SQUARE',
    DotsTypeDots: 'DOTS_TYPE_DOTS',
    DotsTypeBubblyDots: 'DOTS_TYPE_BUBBLY_DOTS',
    DotsTypeCircuitChip: 'DOTS_TYPE_CIRCUIT_CHIP',
    DotsTypeRounded: 'DOTS_TYPE_ROUNDED',
    DotsTypeExtraRounded: 'DOTS_TYPE_EXTRA_ROUNDED',
    DotsTypeClassy: 'DOTS_TYPE_CLASSY',
    DotsTypeClassyRounded: 'DOTS_TYPE_CLASSY_ROUNDED',
    DotsTypeHexagon: 'DOTS_TYPE_HEXAGON',
    DotsTypeOctagon: 'DOTS_TYPE_OCTAGON'
} as const;
export type DotsType = typeof DotsType[keyof typeof DotsType];


export function instanceOfDotsType(value: any): boolean {
    for (const key in DotsType) {
        if (Object.prototype.hasOwnProperty.call(DotsType, key)) {
            if (DotsType[key as keyof typeof DotsType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DotsTypeFromJSON(json: any): DotsType {
    return DotsTypeFromJSONTyped(json, false);
}

export function DotsTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DotsType {
    return json as DotsType;
}

export function DotsTypeToJSON(value?: DotsType | null): any {
    return value as any;
}

export function DotsTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DotsType {
    return value as DotsType;
}

