/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.43.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThemeColor } from './ThemeColor';
import {
    ThemeColorFromJSON,
    ThemeColorFromJSONTyped,
    ThemeColorToJSON,
    ThemeColorToJSONTyped,
} from './ThemeColor';

/**
 * 
 * @export
 * @interface DotsOptions
 */
export interface DotsOptions {
    /**
     * 
     * @type {ThemeColor}
     * @memberof DotsOptions
     */
    themeColor?: ThemeColor;
    /**
     * 
     * @type {string}
     * @memberof DotsOptions
     */
    type?: string;
}

/**
 * Check if a given object implements the DotsOptions interface.
 */
export function instanceOfDotsOptions(value: object): value is DotsOptions {
    return true;
}

export function DotsOptionsFromJSON(json: any): DotsOptions {
    return DotsOptionsFromJSONTyped(json, false);
}

export function DotsOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DotsOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'themeColor': json['themeColor'] == null ? undefined : ThemeColorFromJSON(json['themeColor']),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function DotsOptionsToJSON(json: any): DotsOptions {
    return DotsOptionsToJSONTyped(json, false);
}

export function DotsOptionsToJSONTyped(value?: DotsOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'themeColor': ThemeColorToJSON(value['themeColor']),
        'type': value['type'],
    };
}

