/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * EntryAccessTraceData stores details for entry access traces.
 * @export
 * @interface EntryAccessTraceData
 */
export interface EntryAccessTraceData {
    /**
     * 
     * @type {string}
     * @memberof EntryAccessTraceData
     */
    accessedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof EntryAccessTraceData
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof EntryAccessTraceData
     */
    entrypoint?: string;
    /**
     * 
     * @type {string}
     * @memberof EntryAccessTraceData
     */
    httpMethod?: string;
    /**
     * 
     * @type {string}
     * @memberof EntryAccessTraceData
     */
    visitType?: string;
}

/**
 * Check if a given object implements the EntryAccessTraceData interface.
 */
export function instanceOfEntryAccessTraceData(value: object): value is EntryAccessTraceData {
    return true;
}

export function EntryAccessTraceDataFromJSON(json: any): EntryAccessTraceData {
    return EntryAccessTraceDataFromJSONTyped(json, false);
}

export function EntryAccessTraceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryAccessTraceData {
    if (json == null) {
        return json;
    }
    return {
        
        'accessedAt': json['accessedAt'] == null ? undefined : json['accessedAt'],
        'action': json['action'] == null ? undefined : json['action'],
        'entrypoint': json['entrypoint'] == null ? undefined : json['entrypoint'],
        'httpMethod': json['httpMethod'] == null ? undefined : json['httpMethod'],
        'visitType': json['visitType'] == null ? undefined : json['visitType'],
    };
}

export function EntryAccessTraceDataToJSON(json: any): EntryAccessTraceData {
    return EntryAccessTraceDataToJSONTyped(json, false);
}

export function EntryAccessTraceDataToJSONTyped(value?: EntryAccessTraceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessedAt': value['accessedAt'],
        'action': value['action'],
        'entrypoint': value['entrypoint'],
        'httpMethod': value['httpMethod'],
        'visitType': value['visitType'],
    };
}

