/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * EntryAccessTraceData stores details for entry access traces.
 * @export
 * @interface EntryAccessTraceData
 */
export interface EntryAccessTraceData {
    /**
     * 
     * @type {string}
     * @memberof EntryAccessTraceData
     */
    accessedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof EntryAccessTraceData
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof EntryAccessTraceData
     */
    entrypoint?: string;
    /**
     * 
     * @type {string}
     * @memberof EntryAccessTraceData
     */
    httpMethod?: string;
    /**
     * 
     * @type {string}
     * @memberof EntryAccessTraceData
     */
    visitType?: string;
}

/**
 * Check if a given object implements the EntryAccessTraceData interface.
 */
export function instanceOfEntryAccessTraceData(value: object): value is EntryAccessTraceData {
    return true;
}

export function EntryAccessTraceDataFromJSON(json: any): EntryAccessTraceData {
    return EntryAccessTraceDataFromJSONTyped(json, false);
}

export function EntryAccessTraceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntryAccessTraceData {
    if (json == null) {
        return json;
    }
    return {
        
        'accessedAt': json['accessedAt'] == null ? undefined : json['accessedAt'],
        'action': json['action'] == null ? undefined : json['action'],
        'entrypoint': json['entrypoint'] == null ? undefined : json['entrypoint'],
        'httpMethod': json['httpMethod'] == null ? undefined : json['httpMethod'],
        'visitType': json['visitType'] == null ? undefined : json['visitType'],
    };
}

export function EntryAccessTraceDataToJSON(json: any): EntryAccessTraceData {
    return EntryAccessTraceDataToJSONTyped(json, false);
}

export function EntryAccessTraceDataToJSONTyped(value?: EntryAccessTraceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessedAt': value['accessedAt'],
        'action': value['action'],
        'entrypoint': value['entrypoint'],
        'httpMethod': value['httpMethod'],
        'visitType': value['visitType'],
    };
}

