/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventTraceData } from './EventTraceData';
import {
    EventTraceDataFromJSON,
    EventTraceDataFromJSONTyped,
    EventTraceDataToJSON,
    EventTraceDataToJSONTyped,
} from './EventTraceData';

/**
 * Records workflow step completion for engagement tracking, capturing form submissions, page views,
 * and user interactions to measure engagement quality.
 * @export
 * @interface EventTrace
 */
export interface EventTrace {
    /**
     * 
     * @type {Date}
     * @memberof EventTrace
     */
    completedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EventTrace
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof EventTrace
     */
    eventId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventTrace
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EventTrace
     */
    linkId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventTrace
     */
    stepAction?: string;
    /**
     * 
     * @type {EventTraceData}
     * @memberof EventTrace
     */
    stepData?: EventTraceData;
    /**
     * 
     * @type {string}
     * @memberof EventTrace
     */
    stepKind?: string;
    /**
     * 
     * @type {Date}
     * @memberof EventTrace
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof EventTrace
     */
    visitorId?: string;
    /**
     * 
     * @type {string}
     * @memberof EventTrace
     */
    workspaceId?: string;
}

/**
 * Check if a given object implements the EventTrace interface.
 */
export function instanceOfEventTrace(value: object): value is EventTrace {
    return true;
}

export function EventTraceFromJSON(json: any): EventTrace {
    return EventTraceFromJSONTyped(json, false);
}

export function EventTraceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventTrace {
    if (json == null) {
        return json;
    }
    return {
        
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'eventId': json['eventId'] == null ? undefined : json['eventId'],
        'id': json['id'] == null ? undefined : json['id'],
        'linkId': json['linkId'] == null ? undefined : json['linkId'],
        'stepAction': json['stepAction'] == null ? undefined : json['stepAction'],
        'stepData': json['stepData'] == null ? undefined : EventTraceDataFromJSON(json['stepData']),
        'stepKind': json['stepKind'] == null ? undefined : json['stepKind'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'visitorId': json['visitorId'] == null ? undefined : json['visitorId'],
        'workspaceId': json['workspaceId'] == null ? undefined : json['workspaceId'],
    };
}

export function EventTraceToJSON(json: any): EventTrace {
    return EventTraceToJSONTyped(json, false);
}

export function EventTraceToJSONTyped(value?: EventTrace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'eventId': value['eventId'],
        'id': value['id'],
        'linkId': value['linkId'],
        'stepAction': value['stepAction'],
        'stepData': EventTraceDataToJSON(value['stepData']),
        'stepKind': value['stepKind'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'visitorId': value['visitorId'],
        'workspaceId': value['workspaceId'],
    };
}

