/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThemeColor } from './ThemeColor';
import {
    ThemeColorFromJSON,
    ThemeColorFromJSONTyped,
    ThemeColorToJSON,
    ThemeColorToJSONTyped,
} from './ThemeColor';

/**
 * 
 * @export
 * @interface FontConfig
 */
export interface FontConfig {
    /**
     * 
     * @type {boolean}
     * @memberof FontConfig
     */
    bold?: boolean;
    /**
     * 
     * @type {ThemeColor}
     * @memberof FontConfig
     */
    color?: ThemeColor;
    /**
     *  - PAGE_THEME_FONT_FAMILY_UNSPECIFIED: Maps to the default system sans-serif stack.
     * @type {FontConfigFamilyEnum}
     * @memberof FontConfig
     */
    family?: FontConfigFamilyEnum;
    /**
     * 
     * @type {number}
     * @memberof FontConfig
     */
    fontSize?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FontConfig
     */
    italic?: boolean;
}


/**
 * @export
 */
export const FontConfigFamilyEnum = {
    PageThemeFontFamilyUnspecified: 'PAGE_THEME_FONT_FAMILY_UNSPECIFIED',
    PageThemeFontFamilyDefault: 'PAGE_THEME_FONT_FAMILY_DEFAULT',
    PageThemeFontFamilyArial: 'PAGE_THEME_FONT_FAMILY_ARIAL',
    PageThemeFontFamilyHelvetica: 'PAGE_THEME_FONT_FAMILY_HELVETICA',
    PageThemeFontFamilyVerdana: 'PAGE_THEME_FONT_FAMILY_VERDANA',
    PageThemeFontFamilyGeorgia: 'PAGE_THEME_FONT_FAMILY_GEORGIA',
    PageThemeFontFamilyTimesNewRoman: 'PAGE_THEME_FONT_FAMILY_TIMES_NEW_ROMAN',
    PageThemeFontFamilyCourierNew: 'PAGE_THEME_FONT_FAMILY_COURIER_NEW'
} as const;
export type FontConfigFamilyEnum = typeof FontConfigFamilyEnum[keyof typeof FontConfigFamilyEnum];


/**
 * Check if a given object implements the FontConfig interface.
 */
export function instanceOfFontConfig(value: object): value is FontConfig {
    return true;
}

export function FontConfigFromJSON(json: any): FontConfig {
    return FontConfigFromJSONTyped(json, false);
}

export function FontConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): FontConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'bold': json['bold'] == null ? undefined : json['bold'],
        'color': json['color'] == null ? undefined : ThemeColorFromJSON(json['color']),
        'family': json['family'] == null ? undefined : json['family'],
        'fontSize': json['fontSize'] == null ? undefined : json['fontSize'],
        'italic': json['italic'] == null ? undefined : json['italic'],
    };
}

export function FontConfigToJSON(json: any): FontConfig {
    return FontConfigToJSONTyped(json, false);
}

export function FontConfigToJSONTyped(value?: FontConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bold': value['bold'],
        'color': ThemeColorToJSON(value['color']),
        'family': value['family'],
        'fontSize': value['fontSize'],
        'italic': value['italic'],
    };
}

