/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - FORM_FIELD_TYPE_UNSPECIFIED: Form field type not specified
 * @export
 */
export const FormFieldType = {
    FormFieldTypeUnspecified: 'FORM_FIELD_TYPE_UNSPECIFIED',
    FormFieldTypeText: 'FORM_FIELD_TYPE_TEXT',
    FormFieldTypeEmail: 'FORM_FIELD_TYPE_EMAIL',
    FormFieldTypePhone: 'FORM_FIELD_TYPE_PHONE',
    FormFieldTypeTextarea: 'FORM_FIELD_TYPE_TEXTAREA',
    FormFieldTypeRadio: 'FORM_FIELD_TYPE_RADIO',
    FormFieldTypeCheckbox: 'FORM_FIELD_TYPE_CHECKBOX',
    FormFieldTypeDropdown: 'FORM_FIELD_TYPE_DROPDOWN',
    FormFieldTypeNumber: 'FORM_FIELD_TYPE_NUMBER',
    FormFieldTypeDate: 'FORM_FIELD_TYPE_DATE',
    FormFieldTypeRating: 'FORM_FIELD_TYPE_RATING'
} as const;
export type FormFieldType = typeof FormFieldType[keyof typeof FormFieldType];


export function instanceOfFormFieldType(value: any): boolean {
    for (const key in FormFieldType) {
        if (Object.prototype.hasOwnProperty.call(FormFieldType, key)) {
            if (FormFieldType[key as keyof typeof FormFieldType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FormFieldTypeFromJSON(json: any): FormFieldType {
    return FormFieldTypeFromJSONTyped(json, false);
}

export function FormFieldTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormFieldType {
    return json as FormFieldType;
}

export function FormFieldTypeToJSON(value?: FormFieldType | null): any {
    return value as any;
}

export function FormFieldTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): FormFieldType {
    return value as FormFieldType;
}

