/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FormTraceDataField } from './FormTraceDataField';
import {
    FormTraceDataFieldFromJSON,
    FormTraceDataFieldFromJSONTyped,
    FormTraceDataFieldToJSON,
    FormTraceDataFieldToJSONTyped,
} from './FormTraceDataField';

/**
 * FormTraceData stores summary data about a form interaction.
 * @export
 * @interface FormTraceData
 */
export interface FormTraceData {
    /**
     * 
     * @type {string}
     * @memberof FormTraceData
     */
    action?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FormTraceData
     */
    autoSkipIfKnown?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FormTraceData
     */
    description?: string;
    /**
     * 
     * @type {Array<FormTraceDataField>}
     * @memberof FormTraceData
     */
    fields?: Array<FormTraceDataField>;
    /**
     * 
     * @type {string}
     * @memberof FormTraceData
     */
    skipButtonText?: string;
    /**
     * 
     * @type {string}
     * @memberof FormTraceData
     */
    skipMethod?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FormTraceData
     */
    skipped?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FormTraceData
     */
    submitButtonText?: string;
    /**
     * 
     * @type {number}
     * @memberof FormTraceData
     */
    submittedFields?: number;
    /**
     * 
     * @type {string}
     * @memberof FormTraceData
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof FormTraceData
     */
    totalFields?: number;
}

/**
 * Check if a given object implements the FormTraceData interface.
 */
export function instanceOfFormTraceData(value: object): value is FormTraceData {
    return true;
}

export function FormTraceDataFromJSON(json: any): FormTraceData {
    return FormTraceDataFromJSONTyped(json, false);
}

export function FormTraceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormTraceData {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'autoSkipIfKnown': json['autoSkipIfKnown'] == null ? undefined : json['autoSkipIfKnown'],
        'description': json['description'] == null ? undefined : json['description'],
        'fields': json['fields'] == null ? undefined : ((json['fields'] as Array<any>).map(FormTraceDataFieldFromJSON)),
        'skipButtonText': json['skipButtonText'] == null ? undefined : json['skipButtonText'],
        'skipMethod': json['skipMethod'] == null ? undefined : json['skipMethod'],
        'skipped': json['skipped'] == null ? undefined : json['skipped'],
        'submitButtonText': json['submitButtonText'] == null ? undefined : json['submitButtonText'],
        'submittedFields': json['submittedFields'] == null ? undefined : json['submittedFields'],
        'title': json['title'] == null ? undefined : json['title'],
        'totalFields': json['totalFields'] == null ? undefined : json['totalFields'],
    };
}

export function FormTraceDataToJSON(json: any): FormTraceData {
    return FormTraceDataToJSONTyped(json, false);
}

export function FormTraceDataToJSONTyped(value?: FormTraceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'autoSkipIfKnown': value['autoSkipIfKnown'],
        'description': value['description'],
        'fields': value['fields'] == null ? undefined : ((value['fields'] as Array<any>).map(FormTraceDataFieldToJSON)),
        'skipButtonText': value['skipButtonText'],
        'skipMethod': value['skipMethod'],
        'skipped': value['skipped'],
        'submitButtonText': value['submitButtonText'],
        'submittedFields': value['submittedFields'],
        'title': value['title'],
        'totalFields': value['totalFields'],
    };
}

