/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.111.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsWidgetResult } from './AnalyticsWidgetResult';
import {
    AnalyticsWidgetResultFromJSON,
    AnalyticsWidgetResultFromJSONTyped,
    AnalyticsWidgetResultToJSON,
    AnalyticsWidgetResultToJSONTyped,
} from './AnalyticsWidgetResult';

/**
 * 
 * @export
 * @interface GenerateWidgetSummaryResponse
 */
export interface GenerateWidgetSummaryResponse {
    /**
     * 
     * @type {AnalyticsWidgetResult}
     * @memberof GenerateWidgetSummaryResponse
     */
    result?: AnalyticsWidgetResult;
}

/**
 * Check if a given object implements the GenerateWidgetSummaryResponse interface.
 */
export function instanceOfGenerateWidgetSummaryResponse(value: object): value is GenerateWidgetSummaryResponse {
    return true;
}

export function GenerateWidgetSummaryResponseFromJSON(json: any): GenerateWidgetSummaryResponse {
    return GenerateWidgetSummaryResponseFromJSONTyped(json, false);
}

export function GenerateWidgetSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateWidgetSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : AnalyticsWidgetResultFromJSON(json['result']),
    };
}

export function GenerateWidgetSummaryResponseToJSON(json: any): GenerateWidgetSummaryResponse {
    return GenerateWidgetSummaryResponseToJSONTyped(json, false);
}

export function GenerateWidgetSummaryResponseToJSONTyped(value?: GenerateWidgetSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': AnalyticsWidgetResultToJSON(value['result']),
    };
}

