/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.149.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomDomainSetupGuide } from './CustomDomainSetupGuide';
import {
    CustomDomainSetupGuideFromJSON,
    CustomDomainSetupGuideFromJSONTyped,
    CustomDomainSetupGuideToJSON,
    CustomDomainSetupGuideToJSONTyped,
} from './CustomDomainSetupGuide';

/**
 * 
 * @export
 * @interface GetCustomDomainSetupGuideResponse
 */
export interface GetCustomDomainSetupGuideResponse {
    /**
     * 
     * @type {CustomDomainSetupGuide}
     * @memberof GetCustomDomainSetupGuideResponse
     */
    setupGuide?: CustomDomainSetupGuide;
}

/**
 * Check if a given object implements the GetCustomDomainSetupGuideResponse interface.
 */
export function instanceOfGetCustomDomainSetupGuideResponse(value: object): value is GetCustomDomainSetupGuideResponse {
    return true;
}

export function GetCustomDomainSetupGuideResponseFromJSON(json: any): GetCustomDomainSetupGuideResponse {
    return GetCustomDomainSetupGuideResponseFromJSONTyped(json, false);
}

export function GetCustomDomainSetupGuideResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCustomDomainSetupGuideResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'setupGuide': json['setupGuide'] == null ? undefined : CustomDomainSetupGuideFromJSON(json['setupGuide']),
    };
}

export function GetCustomDomainSetupGuideResponseToJSON(json: any): GetCustomDomainSetupGuideResponse {
    return GetCustomDomainSetupGuideResponseToJSONTyped(json, false);
}

export function GetCustomDomainSetupGuideResponseToJSONTyped(value?: GetCustomDomainSetupGuideResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'setupGuide': CustomDomainSetupGuideToJSON(value['setupGuide']),
    };
}

