/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.77.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetDeviceDistributionRequest
 */
export interface GetDeviceDistributionRequest {
    /**
     * 
     * @type {Date}
     * @memberof GetDeviceDistributionRequest
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetDeviceDistributionRequest
     */
    linkId?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetDeviceDistributionRequest
     */
    startDate?: Date;
}

/**
 * Check if a given object implements the GetDeviceDistributionRequest interface.
 */
export function instanceOfGetDeviceDistributionRequest(value: object): value is GetDeviceDistributionRequest {
    return true;
}

export function GetDeviceDistributionRequestFromJSON(json: any): GetDeviceDistributionRequest {
    return GetDeviceDistributionRequestFromJSONTyped(json, false);
}

export function GetDeviceDistributionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDeviceDistributionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'linkId': json['linkId'] == null ? undefined : json['linkId'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
    };
}

export function GetDeviceDistributionRequestToJSON(json: any): GetDeviceDistributionRequest {
    return GetDeviceDistributionRequestToJSONTyped(json, false);
}

export function GetDeviceDistributionRequestToJSONTyped(value?: GetDeviceDistributionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'linkId': value['linkId'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
    };
}

