/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventsTimeSeries } from './EventsTimeSeries';
import {
    EventsTimeSeriesFromJSON,
    EventsTimeSeriesFromJSONTyped,
    EventsTimeSeriesToJSON,
    EventsTimeSeriesToJSONTyped,
} from './EventsTimeSeries';

/**
 * 
 * @export
 * @interface GetEventsTimeSeriesResponse
 */
export interface GetEventsTimeSeriesResponse {
    /**
     * 
     * @type {EventsTimeSeries}
     * @memberof GetEventsTimeSeriesResponse
     */
    timeSeries?: EventsTimeSeries;
}

/**
 * Check if a given object implements the GetEventsTimeSeriesResponse interface.
 */
export function instanceOfGetEventsTimeSeriesResponse(value: object): value is GetEventsTimeSeriesResponse {
    return true;
}

export function GetEventsTimeSeriesResponseFromJSON(json: any): GetEventsTimeSeriesResponse {
    return GetEventsTimeSeriesResponseFromJSONTyped(json, false);
}

export function GetEventsTimeSeriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEventsTimeSeriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timeSeries': json['timeSeries'] == null ? undefined : EventsTimeSeriesFromJSON(json['timeSeries']),
    };
}

export function GetEventsTimeSeriesResponseToJSON(json: any): GetEventsTimeSeriesResponse {
    return GetEventsTimeSeriesResponseToJSONTyped(json, false);
}

export function GetEventsTimeSeriesResponseToJSONTyped(value?: GetEventsTimeSeriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeSeries': EventsTimeSeriesToJSON(value['timeSeries']),
    };
}

