/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEventsTimeSeriesRequest
 */
export interface GetEventsTimeSeriesRequest {
    /**
     * 
     * @type {Date}
     * @memberof GetEventsTimeSeriesRequest
     */
    endDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof GetEventsTimeSeriesRequest
     */
    intervalInMinutes?: number;
    /**
     * Optional filtering by link ID
     * @type {string}
     * @memberof GetEventsTimeSeriesRequest
     */
    linkId?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetEventsTimeSeriesRequest
     */
    startDate?: Date;
}

/**
 * Check if a given object implements the GetEventsTimeSeriesRequest interface.
 */
export function instanceOfGetEventsTimeSeriesRequest(value: object): value is GetEventsTimeSeriesRequest {
    return true;
}

export function GetEventsTimeSeriesRequestFromJSON(json: any): GetEventsTimeSeriesRequest {
    return GetEventsTimeSeriesRequestFromJSONTyped(json, false);
}

export function GetEventsTimeSeriesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEventsTimeSeriesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'intervalInMinutes': json['intervalInMinutes'] == null ? undefined : json['intervalInMinutes'],
        'linkId': json['linkId'] == null ? undefined : json['linkId'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
    };
}

export function GetEventsTimeSeriesRequestToJSON(json: any): GetEventsTimeSeriesRequest {
    return GetEventsTimeSeriesRequestToJSONTyped(json, false);
}

export function GetEventsTimeSeriesRequestToJSONTyped(value?: GetEventsTimeSeriesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'intervalInMinutes': value['intervalInMinutes'],
        'linkId': value['linkId'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
    };
}

