/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoDataPoint } from './GeoDataPoint';
import {
    GeoDataPointFromJSON,
    GeoDataPointFromJSONTyped,
    GeoDataPointToJSON,
    GeoDataPointToJSONTyped,
} from './GeoDataPoint';

/**
 * 
 * @export
 * @interface GetGeoBreakdownResponse
 */
export interface GetGeoBreakdownResponse {
    /**
     * 
     * @type {Array<GeoDataPoint>}
     * @memberof GetGeoBreakdownResponse
     */
    data?: Array<GeoDataPoint>;
    /**
     * 
     * @type {number}
     * @memberof GetGeoBreakdownResponse
     */
    totalEvents?: number;
}

/**
 * Check if a given object implements the GetGeoBreakdownResponse interface.
 */
export function instanceOfGetGeoBreakdownResponse(value: object): value is GetGeoBreakdownResponse {
    return true;
}

export function GetGeoBreakdownResponseFromJSON(json: any): GetGeoBreakdownResponse {
    return GetGeoBreakdownResponseFromJSONTyped(json, false);
}

export function GetGeoBreakdownResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGeoBreakdownResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GeoDataPointFromJSON)),
        'totalEvents': json['totalEvents'] == null ? undefined : json['totalEvents'],
    };
}

export function GetGeoBreakdownResponseToJSON(json: any): GetGeoBreakdownResponse {
    return GetGeoBreakdownResponseToJSONTyped(json, false);
}

export function GetGeoBreakdownResponseToJSONTyped(value?: GetGeoBreakdownResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GeoDataPointToJSON)),
        'totalEvents': value['totalEvents'],
    };
}

