/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeoDataPoint } from './GeoDataPoint';
import {
    GeoDataPointFromJSON,
    GeoDataPointFromJSONTyped,
    GeoDataPointToJSON,
    GeoDataPointToJSONTyped,
} from './GeoDataPoint';

/**
 * 
 * @export
 * @interface GetGeoBreakdownResponse
 */
export interface GetGeoBreakdownResponse {
    /**
     * 
     * @type {Array<GeoDataPoint>}
     * @memberof GetGeoBreakdownResponse
     */
    data?: Array<GeoDataPoint>;
    /**
     * 
     * @type {number}
     * @memberof GetGeoBreakdownResponse
     */
    totalEvents?: number;
}

/**
 * Check if a given object implements the GetGeoBreakdownResponse interface.
 */
export function instanceOfGetGeoBreakdownResponse(value: object): value is GetGeoBreakdownResponse {
    return true;
}

export function GetGeoBreakdownResponseFromJSON(json: any): GetGeoBreakdownResponse {
    return GetGeoBreakdownResponseFromJSONTyped(json, false);
}

export function GetGeoBreakdownResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGeoBreakdownResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GeoDataPointFromJSON)),
        'totalEvents': json['totalEvents'] == null ? undefined : json['totalEvents'],
    };
}

export function GetGeoBreakdownResponseToJSON(json: any): GetGeoBreakdownResponse {
    return GetGeoBreakdownResponseToJSONTyped(json, false);
}

export function GetGeoBreakdownResponseToJSONTyped(value?: GetGeoBreakdownResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GeoDataPointToJSON)),
        'totalEvents': value['totalEvents'],
    };
}

