/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHourOfDayDistributionRequest
 */
export interface GetHourOfDayDistributionRequest {
    /**
     * 
     * @type {Date}
     * @memberof GetHourOfDayDistributionRequest
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetHourOfDayDistributionRequest
     */
    linkId?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetHourOfDayDistributionRequest
     */
    startDate?: Date;
}

/**
 * Check if a given object implements the GetHourOfDayDistributionRequest interface.
 */
export function instanceOfGetHourOfDayDistributionRequest(value: object): value is GetHourOfDayDistributionRequest {
    return true;
}

export function GetHourOfDayDistributionRequestFromJSON(json: any): GetHourOfDayDistributionRequest {
    return GetHourOfDayDistributionRequestFromJSONTyped(json, false);
}

export function GetHourOfDayDistributionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHourOfDayDistributionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'linkId': json['linkId'] == null ? undefined : json['linkId'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
    };
}

export function GetHourOfDayDistributionRequestToJSON(json: any): GetHourOfDayDistributionRequest {
    return GetHourOfDayDistributionRequestToJSONTyped(json, false);
}

export function GetHourOfDayDistributionRequestToJSONTyped(value?: GetHourOfDayDistributionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'linkId': value['linkId'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
    };
}

