/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GoogleFormsIntegrationStatus = {
    GoogleFormsIntegrationStatusUnspecified: 'GOOGLE_FORMS_INTEGRATION_STATUS_UNSPECIFIED',
    GoogleFormsIntegrationStatusActive: 'GOOGLE_FORMS_INTEGRATION_STATUS_ACTIVE',
    GoogleFormsIntegrationStatusPaused: 'GOOGLE_FORMS_INTEGRATION_STATUS_PAUSED',
    GoogleFormsIntegrationStatusDisconnected: 'GOOGLE_FORMS_INTEGRATION_STATUS_DISCONNECTED'
} as const;
export type GoogleFormsIntegrationStatus = typeof GoogleFormsIntegrationStatus[keyof typeof GoogleFormsIntegrationStatus];


export function instanceOfGoogleFormsIntegrationStatus(value: any): boolean {
    for (const key in GoogleFormsIntegrationStatus) {
        if (Object.prototype.hasOwnProperty.call(GoogleFormsIntegrationStatus, key)) {
            if (GoogleFormsIntegrationStatus[key as keyof typeof GoogleFormsIntegrationStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GoogleFormsIntegrationStatusFromJSON(json: any): GoogleFormsIntegrationStatus {
    return GoogleFormsIntegrationStatusFromJSONTyped(json, false);
}

export function GoogleFormsIntegrationStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GoogleFormsIntegrationStatus {
    return json as GoogleFormsIntegrationStatus;
}

export function GoogleFormsIntegrationStatusToJSON(value?: GoogleFormsIntegrationStatus | null): any {
    return value as any;
}

export function GoogleFormsIntegrationStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): GoogleFormsIntegrationStatus {
    return value as GoogleFormsIntegrationStatus;
}

