/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.79.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HourOfDayDataPoint
 */
export interface HourOfDayDataPoint {
    /**
     * 
     * @type {number}
     * @memberof HourOfDayDataPoint
     */
    eventCount?: number;
    /**
     * 
     * @type {number}
     * @memberof HourOfDayDataPoint
     */
    hour?: number;
}

/**
 * Check if a given object implements the HourOfDayDataPoint interface.
 */
export function instanceOfHourOfDayDataPoint(value: object): value is HourOfDayDataPoint {
    return true;
}

export function HourOfDayDataPointFromJSON(json: any): HourOfDayDataPoint {
    return HourOfDayDataPointFromJSONTyped(json, false);
}

export function HourOfDayDataPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): HourOfDayDataPoint {
    if (json == null) {
        return json;
    }
    return {
        
        'eventCount': json['eventCount'] == null ? undefined : json['eventCount'],
        'hour': json['hour'] == null ? undefined : json['hour'],
    };
}

export function HourOfDayDataPointToJSON(json: any): HourOfDayDataPoint {
    return HourOfDayDataPointToJSONTyped(json, false);
}

export function HourOfDayDataPointToJSONTyped(value?: HourOfDayDataPoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventCount': value['eventCount'],
        'hour': value['hour'],
    };
}

