/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportQrcodeTemplateRequest
 */
export interface ImportQrcodeTemplateRequest {
    /**
     * The slug of the public QR code template to import into your workspace
     * @type {string}
     * @memberof ImportQrcodeTemplateRequest
     */
    slug?: string;
}

/**
 * Check if a given object implements the ImportQrcodeTemplateRequest interface.
 */
export function instanceOfImportQrcodeTemplateRequest(value: object): value is ImportQrcodeTemplateRequest {
    return true;
}

export function ImportQrcodeTemplateRequestFromJSON(json: any): ImportQrcodeTemplateRequest {
    return ImportQrcodeTemplateRequestFromJSONTyped(json, false);
}

export function ImportQrcodeTemplateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportQrcodeTemplateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function ImportQrcodeTemplateRequestToJSON(json: any): ImportQrcodeTemplateRequest {
    return ImportQrcodeTemplateRequestToJSONTyped(json, false);
}

export function ImportQrcodeTemplateRequestToJSONTyped(value?: ImportQrcodeTemplateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
    };
}

