/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - LINK_VIEW_UNSPECIFIED: Return all links regardless of directory (default)
 *  - LINK_VIEW_DIRECTORY: Return links scoped to a directory.
 * When directory_id is set, returns links in that directory.
 * When directory_id is empty, returns root-level links (no directory).
 * @export
 */
export const LinkView = {
    LinkViewUnspecified: 'LINK_VIEW_UNSPECIFIED',
    LinkViewDirectory: 'LINK_VIEW_DIRECTORY'
} as const;
export type LinkView = typeof LinkView[keyof typeof LinkView];


export function instanceOfLinkView(value: any): boolean {
    for (const key in LinkView) {
        if (Object.prototype.hasOwnProperty.call(LinkView, key)) {
            if (LinkView[key as keyof typeof LinkView] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LinkViewFromJSON(json: any): LinkView {
    return LinkViewFromJSONTyped(json, false);
}

export function LinkViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkView {
    return json as LinkView;
}

export function LinkViewToJSON(value?: LinkView | null): any {
    return value as any;
}

export function LinkViewToJSONTyped(value: any, ignoreDiscriminator: boolean): LinkView {
    return value as LinkView;
}

