/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataCollection } from './DataCollection';
import {
    DataCollectionFromJSON,
    DataCollectionFromJSONTyped,
    DataCollectionToJSON,
    DataCollectionToJSONTyped,
} from './DataCollection';

/**
 * Stores per-link compliance preferences that drive how Linkbreakers collects visitor data before executing the workflow.
 * @export
 * @interface LinkSetting
 */
export interface LinkSetting {
    /**
     * 
     * @type {Date}
     * @memberof LinkSetting
     */
    createdAt?: Date;
    /**
     * 
     * @type {DataCollection}
     * @memberof LinkSetting
     */
    dataCollection?: DataCollection;
    /**
     * 
     * @type {string}
     * @memberof LinkSetting
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof LinkSetting
     */
    updatedAt?: Date;
}



/**
 * Check if a given object implements the LinkSetting interface.
 */
export function instanceOfLinkSetting(value: object): value is LinkSetting {
    return true;
}

export function LinkSettingFromJSON(json: any): LinkSetting {
    return LinkSettingFromJSONTyped(json, false);
}

export function LinkSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkSetting {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'dataCollection': json['dataCollection'] == null ? undefined : DataCollectionFromJSON(json['dataCollection']),
        'id': json['id'] == null ? undefined : json['id'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function LinkSettingToJSON(json: any): LinkSetting {
    return LinkSettingToJSONTyped(json, false);
}

export function LinkSettingToJSONTyped(value?: LinkSetting | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'dataCollection': DataCollectionToJSON(value['dataCollection']),
        'id': value['id'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

