/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinksServiceUpdateBody
 */
export interface LinksServiceUpdateBody {
    /**
     * 
     * @type {string}
     * @memberof LinksServiceUpdateBody
     */
    directoryId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LinksServiceUpdateBody
     */
    directoryIdDelete?: boolean;
    /**
     * Where visitors are sent once the link has expired.
     * Empty serves the built-in expired page instead.
     * @type {string}
     * @memberof LinksServiceUpdateBody
     */
    expiredDestination?: string;
    /**
     * Remove the expired destination from this link.
     * If true, expired_destination is cleared and expired visitors see the
     * built-in expired page instead.
     * @type {boolean}
     * @memberof LinksServiceUpdateBody
     */
    expiredDestinationDelete?: boolean;
    /**
     * When the link stops resolving. Empty leaves the current value untouched.
     * Must be in the future. Once it passes the link is removed from the
     * workspace and only the expired destination is served.
     * @type {Date}
     * @memberof LinksServiceUpdateBody
     */
    expiresAt?: Date;
    /**
     * Remove the expiration from this link.
     * If true, expires_at is cleared and the link stops expiring.
     * @type {boolean}
     * @memberof LinksServiceUpdateBody
     */
    expiresAtDelete?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LinksServiceUpdateBody
     */
    fallbackDestination?: string;
    /**
     * 
     * @type {string}
     * @memberof LinksServiceUpdateBody
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LinksServiceUpdateBody
     */
    pageThemeId?: string;
    /**
     * What the user is trying to achieve with this link, in one or two sentences.
     * The link's assistant conversations read it as context, so it is restated
     * whenever the workflow changes shape.
     * @type {string}
     * @memberof LinksServiceUpdateBody
     */
    purpose?: string;
    /**
     * 
     * @type {string}
     * @memberof LinksServiceUpdateBody
     */
    qrcodeTemplateId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LinksServiceUpdateBody
     */
    qrcodeTemplateIdDelete?: boolean;
    /**
     * Set the tags to associate with the link.
     * If a tag with the given name doesn't exist, it will be created.
     * @type {Array<string>}
     * @memberof LinksServiceUpdateBody
     */
    tags?: Array<string>;
    /**
     * Delete all tags from the link
     * If true, all tags will be removed from the link.
     * @type {boolean}
     * @memberof LinksServiceUpdateBody
     */
    tagsDelete?: boolean;
}

/**
 * Check if a given object implements the LinksServiceUpdateBody interface.
 */
export function instanceOfLinksServiceUpdateBody(value: object): value is LinksServiceUpdateBody {
    return true;
}

export function LinksServiceUpdateBodyFromJSON(json: any): LinksServiceUpdateBody {
    return LinksServiceUpdateBodyFromJSONTyped(json, false);
}

export function LinksServiceUpdateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinksServiceUpdateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'directoryId': json['directoryId'] == null ? undefined : json['directoryId'],
        'directoryIdDelete': json['directoryIdDelete'] == null ? undefined : json['directoryIdDelete'],
        'expiredDestination': json['expiredDestination'] == null ? undefined : json['expiredDestination'],
        'expiredDestinationDelete': json['expiredDestinationDelete'] == null ? undefined : json['expiredDestinationDelete'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'expiresAtDelete': json['expiresAtDelete'] == null ? undefined : json['expiresAtDelete'],
        'fallbackDestination': json['fallbackDestination'] == null ? undefined : json['fallbackDestination'],
        'name': json['name'] == null ? undefined : json['name'],
        'pageThemeId': json['pageThemeId'] == null ? undefined : json['pageThemeId'],
        'purpose': json['purpose'] == null ? undefined : json['purpose'],
        'qrcodeTemplateId': json['qrcodeTemplateId'] == null ? undefined : json['qrcodeTemplateId'],
        'qrcodeTemplateIdDelete': json['qrcodeTemplateIdDelete'] == null ? undefined : json['qrcodeTemplateIdDelete'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'tagsDelete': json['tagsDelete'] == null ? undefined : json['tagsDelete'],
    };
}

export function LinksServiceUpdateBodyToJSON(json: any): LinksServiceUpdateBody {
    return LinksServiceUpdateBodyToJSONTyped(json, false);
}

export function LinksServiceUpdateBodyToJSONTyped(value?: LinksServiceUpdateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'directoryId': value['directoryId'],
        'directoryIdDelete': value['directoryIdDelete'],
        'expiredDestination': value['expiredDestination'],
        'expiredDestinationDelete': value['expiredDestinationDelete'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'expiresAtDelete': value['expiresAtDelete'],
        'fallbackDestination': value['fallbackDestination'],
        'name': value['name'],
        'pageThemeId': value['pageThemeId'],
        'purpose': value['purpose'],
        'qrcodeTemplateId': value['qrcodeTemplateId'],
        'qrcodeTemplateIdDelete': value['qrcodeTemplateIdDelete'],
        'tags': value['tags'],
        'tagsDelete': value['tagsDelete'],
    };
}

