/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowStep } from './WorkflowStep';
import {
    WorkflowStepFromJSON,
    WorkflowStepFromJSONTyped,
    WorkflowStepToJSON,
    WorkflowStepToJSONTyped,
} from './WorkflowStep';

/**
 * 
 * @export
 * @interface ListWorkflowStepsResponse
 */
export interface ListWorkflowStepsResponse {
    /**
     * Cursor to fetch the next page of workflow steps
     * @type {string}
     * @memberof ListWorkflowStepsResponse
     */
    nextPageToken?: string;
    /**
     * How many steps this link has in total, so a client can tell a complete
     * answer from a page of one. A local-first client reads absence from this
     * list as the step having been deleted, and may only do so when the count it
     * was given matches what it received. The count covers the link asked about
     * rather than the workspace, which is the only sense in which this list is
     * ever whole.
     * @type {string}
     * @memberof ListWorkflowStepsResponse
     */
    totalCount?: string;
    /**
     * 
     * @type {Array<WorkflowStep>}
     * @memberof ListWorkflowStepsResponse
     */
    workflowSteps?: Array<WorkflowStep>;
}

/**
 * Check if a given object implements the ListWorkflowStepsResponse interface.
 */
export function instanceOfListWorkflowStepsResponse(value: object): value is ListWorkflowStepsResponse {
    return true;
}

export function ListWorkflowStepsResponseFromJSON(json: any): ListWorkflowStepsResponse {
    return ListWorkflowStepsResponseFromJSONTyped(json, false);
}

export function ListWorkflowStepsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWorkflowStepsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nextPageToken': json['nextPageToken'] == null ? undefined : json['nextPageToken'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'workflowSteps': json['workflowSteps'] == null ? undefined : ((json['workflowSteps'] as Array<any>).map(WorkflowStepFromJSON)),
    };
}

export function ListWorkflowStepsResponseToJSON(json: any): ListWorkflowStepsResponse {
    return ListWorkflowStepsResponseToJSONTyped(json, false);
}

export function ListWorkflowStepsResponseToJSONTyped(value?: ListWorkflowStepsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nextPageToken': value['nextPageToken'],
        'totalCount': value['totalCount'],
        'workflowSteps': value['workflowSteps'] == null ? undefined : ((value['workflowSteps'] as Array<any>).map(WorkflowStepToJSON)),
    };
}

