/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.134.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceToken } from './WorkspaceToken';
import {
    WorkspaceTokenFromJSON,
    WorkspaceTokenFromJSONTyped,
    WorkspaceTokenToJSON,
    WorkspaceTokenToJSONTyped,
} from './WorkspaceToken';

/**
 * ListWorkspaceTokensResponse returns the active token inventory for audit screens.
 * @export
 * @interface ListWorkspaceTokensResponse
 */
export interface ListWorkspaceTokensResponse {
    /**
     * Cursor to continue listing tokens. Empty on the last page.
     * @type {string}
     * @memberof ListWorkspaceTokensResponse
     */
    nextPageToken?: string;
    /**
     * 
     * @type {Array<WorkspaceToken>}
     * @memberof ListWorkspaceTokensResponse
     */
    tokens?: Array<WorkspaceToken>;
    /**
     * How many records exist in total, so a client can tell a complete answer
     * from a page of one. A local-first client reads absence from this list as
     * deletion, and may only do so when the count it was given matches what it
     * received: without that, one page would look like the whole model and
     * everything beyond it would be removed locally.
     * @type {string}
     * @memberof ListWorkspaceTokensResponse
     */
    totalCount?: string;
}

/**
 * Check if a given object implements the ListWorkspaceTokensResponse interface.
 */
export function instanceOfListWorkspaceTokensResponse(value: object): value is ListWorkspaceTokensResponse {
    return true;
}

export function ListWorkspaceTokensResponseFromJSON(json: any): ListWorkspaceTokensResponse {
    return ListWorkspaceTokensResponseFromJSONTyped(json, false);
}

export function ListWorkspaceTokensResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWorkspaceTokensResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nextPageToken': json['nextPageToken'] == null ? undefined : json['nextPageToken'],
        'tokens': json['tokens'] == null ? undefined : ((json['tokens'] as Array<any>).map(WorkspaceTokenFromJSON)),
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function ListWorkspaceTokensResponseToJSON(json: any): ListWorkspaceTokensResponse {
    return ListWorkspaceTokensResponseToJSONTyped(json, false);
}

export function ListWorkspaceTokensResponseToJSONTyped(value?: ListWorkspaceTokensResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nextPageToken': value['nextPageToken'],
        'tokens': value['tokens'] == null ? undefined : ((value['tokens'] as Array<any>).map(WorkspaceTokenToJSON)),
        'totalCount': value['totalCount'],
    };
}

