/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SlackChannel } from './SlackChannel';
import {
    SlackChannelFromJSON,
    SlackChannelFromJSONTyped,
    SlackChannelToJSON,
    SlackChannelToJSONTyped,
} from './SlackChannel';

/**
 * 
 * @export
 * @interface ListSlackChannelsResponse
 */
export interface ListSlackChannelsResponse {
    /**
     * 
     * @type {Array<SlackChannel>}
     * @memberof ListSlackChannelsResponse
     */
    channels?: Array<SlackChannel>;
}

/**
 * Check if a given object implements the ListSlackChannelsResponse interface.
 */
export function instanceOfListSlackChannelsResponse(value: object): value is ListSlackChannelsResponse {
    return true;
}

export function ListSlackChannelsResponseFromJSON(json: any): ListSlackChannelsResponse {
    return ListSlackChannelsResponseFromJSONTyped(json, false);
}

export function ListSlackChannelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSlackChannelsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'channels': json['channels'] == null ? undefined : ((json['channels'] as Array<any>).map(SlackChannelFromJSON)),
    };
}

export function ListSlackChannelsResponseToJSON(json: any): ListSlackChannelsResponse {
    return ListSlackChannelsResponseToJSONTyped(json, false);
}

export function ListSlackChannelsResponseToJSONTyped(value?: ListSlackChannelsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channels': value['channels'] == null ? undefined : ((value['channels'] as Array<any>).map(SlackChannelToJSON)),
    };
}

