/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomDomain } from './CustomDomain';
import {
    CustomDomainFromJSON,
    CustomDomainFromJSONTyped,
    CustomDomainToJSON,
    CustomDomainToJSONTyped,
} from './CustomDomain';

/**
 * 
 * @export
 * @interface ListCustomDomainsResponse
 */
export interface ListCustomDomainsResponse {
    /**
     * 
     * @type {Array<CustomDomain>}
     * @memberof ListCustomDomainsResponse
     */
    customDomains?: Array<CustomDomain>;
}

/**
 * Check if a given object implements the ListCustomDomainsResponse interface.
 */
export function instanceOfListCustomDomainsResponse(value: object): value is ListCustomDomainsResponse {
    return true;
}

export function ListCustomDomainsResponseFromJSON(json: any): ListCustomDomainsResponse {
    return ListCustomDomainsResponseFromJSONTyped(json, false);
}

export function ListCustomDomainsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCustomDomainsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'customDomains': json['customDomains'] == null ? undefined : ((json['customDomains'] as Array<any>).map(CustomDomainFromJSON)),
    };
}

export function ListCustomDomainsResponseToJSON(json: any): ListCustomDomainsResponse {
    return ListCustomDomainsResponseToJSONTyped(json, false);
}

export function ListCustomDomainsResponseToJSONTyped(value?: ListCustomDomainsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customDomains': value['customDomains'] == null ? undefined : ((value['customDomains'] as Array<any>).map(CustomDomainToJSON)),
    };
}

