/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Directory } from './Directory';
import {
    DirectoryFromJSON,
    DirectoryFromJSONTyped,
    DirectoryToJSON,
    DirectoryToJSONTyped,
} from './Directory';

/**
 * 
 * @export
 * @interface ListDirectoriesResponse
 */
export interface ListDirectoriesResponse {
    /**
     * 
     * @type {Array<Directory>}
     * @memberof ListDirectoriesResponse
     */
    directories?: Array<Directory>;
    /**
     * Cursor to continue listing directories
     * @type {string}
     * @memberof ListDirectoriesResponse
     */
    nextPageToken?: string;
}

/**
 * Check if a given object implements the ListDirectoriesResponse interface.
 */
export function instanceOfListDirectoriesResponse(value: object): value is ListDirectoriesResponse {
    return true;
}

export function ListDirectoriesResponseFromJSON(json: any): ListDirectoriesResponse {
    return ListDirectoriesResponseFromJSONTyped(json, false);
}

export function ListDirectoriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDirectoriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'directories': json['directories'] == null ? undefined : ((json['directories'] as Array<any>).map(DirectoryFromJSON)),
        'nextPageToken': json['nextPageToken'] == null ? undefined : json['nextPageToken'],
    };
}

export function ListDirectoriesResponseToJSON(json: any): ListDirectoriesResponse {
    return ListDirectoriesResponseToJSONTyped(json, false);
}

export function ListDirectoriesResponseToJSONTyped(value?: ListDirectoriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'directories': value['directories'] == null ? undefined : ((value['directories'] as Array<any>).map(DirectoryToJSON)),
        'nextPageToken': value['nextPageToken'],
    };
}

