/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.146.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PricingPlan } from './PricingPlan';
import {
    PricingPlanFromJSON,
    PricingPlanFromJSONTyped,
    PricingPlanToJSON,
    PricingPlanToJSONTyped,
} from './PricingPlan';
import type { CreditTopup } from './CreditTopup';
import {
    CreditTopupFromJSON,
    CreditTopupFromJSONTyped,
    CreditTopupToJSON,
    CreditTopupToJSONTyped,
} from './CreditTopup';

/**
 * 
 * @export
 * @interface ListPricingPlansResponse
 */
export interface ListPricingPlansResponse {
    /**
     * Price of buying more credits. Absent when prices could not be read.
     * @type {CreditTopup}
     * @memberof ListPricingPlansResponse
     */
    creditTopup?: CreditTopup;
    /**
     * 
     * @type {number}
     * @memberof ListPricingPlansResponse
     */
    linkCreatedCreditCost?: number;
    /**
     * 
     * @type {Array<PricingPlan>}
     * @memberof ListPricingPlansResponse
     */
    plans?: Array<PricingPlan>;
    /**
     * When the prices were read from the billing provider. Absent when they never could be.
     * @type {Date}
     * @memberof ListPricingPlansResponse
     */
    pricesUpdatedAt?: Date;
}

/**
 * Check if a given object implements the ListPricingPlansResponse interface.
 */
export function instanceOfListPricingPlansResponse(value: object): value is ListPricingPlansResponse {
    return true;
}

export function ListPricingPlansResponseFromJSON(json: any): ListPricingPlansResponse {
    return ListPricingPlansResponseFromJSONTyped(json, false);
}

export function ListPricingPlansResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPricingPlansResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'creditTopup': json['creditTopup'] == null ? undefined : CreditTopupFromJSON(json['creditTopup']),
        'linkCreatedCreditCost': json['linkCreatedCreditCost'] == null ? undefined : json['linkCreatedCreditCost'],
        'plans': json['plans'] == null ? undefined : ((json['plans'] as Array<any>).map(PricingPlanFromJSON)),
        'pricesUpdatedAt': json['pricesUpdatedAt'] == null ? undefined : (new Date(json['pricesUpdatedAt'])),
    };
}

export function ListPricingPlansResponseToJSON(json: any): ListPricingPlansResponse {
    return ListPricingPlansResponseToJSONTyped(json, false);
}

export function ListPricingPlansResponseToJSONTyped(value?: ListPricingPlansResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creditTopup': CreditTopupToJSON(value['creditTopup']),
        'linkCreatedCreditCost': value['linkCreatedCreditCost'],
        'plans': value['plans'] == null ? undefined : ((value['plans'] as Array<any>).map(PricingPlanToJSON)),
        'pricesUpdatedAt': value['pricesUpdatedAt'] == null ? value['pricesUpdatedAt'] : value['pricesUpdatedAt'].toISOString(),
    };
}

