/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.137.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageTheme } from './PageTheme';
import {
    PageThemeFromJSON,
    PageThemeFromJSONTyped,
    PageThemeToJSON,
    PageThemeToJSONTyped,
} from './PageTheme';

/**
 * 
 * @export
 * @interface ListPageThemesResponse
 */
export interface ListPageThemesResponse {
    /**
     * Cursor to continue listing page themes. Empty on the last page.
     * @type {string}
     * @memberof ListPageThemesResponse
     */
    nextPageToken?: string;
    /**
     * 
     * @type {Array<PageTheme>}
     * @memberof ListPageThemesResponse
     */
    pageThemes?: Array<PageTheme>;
    /**
     * How many records exist in total, so a client can tell a complete answer
     * from a page of one. A local-first client reads absence from this list as
     * deletion, and may only do so when the count it was given matches what it
     * received: without that, one page would look like the whole model and
     * everything beyond it would be removed locally.
     * @type {string}
     * @memberof ListPageThemesResponse
     */
    totalCount?: string;
}

/**
 * Check if a given object implements the ListPageThemesResponse interface.
 */
export function instanceOfListPageThemesResponse(value: object): value is ListPageThemesResponse {
    return true;
}

export function ListPageThemesResponseFromJSON(json: any): ListPageThemesResponse {
    return ListPageThemesResponseFromJSONTyped(json, false);
}

export function ListPageThemesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPageThemesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nextPageToken': json['nextPageToken'] == null ? undefined : json['nextPageToken'],
        'pageThemes': json['pageThemes'] == null ? undefined : ((json['pageThemes'] as Array<any>).map(PageThemeFromJSON)),
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
    };
}

export function ListPageThemesResponseToJSON(json: any): ListPageThemesResponse {
    return ListPageThemesResponseToJSONTyped(json, false);
}

export function ListPageThemesResponseToJSONTyped(value?: ListPageThemesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nextPageToken': value['nextPageToken'],
        'pageThemes': value['pageThemes'] == null ? undefined : ((value['pageThemes'] as Array<any>).map(PageThemeToJSON)),
        'totalCount': value['totalCount'],
    };
}

