/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListVisitorAttributeKeysResponse
 */
export interface ListVisitorAttributeKeysResponse {
    /**
     * Distinct selectable visitor attribute keys, including reserved system fields such as $email and $phone.
     * @type {Array<string>}
     * @memberof ListVisitorAttributeKeysResponse
     */
    attributeKeys?: Array<string>;
}

/**
 * Check if a given object implements the ListVisitorAttributeKeysResponse interface.
 */
export function instanceOfListVisitorAttributeKeysResponse(value: object): value is ListVisitorAttributeKeysResponse {
    return true;
}

export function ListVisitorAttributeKeysResponseFromJSON(json: any): ListVisitorAttributeKeysResponse {
    return ListVisitorAttributeKeysResponseFromJSONTyped(json, false);
}

export function ListVisitorAttributeKeysResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListVisitorAttributeKeysResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'attributeKeys': json['attributeKeys'] == null ? undefined : json['attributeKeys'],
    };
}

export function ListVisitorAttributeKeysResponseToJSON(json: any): ListVisitorAttributeKeysResponse {
    return ListVisitorAttributeKeysResponseToJSONTyped(json, false);
}

export function ListVisitorAttributeKeysResponseToJSONTyped(value?: ListVisitorAttributeKeysResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attributeKeys': value['attributeKeys'],
    };
}

