/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Member } from './Member';
import {
    MemberFromJSON,
    MemberFromJSONTyped,
    MemberToJSON,
    MemberToJSONTyped,
} from './Member';

/**
 * ListResponse wraps the current page of teammates for the workspace directory.
 * @export
 * @interface ListResponse
 */
export interface ListResponse {
    /**
     * 
     * @type {Array<Member>}
     * @memberof ListResponse
     */
    members?: Array<Member>;
}

/**
 * Check if a given object implements the ListResponse interface.
 */
export function instanceOfListResponse(value: object): value is ListResponse {
    return true;
}

export function ListResponseFromJSON(json: any): ListResponse {
    return ListResponseFromJSONTyped(json, false);
}

export function ListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(MemberFromJSON)),
    };
}

export function ListResponseToJSON(json: any): ListResponse {
    return ListResponseToJSONTyped(json, false);
}

export function ListResponseToJSONTyped(value?: ListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(MemberToJSON)),
    };
}

