/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.149.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - METERED_UNIT_UNSPECIFIED: Not set
 *  - METERED_UNIT_LINK_CREATED: A link created
 *  - METERED_UNIT_LINK_VISITED: A tracked visit
 *  - METERED_UNIT_PUBLIC_API_CALL: A public API call
 *  - METERED_UNIT_CUSTOM_DOMAIN_CREATED: A custom domain created
 * @export
 */
export const MeteredUnit = {
    MeteredUnitUnspecified: 'METERED_UNIT_UNSPECIFIED',
    MeteredUnitLinkCreated: 'METERED_UNIT_LINK_CREATED',
    MeteredUnitLinkVisited: 'METERED_UNIT_LINK_VISITED',
    MeteredUnitPublicApiCall: 'METERED_UNIT_PUBLIC_API_CALL',
    MeteredUnitCustomDomainCreated: 'METERED_UNIT_CUSTOM_DOMAIN_CREATED'
} as const;
export type MeteredUnit = typeof MeteredUnit[keyof typeof MeteredUnit];


export function instanceOfMeteredUnit(value: any): boolean {
    for (const key in MeteredUnit) {
        if (Object.prototype.hasOwnProperty.call(MeteredUnit, key)) {
            if (MeteredUnit[key as keyof typeof MeteredUnit] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MeteredUnitFromJSON(json: any): MeteredUnit {
    return MeteredUnitFromJSONTyped(json, false);
}

export function MeteredUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeteredUnit {
    return json as MeteredUnit;
}

export function MeteredUnitToJSON(value?: MeteredUnit | null): any {
    return value as any;
}

export function MeteredUnitToJSONTyped(value: any, ignoreDiscriminator: boolean): MeteredUnit {
    return value as MeteredUnit;
}

