/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.34.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultiLinkSelectedButton } from './MultiLinkSelectedButton';
import {
    MultiLinkSelectedButtonFromJSON,
    MultiLinkSelectedButtonFromJSONTyped,
    MultiLinkSelectedButtonToJSON,
    MultiLinkSelectedButtonToJSONTyped,
} from './MultiLinkSelectedButton';

/**
 * MultiLinkTraceData stores selection data from a multi-link step.
 * @export
 * @interface MultiLinkTraceData
 */
export interface MultiLinkTraceData {
    /**
     * 
     * @type {MultiLinkSelectedButton}
     * @memberof MultiLinkTraceData
     */
    selectedButton?: MultiLinkSelectedButton;
}

/**
 * Check if a given object implements the MultiLinkTraceData interface.
 */
export function instanceOfMultiLinkTraceData(value: object): value is MultiLinkTraceData {
    return true;
}

export function MultiLinkTraceDataFromJSON(json: any): MultiLinkTraceData {
    return MultiLinkTraceDataFromJSONTyped(json, false);
}

export function MultiLinkTraceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiLinkTraceData {
    if (json == null) {
        return json;
    }
    return {
        
        'selectedButton': json['selectedButton'] == null ? undefined : MultiLinkSelectedButtonFromJSON(json['selectedButton']),
    };
}

export function MultiLinkTraceDataToJSON(json: any): MultiLinkTraceData {
    return MultiLinkTraceDataToJSONTyped(json, false);
}

export function MultiLinkTraceDataToJSONTyped(value?: MultiLinkTraceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'selectedButton': MultiLinkSelectedButtonToJSON(value['selectedButton']),
    };
}

