/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultiLinkTraceSelectedButton } from './MultiLinkTraceSelectedButton';
import {
    MultiLinkTraceSelectedButtonFromJSON,
    MultiLinkTraceSelectedButtonFromJSONTyped,
    MultiLinkTraceSelectedButtonToJSON,
    MultiLinkTraceSelectedButtonToJSONTyped,
} from './MultiLinkTraceSelectedButton';
import type { MultiLinkTraceButton } from './MultiLinkTraceButton';
import {
    MultiLinkTraceButtonFromJSON,
    MultiLinkTraceButtonFromJSONTyped,
    MultiLinkTraceButtonToJSON,
    MultiLinkTraceButtonToJSONTyped,
} from './MultiLinkTraceButton';

/**
 * MultiLinkTraceData stores selection data from a multi-link step.
 * @export
 * @interface MultiLinkTraceData
 */
export interface MultiLinkTraceData {
    /**
     * 
     * @type {Array<MultiLinkTraceButton>}
     * @memberof MultiLinkTraceData
     */
    availableButtons?: Array<MultiLinkTraceButton>;
    /**
     * 
     * @type {string}
     * @memberof MultiLinkTraceData
     */
    description?: string;
    /**
     * 
     * @type {MultiLinkTraceSelectedButton}
     * @memberof MultiLinkTraceData
     */
    selectedButton?: MultiLinkTraceSelectedButton;
    /**
     * 
     * @type {string}
     * @memberof MultiLinkTraceData
     */
    title?: string;
}

/**
 * Check if a given object implements the MultiLinkTraceData interface.
 */
export function instanceOfMultiLinkTraceData(value: object): value is MultiLinkTraceData {
    return true;
}

export function MultiLinkTraceDataFromJSON(json: any): MultiLinkTraceData {
    return MultiLinkTraceDataFromJSONTyped(json, false);
}

export function MultiLinkTraceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiLinkTraceData {
    if (json == null) {
        return json;
    }
    return {
        
        'availableButtons': json['availableButtons'] == null ? undefined : ((json['availableButtons'] as Array<any>).map(MultiLinkTraceButtonFromJSON)),
        'description': json['description'] == null ? undefined : json['description'],
        'selectedButton': json['selectedButton'] == null ? undefined : MultiLinkTraceSelectedButtonFromJSON(json['selectedButton']),
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function MultiLinkTraceDataToJSON(json: any): MultiLinkTraceData {
    return MultiLinkTraceDataToJSONTyped(json, false);
}

export function MultiLinkTraceDataToJSONTyped(value?: MultiLinkTraceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'availableButtons': value['availableButtons'] == null ? undefined : ((value['availableButtons'] as Array<any>).map(MultiLinkTraceButtonToJSON)),
        'description': value['description'],
        'selectedButton': MultiLinkTraceSelectedButtonToJSON(value['selectedButton']),
        'title': value['title'],
    };
}

