/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.37.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - OUTPUT_FILE_FORMAT_UNSPECIFIED: Output format not specified (defaults to PNG server-side)
 *  - OUTPUT_FILE_FORMAT_SVG: Scalable Vector Graphics format for infinite resolution
 *  - OUTPUT_FILE_FORMAT_PNG: Portable Network Graphics format with transparency support
 *  - OUTPUT_FILE_FORMAT_JPEG: Joint Photographic Experts Group format for compressed images
 *  - OUTPUT_FILE_FORMAT_WEBP: WebP format for modern web-optimized compression
 * @export
 */
export const OutputFileFormat = {
    OutputFileFormatUnspecified: 'OUTPUT_FILE_FORMAT_UNSPECIFIED',
    OutputFileFormatSvg: 'OUTPUT_FILE_FORMAT_SVG',
    OutputFileFormatPng: 'OUTPUT_FILE_FORMAT_PNG',
    OutputFileFormatJpeg: 'OUTPUT_FILE_FORMAT_JPEG',
    OutputFileFormatWebp: 'OUTPUT_FILE_FORMAT_WEBP'
} as const;
export type OutputFileFormat = typeof OutputFileFormat[keyof typeof OutputFileFormat];


export function instanceOfOutputFileFormat(value: any): boolean {
    for (const key in OutputFileFormat) {
        if (Object.prototype.hasOwnProperty.call(OutputFileFormat, key)) {
            if (OutputFileFormat[key as keyof typeof OutputFileFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OutputFileFormatFromJSON(json: any): OutputFileFormat {
    return OutputFileFormatFromJSONTyped(json, false);
}

export function OutputFileFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputFileFormat {
    return json as OutputFileFormat;
}

export function OutputFileFormatToJSON(value?: OutputFileFormat | null): any {
    return value as any;
}

export function OutputFileFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): OutputFileFormat {
    return value as OutputFileFormat;
}

