/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.45.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *  - PAGE_THEME_FONT_FAMILY_UNSPECIFIED: Maps to the default system sans-serif stack.
 * @export
 */
export const PageThemeFontFamily = {
    PageThemeFontFamilyUnspecified: 'PAGE_THEME_FONT_FAMILY_UNSPECIFIED',
    PageThemeFontFamilyDefault: 'PAGE_THEME_FONT_FAMILY_DEFAULT',
    PageThemeFontFamilyArial: 'PAGE_THEME_FONT_FAMILY_ARIAL',
    PageThemeFontFamilyHelvetica: 'PAGE_THEME_FONT_FAMILY_HELVETICA',
    PageThemeFontFamilyVerdana: 'PAGE_THEME_FONT_FAMILY_VERDANA',
    PageThemeFontFamilyGeorgia: 'PAGE_THEME_FONT_FAMILY_GEORGIA',
    PageThemeFontFamilyTimesNewRoman: 'PAGE_THEME_FONT_FAMILY_TIMES_NEW_ROMAN',
    PageThemeFontFamilyCourierNew: 'PAGE_THEME_FONT_FAMILY_COURIER_NEW'
} as const;
export type PageThemeFontFamily = typeof PageThemeFontFamily[keyof typeof PageThemeFontFamily];


export function instanceOfPageThemeFontFamily(value: any): boolean {
    for (const key in PageThemeFontFamily) {
        if (Object.prototype.hasOwnProperty.call(PageThemeFontFamily, key)) {
            if (PageThemeFontFamily[key as keyof typeof PageThemeFontFamily] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PageThemeFontFamilyFromJSON(json: any): PageThemeFontFamily {
    return PageThemeFontFamilyFromJSONTyped(json, false);
}

export function PageThemeFontFamilyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageThemeFontFamily {
    return json as PageThemeFontFamily;
}

export function PageThemeFontFamilyToJSON(value?: PageThemeFontFamily | null): any {
    return value as any;
}

export function PageThemeFontFamilyToJSONTyped(value: any, ignoreDiscriminator: boolean): PageThemeFontFamily {
    return value as PageThemeFontFamily;
}

