/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.36.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordPayload
 */
export interface PasswordPayload {
    /**
     * 
     * @type {string}
     * @memberof PasswordPayload
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordPayload
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordPayload
     */
    title?: string;
}

/**
 * Check if a given object implements the PasswordPayload interface.
 */
export function instanceOfPasswordPayload(value: object): value is PasswordPayload {
    return true;
}

export function PasswordPayloadFromJSON(json: any): PasswordPayload {
    return PasswordPayloadFromJSONTyped(json, false);
}

export function PasswordPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'password': json['password'] == null ? undefined : json['password'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function PasswordPayloadToJSON(json: any): PasswordPayload {
    return PasswordPayloadToJSONTyped(json, false);
}

export function PasswordPayloadToJSONTyped(value?: PasswordPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'password': value['password'],
        'title': value['title'],
    };
}

