/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.148.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - PRICING_PLAN_ID_UNSPECIFIED: Not set
 *  - PRICING_PLAN_ID_FREE: Free plan, no payment
 *  - PRICING_PLAN_ID_LIGHT: Light plan
 *  - PRICING_PLAN_ID_PRO: Pro plan. Trials and sponsored workspaces are allowed what Pro allows unless a limit says otherwise.
 *  - PRICING_PLAN_ID_ENTERPRISE: Enterprise plan, billed per unit used
 * @export
 */
export const PricingPlanId = {
    PricingPlanIdUnspecified: 'PRICING_PLAN_ID_UNSPECIFIED',
    PricingPlanIdFree: 'PRICING_PLAN_ID_FREE',
    PricingPlanIdLight: 'PRICING_PLAN_ID_LIGHT',
    PricingPlanIdPro: 'PRICING_PLAN_ID_PRO',
    PricingPlanIdEnterprise: 'PRICING_PLAN_ID_ENTERPRISE'
} as const;
export type PricingPlanId = typeof PricingPlanId[keyof typeof PricingPlanId];


export function instanceOfPricingPlanId(value: any): boolean {
    for (const key in PricingPlanId) {
        if (Object.prototype.hasOwnProperty.call(PricingPlanId, key)) {
            if (PricingPlanId[key as keyof typeof PricingPlanId] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PricingPlanIdFromJSON(json: any): PricingPlanId {
    return PricingPlanIdFromJSONTyped(json, false);
}

export function PricingPlanIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingPlanId {
    return json as PricingPlanId;
}

export function PricingPlanIdToJSON(value?: PricingPlanId | null): any {
    return value as any;
}

export function PricingPlanIdToJSONTyped(value: any, ignoreDiscriminator: boolean): PricingPlanId {
    return value as PricingPlanId;
}

