/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageTheme } from './PageTheme';
import {
    PageThemeFromJSON,
    PageThemeFromJSONTyped,
    PageThemeToJSON,
    PageThemeToJSONTyped,
} from './PageTheme';
import type { PublicWorkspace } from './PublicWorkspace';
import {
    PublicWorkspaceFromJSON,
    PublicWorkspaceFromJSONTyped,
    PublicWorkspaceToJSON,
    PublicWorkspaceToJSONTyped,
} from './PublicWorkspace';

/**
 * 
 * @export
 * @interface PublicPageThemeTemplate
 */
export interface PublicPageThemeTemplate {
    /**
     * Signed URL for the template's badge image. Empty when it has no badge.
     * @type {string}
     * @memberof PublicPageThemeTemplate
     */
    badgeSignedUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PublicPageThemeTemplate
     */
    builtIn?: boolean;
    /**
     * Signed URL for the template's cover image. Empty when it has no cover.
     * @type {string}
     * @memberof PublicPageThemeTemplate
     */
    coverSignedUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPageThemeTemplate
     */
    description?: string;
    /**
     * Frequently Asked Questions about this template stored as JSON
     * @type {string}
     * @memberof PublicPageThemeTemplate
     */
    faq?: string;
    /**
     * Extended markdown-supported content providing detailed information about the template
     * @type {string}
     * @memberof PublicPageThemeTemplate
     */
    learnMore?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPageThemeTemplate
     */
    name?: string;
    /**
     * The styling itself, so a public gallery can render a live preview rather
     * than only the rasterized thumbnail.
     * @type {PageTheme}
     * @memberof PublicPageThemeTemplate
     */
    pageTheme?: PageTheme;
    /**
     * 
     * @type {Date}
     * @memberof PublicPageThemeTemplate
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PublicPageThemeTemplate
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPageThemeTemplate
     */
    tags?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicPageThemeTemplate
     */
    thumbnailSignedUrl?: string;
    /**
     * Public information about the workspace that created this template. Empty for built-in templates. Only included when 'workspace' is specified in the include parameter.
     * @type {PublicWorkspace}
     * @memberof PublicPageThemeTemplate
     */
    workspace?: PublicWorkspace;
}

/**
 * Check if a given object implements the PublicPageThemeTemplate interface.
 */
export function instanceOfPublicPageThemeTemplate(value: object): value is PublicPageThemeTemplate {
    return true;
}

export function PublicPageThemeTemplateFromJSON(json: any): PublicPageThemeTemplate {
    return PublicPageThemeTemplateFromJSONTyped(json, false);
}

export function PublicPageThemeTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicPageThemeTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'badgeSignedUrl': json['badgeSignedUrl'] == null ? undefined : json['badgeSignedUrl'],
        'builtIn': json['builtIn'] == null ? undefined : json['builtIn'],
        'coverSignedUrl': json['coverSignedUrl'] == null ? undefined : json['coverSignedUrl'],
        'description': json['description'] == null ? undefined : json['description'],
        'faq': json['faq'] == null ? undefined : json['faq'],
        'learnMore': json['learnMore'] == null ? undefined : json['learnMore'],
        'name': json['name'] == null ? undefined : json['name'],
        'pageTheme': json['pageTheme'] == null ? undefined : PageThemeFromJSON(json['pageTheme']),
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'slug': json['slug'] == null ? undefined : json['slug'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'thumbnailSignedUrl': json['thumbnailSignedUrl'] == null ? undefined : json['thumbnailSignedUrl'],
        'workspace': json['workspace'] == null ? undefined : PublicWorkspaceFromJSON(json['workspace']),
    };
}

export function PublicPageThemeTemplateToJSON(json: any): PublicPageThemeTemplate {
    return PublicPageThemeTemplateToJSONTyped(json, false);
}

export function PublicPageThemeTemplateToJSONTyped(value?: PublicPageThemeTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'badgeSignedUrl': value['badgeSignedUrl'],
        'builtIn': value['builtIn'],
        'coverSignedUrl': value['coverSignedUrl'],
        'description': value['description'],
        'faq': value['faq'],
        'learnMore': value['learnMore'],
        'name': value['name'],
        'pageTheme': PageThemeToJSON(value['pageTheme']),
        'publishedAt': value['publishedAt'] == null ? value['publishedAt'] : value['publishedAt'].toISOString(),
        'slug': value['slug'],
        'tags': value['tags'],
        'thumbnailSignedUrl': value['thumbnailSignedUrl'],
        'workspace': PublicWorkspaceToJSON(value['workspace']),
    };
}

