/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.131.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicPageThemeTemplate } from './PublicPageThemeTemplate';
import {
    PublicPageThemeTemplateFromJSON,
    PublicPageThemeTemplateFromJSONTyped,
    PublicPageThemeTemplateToJSON,
    PublicPageThemeTemplateToJSONTyped,
} from './PublicPageThemeTemplate';

/**
 * 
 * @export
 * @interface PublicListPageThemeTemplatesResponse
 */
export interface PublicListPageThemeTemplatesResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PublicListPageThemeTemplatesResponse
     */
    hasMore?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PublicListPageThemeTemplatesResponse
     */
    nextPageToken?: string;
    /**
     * 
     * @type {Array<PublicPageThemeTemplate>}
     * @memberof PublicListPageThemeTemplatesResponse
     */
    pageThemeTemplates?: Array<PublicPageThemeTemplate>;
}

/**
 * Check if a given object implements the PublicListPageThemeTemplatesResponse interface.
 */
export function instanceOfPublicListPageThemeTemplatesResponse(value: object): value is PublicListPageThemeTemplatesResponse {
    return true;
}

export function PublicListPageThemeTemplatesResponseFromJSON(json: any): PublicListPageThemeTemplatesResponse {
    return PublicListPageThemeTemplatesResponseFromJSONTyped(json, false);
}

export function PublicListPageThemeTemplatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicListPageThemeTemplatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'hasMore': json['hasMore'] == null ? undefined : json['hasMore'],
        'nextPageToken': json['nextPageToken'] == null ? undefined : json['nextPageToken'],
        'pageThemeTemplates': json['pageThemeTemplates'] == null ? undefined : ((json['pageThemeTemplates'] as Array<any>).map(PublicPageThemeTemplateFromJSON)),
    };
}

export function PublicListPageThemeTemplatesResponseToJSON(json: any): PublicListPageThemeTemplatesResponse {
    return PublicListPageThemeTemplatesResponseToJSONTyped(json, false);
}

export function PublicListPageThemeTemplatesResponseToJSONTyped(value?: PublicListPageThemeTemplatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasMore': value['hasMore'],
        'nextPageToken': value['nextPageToken'],
        'pageThemeTemplates': value['pageThemeTemplates'] == null ? undefined : ((value['pageThemeTemplates'] as Array<any>).map(PublicPageThemeTemplateToJSON)),
    };
}

