/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QrcodeTemplatesServiceUpdateQrcodeTemplateBody
 */
export interface QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    /**
     * 
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    faq?: string;
    /**
     * Extended markdown-supported content providing detailed information about the template
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    learnMore?: string;
    /**
     * 
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    tags?: string;
}

/**
 * Check if a given object implements the QrcodeTemplatesServiceUpdateQrcodeTemplateBody interface.
 */
export function instanceOfQrcodeTemplatesServiceUpdateQrcodeTemplateBody(value: object): value is QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    return true;
}

export function QrcodeTemplatesServiceUpdateQrcodeTemplateBodyFromJSON(json: any): QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    return QrcodeTemplatesServiceUpdateQrcodeTemplateBodyFromJSONTyped(json, false);
}

export function QrcodeTemplatesServiceUpdateQrcodeTemplateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'faq': json['faq'] == null ? undefined : json['faq'],
        'learnMore': json['learnMore'] == null ? undefined : json['learnMore'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function QrcodeTemplatesServiceUpdateQrcodeTemplateBodyToJSON(json: any): QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    return QrcodeTemplatesServiceUpdateQrcodeTemplateBodyToJSONTyped(json, false);
}

export function QrcodeTemplatesServiceUpdateQrcodeTemplateBodyToJSONTyped(value?: QrcodeTemplatesServiceUpdateQrcodeTemplateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'faq': value['faq'],
        'learnMore': value['learnMore'],
        'name': value['name'],
        'slug': value['slug'],
        'tags': value['tags'],
    };
}

