/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QrcodeTemplatesServiceUpdateQrcodeTemplateBody
 */
export interface QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    /**
     * 
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    faq?: string;
    /**
     * Extended markdown-supported content providing detailed information about the template
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    learnMore?: string;
    /**
     * 
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof QrcodeTemplatesServiceUpdateQrcodeTemplateBody
     */
    tags?: string;
}

/**
 * Check if a given object implements the QrcodeTemplatesServiceUpdateQrcodeTemplateBody interface.
 */
export function instanceOfQrcodeTemplatesServiceUpdateQrcodeTemplateBody(value: object): value is QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    return true;
}

export function QrcodeTemplatesServiceUpdateQrcodeTemplateBodyFromJSON(json: any): QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    return QrcodeTemplatesServiceUpdateQrcodeTemplateBodyFromJSONTyped(json, false);
}

export function QrcodeTemplatesServiceUpdateQrcodeTemplateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'faq': json['faq'] == null ? undefined : json['faq'],
        'learnMore': json['learnMore'] == null ? undefined : json['learnMore'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function QrcodeTemplatesServiceUpdateQrcodeTemplateBodyToJSON(json: any): QrcodeTemplatesServiceUpdateQrcodeTemplateBody {
    return QrcodeTemplatesServiceUpdateQrcodeTemplateBodyToJSONTyped(json, false);
}

export function QrcodeTemplatesServiceUpdateQrcodeTemplateBodyToJSONTyped(value?: QrcodeTemplatesServiceUpdateQrcodeTemplateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'faq': value['faq'],
        'learnMore': value['learnMore'],
        'name': value['name'],
        'slug': value['slug'],
        'tags': value['tags'],
    };
}

