/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CornersSquareOptions } from './CornersSquareOptions';
import {
    CornersSquareOptionsFromJSON,
    CornersSquareOptionsFromJSONTyped,
    CornersSquareOptionsToJSON,
    CornersSquareOptionsToJSONTyped,
} from './CornersSquareOptions';
import type { DotsOptions } from './DotsOptions';
import {
    DotsOptionsFromJSON,
    DotsOptionsFromJSONTyped,
    DotsOptionsToJSON,
    DotsOptionsToJSONTyped,
} from './DotsOptions';
import type { CornersDotOptions } from './CornersDotOptions';
import {
    CornersDotOptionsFromJSON,
    CornersDotOptionsFromJSONTyped,
    CornersDotOptionsToJSON,
    CornersDotOptionsToJSONTyped,
} from './CornersDotOptions';
import type { BackgroundOptions } from './BackgroundOptions';
import {
    BackgroundOptionsFromJSON,
    BackgroundOptionsFromJSONTyped,
    BackgroundOptionsToJSON,
    BackgroundOptionsToJSONTyped,
} from './BackgroundOptions';

/**
 * UpdateQrcodeDesignRequest updates colors, shapes, and media used when regenerating QR assets.
 * @export
 * @interface QrcodeDesignServiceUpdateBody
 */
export interface QrcodeDesignServiceUpdateBody {
    /**
     * 
     * @type {BackgroundOptions}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    backgroundOptions?: BackgroundOptions;
    /**
     * The image to use as the central image of the QR Code. The file size limit is 3MB. It must be transmitted in a base64 string format when sending it through HTTP.
     * @type {string}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    centralImageData?: string;
    /**
     * Set this to true to delete the central image. It can't be used at the same time as transmitting a central image.
     * @type {boolean}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    centralImageDelete?: boolean;
    /**
     * 
     * @type {number}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    centralImageMargin?: number;
    /**
     * 
     * @type {number}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    centralImageSize?: number;
    /**
     * 
     * @type {CornersDotOptions}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    cornersDotOptions?: CornersDotOptions;
    /**
     * 
     * @type {CornersSquareOptions}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    cornersSquareOptions?: CornersSquareOptions;
    /**
     * 
     * @type {DotsOptions}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    dotsOptions?: DotsOptions;
    /**
     * 
     * @type {string}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    errorCorrectionLevel?: string;
    /**
     * 
     * @type {number}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    height?: number;
    /**
     * 
     * @type {boolean}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    hideBackgroundDots?: boolean;
    /**
     * - OUTPUT_FILE_FORMAT_UNSPECIFIED: Output format not specified (defaults to PNG server-side)
     *  - OUTPUT_FILE_FORMAT_SVG: Scalable Vector Graphics format for infinite resolution
     *  - OUTPUT_FILE_FORMAT_PNG: Portable Network Graphics format with transparency support
     *  - OUTPUT_FILE_FORMAT_JPEG: Joint Photographic Experts Group format for compressed images
     *  - OUTPUT_FILE_FORMAT_WEBP: WebP format for modern web-optimized compression
     * @type {QrcodeDesignServiceUpdateBodyOutputFileFormatEnum}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    outputFileFormat?: QrcodeDesignServiceUpdateBodyOutputFileFormatEnum;
    /**
     * - SHAPE_UNSPECIFIED: Shape not specified (defaults to square modules)
     *  - SHAPE_SQUARE: Traditional square modules for QR code data points
     *  - SHAPE_CIRCLE: Circular modules for a rounded visual appearance
     * @type {QrcodeDesignServiceUpdateBodyShapeEnum}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    shape?: QrcodeDesignServiceUpdateBodyShapeEnum;
    /**
     * 
     * @type {number}
     * @memberof QrcodeDesignServiceUpdateBody
     */
    width?: number;
}


/**
 * @export
 */
export const QrcodeDesignServiceUpdateBodyOutputFileFormatEnum = {
    OutputFileFormatUnspecified: 'OUTPUT_FILE_FORMAT_UNSPECIFIED',
    OutputFileFormatSvg: 'OUTPUT_FILE_FORMAT_SVG',
    OutputFileFormatPng: 'OUTPUT_FILE_FORMAT_PNG',
    OutputFileFormatJpeg: 'OUTPUT_FILE_FORMAT_JPEG',
    OutputFileFormatWebp: 'OUTPUT_FILE_FORMAT_WEBP'
} as const;
export type QrcodeDesignServiceUpdateBodyOutputFileFormatEnum = typeof QrcodeDesignServiceUpdateBodyOutputFileFormatEnum[keyof typeof QrcodeDesignServiceUpdateBodyOutputFileFormatEnum];

/**
 * @export
 */
export const QrcodeDesignServiceUpdateBodyShapeEnum = {
    ShapeUnspecified: 'SHAPE_UNSPECIFIED',
    ShapeSquare: 'SHAPE_SQUARE',
    ShapeCircle: 'SHAPE_CIRCLE'
} as const;
export type QrcodeDesignServiceUpdateBodyShapeEnum = typeof QrcodeDesignServiceUpdateBodyShapeEnum[keyof typeof QrcodeDesignServiceUpdateBodyShapeEnum];


/**
 * Check if a given object implements the QrcodeDesignServiceUpdateBody interface.
 */
export function instanceOfQrcodeDesignServiceUpdateBody(value: object): value is QrcodeDesignServiceUpdateBody {
    return true;
}

export function QrcodeDesignServiceUpdateBodyFromJSON(json: any): QrcodeDesignServiceUpdateBody {
    return QrcodeDesignServiceUpdateBodyFromJSONTyped(json, false);
}

export function QrcodeDesignServiceUpdateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): QrcodeDesignServiceUpdateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'backgroundOptions': json['backgroundOptions'] == null ? undefined : BackgroundOptionsFromJSON(json['backgroundOptions']),
        'centralImageData': json['centralImageData'] == null ? undefined : json['centralImageData'],
        'centralImageDelete': json['centralImageDelete'] == null ? undefined : json['centralImageDelete'],
        'centralImageMargin': json['centralImageMargin'] == null ? undefined : json['centralImageMargin'],
        'centralImageSize': json['centralImageSize'] == null ? undefined : json['centralImageSize'],
        'cornersDotOptions': json['cornersDotOptions'] == null ? undefined : CornersDotOptionsFromJSON(json['cornersDotOptions']),
        'cornersSquareOptions': json['cornersSquareOptions'] == null ? undefined : CornersSquareOptionsFromJSON(json['cornersSquareOptions']),
        'dotsOptions': json['dotsOptions'] == null ? undefined : DotsOptionsFromJSON(json['dotsOptions']),
        'errorCorrectionLevel': json['errorCorrectionLevel'] == null ? undefined : json['errorCorrectionLevel'],
        'height': json['height'] == null ? undefined : json['height'],
        'hideBackgroundDots': json['hideBackgroundDots'] == null ? undefined : json['hideBackgroundDots'],
        'outputFileFormat': json['outputFileFormat'] == null ? undefined : json['outputFileFormat'],
        'shape': json['shape'] == null ? undefined : json['shape'],
        'width': json['width'] == null ? undefined : json['width'],
    };
}

export function QrcodeDesignServiceUpdateBodyToJSON(json: any): QrcodeDesignServiceUpdateBody {
    return QrcodeDesignServiceUpdateBodyToJSONTyped(json, false);
}

export function QrcodeDesignServiceUpdateBodyToJSONTyped(value?: QrcodeDesignServiceUpdateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'backgroundOptions': BackgroundOptionsToJSON(value['backgroundOptions']),
        'centralImageData': value['centralImageData'],
        'centralImageDelete': value['centralImageDelete'],
        'centralImageMargin': value['centralImageMargin'],
        'centralImageSize': value['centralImageSize'],
        'cornersDotOptions': CornersDotOptionsToJSON(value['cornersDotOptions']),
        'cornersSquareOptions': CornersSquareOptionsToJSON(value['cornersSquareOptions']),
        'dotsOptions': DotsOptionsToJSON(value['dotsOptions']),
        'errorCorrectionLevel': value['errorCorrectionLevel'],
        'height': value['height'],
        'hideBackgroundDots': value['hideBackgroundDots'],
        'outputFileFormat': value['outputFileFormat'],
        'shape': value['shape'],
        'width': value['width'],
    };
}

