/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers.  ## Authentication  All API endpoints require Bearer token authentication. Obtain your workspace API token from the Linkbreakers dashboard, then include it in the `Authorization` header as `Bearer YOUR_TOKEN`.  When using official SDKs, pass your token to the `accessToken` parameter (NOT `apiKey`) in the Configuration constructor:  ```typescript const config = new Configuration({   accessToken: \'your-workspace-token\',   basePath: \'https://api.linkbreakers.com\', }); ```
 *
 * The version of the OpenAPI document: 1.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * RedirectTraceData stores redirect exit information.
 * @export
 * @interface RedirectTraceData
 */
export interface RedirectTraceData {
    /**
     * 
     * @type {boolean}
     * @memberof RedirectTraceData
     */
    conversionTracking?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RedirectTraceData
     */
    destination?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RedirectTraceData
     */
    fallback?: boolean;
}

/**
 * Check if a given object implements the RedirectTraceData interface.
 */
export function instanceOfRedirectTraceData(value: object): value is RedirectTraceData {
    return true;
}

export function RedirectTraceDataFromJSON(json: any): RedirectTraceData {
    return RedirectTraceDataFromJSONTyped(json, false);
}

export function RedirectTraceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): RedirectTraceData {
    if (json == null) {
        return json;
    }
    return {
        
        'conversionTracking': json['conversionTracking'] == null ? undefined : json['conversionTracking'],
        'destination': json['destination'] == null ? undefined : json['destination'],
        'fallback': json['fallback'] == null ? undefined : json['fallback'],
    };
}

export function RedirectTraceDataToJSON(json: any): RedirectTraceData {
    return RedirectTraceDataToJSONTyped(json, false);
}

export function RedirectTraceDataToJSONTyped(value?: RedirectTraceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conversionTracking': value['conversionTracking'],
        'destination': value['destination'],
        'fallback': value['fallback'],
    };
}

