/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ResponseFormat defines the transport format the API should return for list-style endpoints.
 * 
 *  - RESPONSE_FORMAT_UNSPECIFIED: Response format not specified
 *  - RESPONSE_FORMAT_JSON: Response format JSON
 *  - RESPONSE_FORMAT_CSV: Response format CSV
 * @export
 */
export const ResponseFormat = {
    ResponseFormatUnspecified: 'RESPONSE_FORMAT_UNSPECIFIED',
    ResponseFormatJson: 'RESPONSE_FORMAT_JSON',
    ResponseFormatCsv: 'RESPONSE_FORMAT_CSV'
} as const;
export type ResponseFormat = typeof ResponseFormat[keyof typeof ResponseFormat];


export function instanceOfResponseFormat(value: any): boolean {
    for (const key in ResponseFormat) {
        if (Object.prototype.hasOwnProperty.call(ResponseFormat, key)) {
            if (ResponseFormat[key as keyof typeof ResponseFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResponseFormatFromJSON(json: any): ResponseFormat {
    return ResponseFormatFromJSONTyped(json, false);
}

export function ResponseFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseFormat {
    return json as ResponseFormat;
}

export function ResponseFormatToJSON(value?: ResponseFormat | null): any {
    return value as any;
}

export function ResponseFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): ResponseFormat {
    return value as ResponseFormat;
}

