/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - SHAPE_UNSPECIFIED: Shape not specified (defaults to square modules)
 *  - SHAPE_SQUARE: Traditional square modules for QR code data points
 *  - SHAPE_CIRCLE: Circular modules for a rounded visual appearance
 * @export
 */
export const Shape = {
    ShapeUnspecified: 'SHAPE_UNSPECIFIED',
    ShapeSquare: 'SHAPE_SQUARE',
    ShapeCircle: 'SHAPE_CIRCLE'
} as const;
export type Shape = typeof Shape[keyof typeof Shape];


export function instanceOfShape(value: any): boolean {
    for (const key in Shape) {
        if (Object.prototype.hasOwnProperty.call(Shape, key)) {
            if (Shape[key as keyof typeof Shape] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ShapeFromJSON(json: any): Shape {
    return ShapeFromJSONTyped(json, false);
}

export function ShapeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Shape {
    return json as Shape;
}

export function ShapeToJSON(value?: Shape | null): any {
    return value as any;
}

export function ShapeToJSONTyped(value: any, ignoreDiscriminator: boolean): Shape {
    return value as Shape;
}

