/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShortlinkAvailabilityResponse
 */
export interface ShortlinkAvailabilityResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ShortlinkAvailabilityResponse
     */
    available?: boolean;
}

/**
 * Check if a given object implements the ShortlinkAvailabilityResponse interface.
 */
export function instanceOfShortlinkAvailabilityResponse(value: object): value is ShortlinkAvailabilityResponse {
    return true;
}

export function ShortlinkAvailabilityResponseFromJSON(json: any): ShortlinkAvailabilityResponse {
    return ShortlinkAvailabilityResponseFromJSONTyped(json, false);
}

export function ShortlinkAvailabilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShortlinkAvailabilityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'available': json['available'] == null ? undefined : json['available'],
    };
}

export function ShortlinkAvailabilityResponseToJSON(json: any): ShortlinkAvailabilityResponse {
    return ShortlinkAvailabilityResponseToJSONTyped(json, false);
}

export function ShortlinkAvailabilityResponseToJSONTyped(value?: ShortlinkAvailabilityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'available': value['available'],
    };
}

