/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - SOCIAL_LINKS_DISPLAY_STYLE_DETAILED: Display icon with text label (default)
 *  - SOCIAL_LINKS_DISPLAY_STYLE_COMPACT: Display icons only in a compact row
 * @export
 */
export const SocialLinksDisplayStyle = {
    SocialLinksDisplayStyleUnspecified: 'SOCIAL_LINKS_DISPLAY_STYLE_UNSPECIFIED',
    SocialLinksDisplayStyleDetailed: 'SOCIAL_LINKS_DISPLAY_STYLE_DETAILED',
    SocialLinksDisplayStyleCompact: 'SOCIAL_LINKS_DISPLAY_STYLE_COMPACT'
} as const;
export type SocialLinksDisplayStyle = typeof SocialLinksDisplayStyle[keyof typeof SocialLinksDisplayStyle];


export function instanceOfSocialLinksDisplayStyle(value: any): boolean {
    for (const key in SocialLinksDisplayStyle) {
        if (Object.prototype.hasOwnProperty.call(SocialLinksDisplayStyle, key)) {
            if (SocialLinksDisplayStyle[key as keyof typeof SocialLinksDisplayStyle] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SocialLinksDisplayStyleFromJSON(json: any): SocialLinksDisplayStyle {
    return SocialLinksDisplayStyleFromJSONTyped(json, false);
}

export function SocialLinksDisplayStyleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialLinksDisplayStyle {
    return json as SocialLinksDisplayStyle;
}

export function SocialLinksDisplayStyleToJSON(value?: SocialLinksDisplayStyle | null): any {
    return value as any;
}

export function SocialLinksDisplayStyleToJSONTyped(value: any, ignoreDiscriminator: boolean): SocialLinksDisplayStyle {
    return value as SocialLinksDisplayStyle;
}

