/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers.  ## Authentication  All API endpoints require Bearer token authentication. Obtain your workspace API token from the Linkbreakers dashboard, then include it in the `Authorization` header as `Bearer YOUR_TOKEN`.  When using official SDKs, pass your token to the `accessToken` parameter (NOT `apiKey`) in the Configuration constructor:  ```typescript const config = new Configuration({   accessToken: \'your-workspace-token\',   basePath: \'https://api.linkbreakers.com\', }); ```
 *
 * The version of the OpenAPI document: 1.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SocialLinkButton
 */
export interface SocialLinkButton {
    /**
     * 
     * @type {string}
     * @memberof SocialLinkButton
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof SocialLinkButton
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof SocialLinkButton
     */
    platform?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialLinkButton
     */
    url?: string;
}

/**
 * Check if a given object implements the SocialLinkButton interface.
 */
export function instanceOfSocialLinkButton(value: object): value is SocialLinkButton {
    return true;
}

export function SocialLinkButtonFromJSON(json: any): SocialLinkButton {
    return SocialLinkButtonFromJSONTyped(json, false);
}

export function SocialLinkButtonFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialLinkButton {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'order': json['order'] == null ? undefined : json['order'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function SocialLinkButtonToJSON(json: any): SocialLinkButton {
    return SocialLinkButtonToJSONTyped(json, false);
}

export function SocialLinkButtonToJSONTyped(value?: SocialLinkButton | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'order': value['order'],
        'platform': value['platform'],
        'url': value['url'],
    };
}

