/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.127.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocketMessageType } from './SocketMessageType';
import {
    SocketMessageTypeFromJSON,
    SocketMessageTypeFromJSONTyped,
    SocketMessageTypeToJSON,
    SocketMessageTypeToJSONTyped,
} from './SocketMessageType';
import type { ChatUIAction } from './ChatUIAction';
import {
    ChatUIActionFromJSON,
    ChatUIActionFromJSONTyped,
    ChatUIActionToJSON,
    ChatUIActionToJSONTyped,
} from './ChatUIAction';

/**
 * SocketAgentResponseMessage is the agent's reply to one message.
 * @export
 * @interface SocketAgentResponseMessage
 */
export interface SocketAgentResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof SocketAgentResponseMessage
     */
    appliedActions?: Array<string>;
    /**
     * True when the agent changed the resource, so the screen should re-read it.
     * @type {boolean}
     * @memberof SocketAgentResponseMessage
     */
    contextUpdated?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SocketAgentResponseMessage
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof SocketAgentResponseMessage
     */
    responseText?: string;
    /**
     * 
     * @type {SocketMessageType}
     * @memberof SocketAgentResponseMessage
     */
    type?: SocketMessageType;
    /**
     * 
     * @type {Array<ChatUIAction>}
     * @memberof SocketAgentResponseMessage
     */
    uiActions?: Array<ChatUIAction>;
}



/**
 * Check if a given object implements the SocketAgentResponseMessage interface.
 */
export function instanceOfSocketAgentResponseMessage(value: object): value is SocketAgentResponseMessage {
    return true;
}

export function SocketAgentResponseMessageFromJSON(json: any): SocketAgentResponseMessage {
    return SocketAgentResponseMessageFromJSONTyped(json, false);
}

export function SocketAgentResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocketAgentResponseMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'appliedActions': json['appliedActions'] == null ? undefined : json['appliedActions'],
        'contextUpdated': json['contextUpdated'] == null ? undefined : json['contextUpdated'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'responseText': json['responseText'] == null ? undefined : json['responseText'],
        'type': json['type'] == null ? undefined : SocketMessageTypeFromJSON(json['type']),
        'uiActions': json['uiActions'] == null ? undefined : ((json['uiActions'] as Array<any>).map(ChatUIActionFromJSON)),
    };
}

export function SocketAgentResponseMessageToJSON(json: any): SocketAgentResponseMessage {
    return SocketAgentResponseMessageToJSONTyped(json, false);
}

export function SocketAgentResponseMessageToJSONTyped(value?: SocketAgentResponseMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appliedActions': value['appliedActions'],
        'contextUpdated': value['contextUpdated'],
        'requestId': value['requestId'],
        'responseText': value['responseText'],
        'type': SocketMessageTypeToJSON(value['type']),
        'uiActions': value['uiActions'] == null ? undefined : ((value['uiActions'] as Array<any>).map(ChatUIActionToJSON)),
    };
}

