/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.127.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocketMessageType } from './SocketMessageType';
import {
    SocketMessageTypeFromJSON,
    SocketMessageTypeFromJSONTyped,
    SocketMessageTypeToJSON,
    SocketMessageTypeToJSONTyped,
} from './SocketMessageType';
import type { SocketErrorCode } from './SocketErrorCode';
import {
    SocketErrorCodeFromJSON,
    SocketErrorCodeFromJSONTyped,
    SocketErrorCodeToJSON,
    SocketErrorCodeToJSONTyped,
} from './SocketErrorCode';

/**
 * SocketSubscribeDeniedMessage refuses a channel the caller may not read.
 * 
 * Said out loud rather than dropped silently: a client that believes it is
 * subscribed and receives nothing cannot tell that apart from a quiet channel.
 * @export
 * @interface SocketSubscribeDeniedMessage
 */
export interface SocketSubscribeDeniedMessage {
    /**
     * 
     * @type {string}
     * @memberof SocketSubscribeDeniedMessage
     */
    channel?: string;
    /**
     * 
     * @type {SocketErrorCode}
     * @memberof SocketSubscribeDeniedMessage
     */
    code?: SocketErrorCode;
    /**
     * 
     * @type {string}
     * @memberof SocketSubscribeDeniedMessage
     */
    message?: string;
    /**
     * 
     * @type {SocketMessageType}
     * @memberof SocketSubscribeDeniedMessage
     */
    type?: SocketMessageType;
}



/**
 * Check if a given object implements the SocketSubscribeDeniedMessage interface.
 */
export function instanceOfSocketSubscribeDeniedMessage(value: object): value is SocketSubscribeDeniedMessage {
    return true;
}

export function SocketSubscribeDeniedMessageFromJSON(json: any): SocketSubscribeDeniedMessage {
    return SocketSubscribeDeniedMessageFromJSONTyped(json, false);
}

export function SocketSubscribeDeniedMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocketSubscribeDeniedMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'channel': json['channel'] == null ? undefined : json['channel'],
        'code': json['code'] == null ? undefined : SocketErrorCodeFromJSON(json['code']),
        'message': json['message'] == null ? undefined : json['message'],
        'type': json['type'] == null ? undefined : SocketMessageTypeFromJSON(json['type']),
    };
}

export function SocketSubscribeDeniedMessageToJSON(json: any): SocketSubscribeDeniedMessage {
    return SocketSubscribeDeniedMessageToJSONTyped(json, false);
}

export function SocketSubscribeDeniedMessageToJSONTyped(value?: SocketSubscribeDeniedMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'channel': value['channel'],
        'code': SocketErrorCodeToJSON(value['code']),
        'message': value['message'],
        'type': SocketMessageTypeToJSON(value['type']),
    };
}

