/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.128.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocketMessageType } from './SocketMessageType';
import {
    SocketMessageTypeFromJSON,
    SocketMessageTypeFromJSONTyped,
    SocketMessageTypeToJSON,
    SocketMessageTypeToJSONTyped,
} from './SocketMessageType';
import type { SocketErrorCode } from './SocketErrorCode';
import {
    SocketErrorCodeFromJSON,
    SocketErrorCodeFromJSONTyped,
    SocketErrorCodeToJSON,
    SocketErrorCodeToJSONTyped,
} from './SocketErrorCode';

/**
 * SocketAgentErrorMessage says why there will be no reply.
 * @export
 * @interface SocketAgentErrorMessage
 */
export interface SocketAgentErrorMessage {
    /**
     * 
     * @type {SocketErrorCode}
     * @memberof SocketAgentErrorMessage
     */
    errorCode?: SocketErrorCode;
    /**
     * 
     * @type {string}
     * @memberof SocketAgentErrorMessage
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof SocketAgentErrorMessage
     */
    requestId?: string;
    /**
     * 
     * @type {SocketMessageType}
     * @memberof SocketAgentErrorMessage
     */
    type?: SocketMessageType;
}



/**
 * Check if a given object implements the SocketAgentErrorMessage interface.
 */
export function instanceOfSocketAgentErrorMessage(value: object): value is SocketAgentErrorMessage {
    return true;
}

export function SocketAgentErrorMessageFromJSON(json: any): SocketAgentErrorMessage {
    return SocketAgentErrorMessageFromJSONTyped(json, false);
}

export function SocketAgentErrorMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocketAgentErrorMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'] == null ? undefined : SocketErrorCodeFromJSON(json['errorCode']),
        'message': json['message'] == null ? undefined : json['message'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'type': json['type'] == null ? undefined : SocketMessageTypeFromJSON(json['type']),
    };
}

export function SocketAgentErrorMessageToJSON(json: any): SocketAgentErrorMessage {
    return SocketAgentErrorMessageToJSONTyped(json, false);
}

export function SocketAgentErrorMessageToJSONTyped(value?: SocketAgentErrorMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorCode': SocketErrorCodeToJSON(value['errorCode']),
        'message': value['message'],
        'requestId': value['requestId'],
        'type': SocketMessageTypeToJSON(value['type']),
    };
}

