/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocketConnectedMessage } from './SocketConnectedMessage';
import {
    SocketConnectedMessageFromJSON,
    SocketConnectedMessageFromJSONTyped,
    SocketConnectedMessageToJSON,
    SocketConnectedMessageToJSONTyped,
} from './SocketConnectedMessage';
import type { SocketPingRequest } from './SocketPingRequest';
import {
    SocketPingRequestFromJSON,
    SocketPingRequestFromJSONTyped,
    SocketPingRequestToJSON,
    SocketPingRequestToJSONTyped,
} from './SocketPingRequest';
import type { SocketSubscribeDeniedMessage } from './SocketSubscribeDeniedMessage';
import {
    SocketSubscribeDeniedMessageFromJSON,
    SocketSubscribeDeniedMessageFromJSONTyped,
    SocketSubscribeDeniedMessageToJSON,
    SocketSubscribeDeniedMessageToJSONTyped,
} from './SocketSubscribeDeniedMessage';
import type { SocketPongMessage } from './SocketPongMessage';
import {
    SocketPongMessageFromJSON,
    SocketPongMessageFromJSONTyped,
    SocketPongMessageToJSON,
    SocketPongMessageToJSONTyped,
} from './SocketPongMessage';
import type { SocketSubscribeRequest } from './SocketSubscribeRequest';
import {
    SocketSubscribeRequestFromJSON,
    SocketSubscribeRequestFromJSONTyped,
    SocketSubscribeRequestToJSON,
    SocketSubscribeRequestToJSONTyped,
} from './SocketSubscribeRequest';
import type { SocketEventMessage } from './SocketEventMessage';
import {
    SocketEventMessageFromJSON,
    SocketEventMessageFromJSONTyped,
    SocketEventMessageToJSON,
    SocketEventMessageToJSONTyped,
} from './SocketEventMessage';
import type { SocketAssistantSendRequest } from './SocketAssistantSendRequest';
import {
    SocketAssistantSendRequestFromJSON,
    SocketAssistantSendRequestFromJSONTyped,
    SocketAssistantSendRequestToJSON,
    SocketAssistantSendRequestToJSONTyped,
} from './SocketAssistantSendRequest';
import type { SocketAssistantResponseMessage } from './SocketAssistantResponseMessage';
import {
    SocketAssistantResponseMessageFromJSON,
    SocketAssistantResponseMessageFromJSONTyped,
    SocketAssistantResponseMessageToJSON,
    SocketAssistantResponseMessageToJSONTyped,
} from './SocketAssistantResponseMessage';
import type { SocketSubscribedMessage } from './SocketSubscribedMessage';
import {
    SocketSubscribedMessageFromJSON,
    SocketSubscribedMessageFromJSONTyped,
    SocketSubscribedMessageToJSON,
    SocketSubscribedMessageToJSONTyped,
} from './SocketSubscribedMessage';
import type { SocketAssistantErrorMessage } from './SocketAssistantErrorMessage';
import {
    SocketAssistantErrorMessageFromJSON,
    SocketAssistantErrorMessageFromJSONTyped,
    SocketAssistantErrorMessageToJSON,
    SocketAssistantErrorMessageToJSONTyped,
} from './SocketAssistantErrorMessage';
import type { SocketAssistantProgressMessage } from './SocketAssistantProgressMessage';
import {
    SocketAssistantProgressMessageFromJSON,
    SocketAssistantProgressMessageFromJSONTyped,
    SocketAssistantProgressMessageToJSON,
    SocketAssistantProgressMessageToJSONTyped,
} from './SocketAssistantProgressMessage';
import type { SocketUnsubscribeRequest } from './SocketUnsubscribeRequest';
import {
    SocketUnsubscribeRequestFromJSON,
    SocketUnsubscribeRequestFromJSONTyped,
    SocketUnsubscribeRequestToJSON,
    SocketUnsubscribeRequestToJSONTyped,
} from './SocketUnsubscribeRequest';

/**
 * SocketContract names every frame the socket carries.
 * 
 * Its fields are what put these messages in the generated clients: a websocket
 * has no HTTP operation of its own, and a message no operation mentions is not
 * emitted. The endpoint answers with the protocol version; the rest of this
 * message is the schema both sides are generated from.
 * @export
 * @interface SocketContract
 */
export interface SocketContract {
    /**
     * 
     * @type {SocketAssistantErrorMessage}
     * @memberof SocketContract
     */
    assistantError?: SocketAssistantErrorMessage;
    /**
     * 
     * @type {SocketAssistantProgressMessage}
     * @memberof SocketContract
     */
    assistantProgress?: SocketAssistantProgressMessage;
    /**
     * 
     * @type {SocketAssistantResponseMessage}
     * @memberof SocketContract
     */
    assistantResponse?: SocketAssistantResponseMessage;
    /**
     * 
     * @type {SocketAssistantSendRequest}
     * @memberof SocketContract
     */
    assistantSend?: SocketAssistantSendRequest;
    /**
     * 
     * @type {SocketConnectedMessage}
     * @memberof SocketContract
     */
    connected?: SocketConnectedMessage;
    /**
     * 
     * @type {SocketEventMessage}
     * @memberof SocketContract
     */
    event?: SocketEventMessage;
    /**
     * 
     * @type {SocketPingRequest}
     * @memberof SocketContract
     */
    ping?: SocketPingRequest;
    /**
     * 
     * @type {SocketPongMessage}
     * @memberof SocketContract
     */
    pong?: SocketPongMessage;
    /**
     * 
     * @type {string}
     * @memberof SocketContract
     */
    protocolVersion?: string;
    /**
     * 
     * @type {SocketSubscribeRequest}
     * @memberof SocketContract
     */
    subscribe?: SocketSubscribeRequest;
    /**
     * 
     * @type {SocketSubscribeDeniedMessage}
     * @memberof SocketContract
     */
    subscribeDenied?: SocketSubscribeDeniedMessage;
    /**
     * 
     * @type {SocketSubscribedMessage}
     * @memberof SocketContract
     */
    subscribed?: SocketSubscribedMessage;
    /**
     * 
     * @type {SocketUnsubscribeRequest}
     * @memberof SocketContract
     */
    unsubscribe?: SocketUnsubscribeRequest;
}

/**
 * Check if a given object implements the SocketContract interface.
 */
export function instanceOfSocketContract(value: object): value is SocketContract {
    return true;
}

export function SocketContractFromJSON(json: any): SocketContract {
    return SocketContractFromJSONTyped(json, false);
}

export function SocketContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocketContract {
    if (json == null) {
        return json;
    }
    return {
        
        'assistantError': json['assistantError'] == null ? undefined : SocketAssistantErrorMessageFromJSON(json['assistantError']),
        'assistantProgress': json['assistantProgress'] == null ? undefined : SocketAssistantProgressMessageFromJSON(json['assistantProgress']),
        'assistantResponse': json['assistantResponse'] == null ? undefined : SocketAssistantResponseMessageFromJSON(json['assistantResponse']),
        'assistantSend': json['assistantSend'] == null ? undefined : SocketAssistantSendRequestFromJSON(json['assistantSend']),
        'connected': json['connected'] == null ? undefined : SocketConnectedMessageFromJSON(json['connected']),
        'event': json['event'] == null ? undefined : SocketEventMessageFromJSON(json['event']),
        'ping': json['ping'] == null ? undefined : SocketPingRequestFromJSON(json['ping']),
        'pong': json['pong'] == null ? undefined : SocketPongMessageFromJSON(json['pong']),
        'protocolVersion': json['protocolVersion'] == null ? undefined : json['protocolVersion'],
        'subscribe': json['subscribe'] == null ? undefined : SocketSubscribeRequestFromJSON(json['subscribe']),
        'subscribeDenied': json['subscribeDenied'] == null ? undefined : SocketSubscribeDeniedMessageFromJSON(json['subscribeDenied']),
        'subscribed': json['subscribed'] == null ? undefined : SocketSubscribedMessageFromJSON(json['subscribed']),
        'unsubscribe': json['unsubscribe'] == null ? undefined : SocketUnsubscribeRequestFromJSON(json['unsubscribe']),
    };
}

export function SocketContractToJSON(json: any): SocketContract {
    return SocketContractToJSONTyped(json, false);
}

export function SocketContractToJSONTyped(value?: SocketContract | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assistantError': SocketAssistantErrorMessageToJSON(value['assistantError']),
        'assistantProgress': SocketAssistantProgressMessageToJSON(value['assistantProgress']),
        'assistantResponse': SocketAssistantResponseMessageToJSON(value['assistantResponse']),
        'assistantSend': SocketAssistantSendRequestToJSON(value['assistantSend']),
        'connected': SocketConnectedMessageToJSON(value['connected']),
        'event': SocketEventMessageToJSON(value['event']),
        'ping': SocketPingRequestToJSON(value['ping']),
        'pong': SocketPongMessageToJSON(value['pong']),
        'protocolVersion': value['protocolVersion'],
        'subscribe': SocketSubscribeRequestToJSON(value['subscribe']),
        'subscribeDenied': SocketSubscribeDeniedMessageToJSON(value['subscribeDenied']),
        'subscribed': SocketSubscribedMessageToJSON(value['subscribed']),
        'unsubscribe': SocketUnsubscribeRequestToJSON(value['unsubscribe']),
    };
}

