/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.135.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocketMessageType } from './SocketMessageType';
import {
    SocketMessageTypeFromJSON,
    SocketMessageTypeFromJSONTyped,
    SocketMessageTypeToJSON,
    SocketMessageTypeToJSONTyped,
} from './SocketMessageType';
import type { SocketErrorCode } from './SocketErrorCode';
import {
    SocketErrorCodeFromJSON,
    SocketErrorCodeFromJSONTyped,
    SocketErrorCodeToJSON,
    SocketErrorCodeToJSONTyped,
} from './SocketErrorCode';

/**
 * SocketAssistantErrorMessage says why there will be no reply.
 * @export
 * @interface SocketAssistantErrorMessage
 */
export interface SocketAssistantErrorMessage {
    /**
     * 
     * @type {SocketErrorCode}
     * @memberof SocketAssistantErrorMessage
     */
    errorCode?: SocketErrorCode;
    /**
     * 
     * @type {string}
     * @memberof SocketAssistantErrorMessage
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof SocketAssistantErrorMessage
     */
    requestId?: string;
    /**
     * 
     * @type {SocketMessageType}
     * @memberof SocketAssistantErrorMessage
     */
    type?: SocketMessageType;
}



/**
 * Check if a given object implements the SocketAssistantErrorMessage interface.
 */
export function instanceOfSocketAssistantErrorMessage(value: object): value is SocketAssistantErrorMessage {
    return true;
}

export function SocketAssistantErrorMessageFromJSON(json: any): SocketAssistantErrorMessage {
    return SocketAssistantErrorMessageFromJSONTyped(json, false);
}

export function SocketAssistantErrorMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocketAssistantErrorMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'errorCode': json['errorCode'] == null ? undefined : SocketErrorCodeFromJSON(json['errorCode']),
        'message': json['message'] == null ? undefined : json['message'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'type': json['type'] == null ? undefined : SocketMessageTypeFromJSON(json['type']),
    };
}

export function SocketAssistantErrorMessageToJSON(json: any): SocketAssistantErrorMessage {
    return SocketAssistantErrorMessageToJSONTyped(json, false);
}

export function SocketAssistantErrorMessageToJSONTyped(value?: SocketAssistantErrorMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errorCode': SocketErrorCodeToJSON(value['errorCode']),
        'message': value['message'],
        'requestId': value['requestId'],
        'type': SocketMessageTypeToJSON(value['type']),
    };
}

