/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocketMessageType } from './SocketMessageType';
import {
    SocketMessageTypeFromJSON,
    SocketMessageTypeFromJSONTyped,
    SocketMessageTypeToJSON,
    SocketMessageTypeToJSONTyped,
} from './SocketMessageType';

/**
 * SocketAssistantSendRequest asks the assistant for a reply.
 * @export
 * @interface SocketAssistantSendRequest
 */
export interface SocketAssistantSendRequest {
    /**
     * 
     * @type {string}
     * @memberof SocketAssistantSendRequest
     */
    contextId?: string;
    /**
     * Whatever the page knows and the assistant cannot see.
     * @type {string}
     * @memberof SocketAssistantSendRequest
     */
    contextMetadata?: string;
    /**
     * 
     * @type {string}
     * @memberof SocketAssistantSendRequest
     */
    contextType?: string;
    /**
     * Files already uploaded, to attach to this turn.
     * @type {Array<string>}
     * @memberof SocketAssistantSendRequest
     */
    fileIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SocketAssistantSendRequest
     */
    message?: string;
    /**
     * Correlates the reply to this message. The client generates it.
     * @type {string}
     * @memberof SocketAssistantSendRequest
     */
    requestId?: string;
    /**
     * 
     * @type {SocketMessageType}
     * @memberof SocketAssistantSendRequest
     */
    type?: SocketMessageType;
}



/**
 * Check if a given object implements the SocketAssistantSendRequest interface.
 */
export function instanceOfSocketAssistantSendRequest(value: object): value is SocketAssistantSendRequest {
    return true;
}

export function SocketAssistantSendRequestFromJSON(json: any): SocketAssistantSendRequest {
    return SocketAssistantSendRequestFromJSONTyped(json, false);
}

export function SocketAssistantSendRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocketAssistantSendRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contextId': json['contextId'] == null ? undefined : json['contextId'],
        'contextMetadata': json['contextMetadata'] == null ? undefined : json['contextMetadata'],
        'contextType': json['contextType'] == null ? undefined : json['contextType'],
        'fileIds': json['fileIds'] == null ? undefined : json['fileIds'],
        'message': json['message'] == null ? undefined : json['message'],
        'requestId': json['requestId'] == null ? undefined : json['requestId'],
        'type': json['type'] == null ? undefined : SocketMessageTypeFromJSON(json['type']),
    };
}

export function SocketAssistantSendRequestToJSON(json: any): SocketAssistantSendRequest {
    return SocketAssistantSendRequestToJSONTyped(json, false);
}

export function SocketAssistantSendRequestToJSONTyped(value?: SocketAssistantSendRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contextId': value['contextId'],
        'contextMetadata': value['contextMetadata'],
        'contextType': value['contextType'],
        'fileIds': value['fileIds'],
        'message': value['message'],
        'requestId': value['requestId'],
        'type': SocketMessageTypeToJSON(value['type']),
    };
}

