/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.144.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SocketMessageType } from './SocketMessageType';
import {
    SocketMessageTypeFromJSON,
    SocketMessageTypeFromJSONTyped,
    SocketMessageTypeToJSON,
    SocketMessageTypeToJSONTyped,
} from './SocketMessageType';

/**
 * SocketPongMessage answers a ping.
 * @export
 * @interface SocketPongMessage
 */
export interface SocketPongMessage {
    /**
     * 
     * @type {SocketMessageType}
     * @memberof SocketPongMessage
     */
    type?: SocketMessageType;
}



/**
 * Check if a given object implements the SocketPongMessage interface.
 */
export function instanceOfSocketPongMessage(value: object): value is SocketPongMessage {
    return true;
}

export function SocketPongMessageFromJSON(json: any): SocketPongMessage {
    return SocketPongMessageFromJSONTyped(json, false);
}

export function SocketPongMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocketPongMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : SocketMessageTypeFromJSON(json['type']),
    };
}

export function SocketPongMessageToJSON(json: any): SocketPongMessage {
    return SocketPongMessageToJSONTyped(json, false);
}

export function SocketPongMessageToJSONTyped(value?: SocketPongMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': SocketMessageTypeToJSON(value['type']),
    };
}

