/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpecificDateOption
 */
export interface SpecificDateOption {
    /**
     * Day of month (1-31)
     * @type {number}
     * @memberof SpecificDateOption
     */
    day?: number;
    /**
     * 
     * @type {string}
     * @memberof SpecificDateOption
     */
    id?: string;
    /**
     * Month (1-12)
     * @type {number}
     * @memberof SpecificDateOption
     */
    month?: number;
    /**
     * 
     * @type {string}
     * @memberof SpecificDateOption
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SpecificDateOption
     */
    nextStepId?: string;
    /**
     * Year (optional, for one-time dates)
     * @type {number}
     * @memberof SpecificDateOption
     */
    year?: number;
}

/**
 * Check if a given object implements the SpecificDateOption interface.
 */
export function instanceOfSpecificDateOption(value: object): value is SpecificDateOption {
    return true;
}

export function SpecificDateOptionFromJSON(json: any): SpecificDateOption {
    return SpecificDateOptionFromJSONTyped(json, false);
}

export function SpecificDateOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpecificDateOption {
    if (json == null) {
        return json;
    }
    return {
        
        'day': json['day'] == null ? undefined : json['day'],
        'id': json['id'] == null ? undefined : json['id'],
        'month': json['month'] == null ? undefined : json['month'],
        'name': json['name'] == null ? undefined : json['name'],
        'nextStepId': json['nextStepId'] == null ? undefined : json['nextStepId'],
        'year': json['year'] == null ? undefined : json['year'],
    };
}

export function SpecificDateOptionToJSON(json: any): SpecificDateOption {
    return SpecificDateOptionToJSONTyped(json, false);
}

export function SpecificDateOptionToJSONTyped(value?: SpecificDateOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'day': value['day'],
        'id': value['id'],
        'month': value['month'],
        'name': value['name'],
        'nextStepId': value['nextStepId'],
        'year': value['year'],
    };
}

