/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.44.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpecificDateConditionTraceOption } from './SpecificDateConditionTraceOption';
import {
    SpecificDateConditionTraceOptionFromJSON,
    SpecificDateConditionTraceOptionFromJSONTyped,
    SpecificDateConditionTraceOptionToJSON,
    SpecificDateConditionTraceOptionToJSONTyped,
} from './SpecificDateConditionTraceOption';

/**
 * SpecificDateConditionTraceData stores specific-date condition routing metadata.
 * @export
 * @interface SpecificDateConditionTraceData
 */
export interface SpecificDateConditionTraceData {
    /**
     * 
     * @type {boolean}
     * @memberof SpecificDateConditionTraceData
     */
    hasElse?: boolean;
    /**
     * 
     * @type {Array<SpecificDateConditionTraceOption>}
     * @memberof SpecificDateConditionTraceData
     */
    options?: Array<SpecificDateConditionTraceOption>;
}

/**
 * Check if a given object implements the SpecificDateConditionTraceData interface.
 */
export function instanceOfSpecificDateConditionTraceData(value: object): value is SpecificDateConditionTraceData {
    return true;
}

export function SpecificDateConditionTraceDataFromJSON(json: any): SpecificDateConditionTraceData {
    return SpecificDateConditionTraceDataFromJSONTyped(json, false);
}

export function SpecificDateConditionTraceDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpecificDateConditionTraceData {
    if (json == null) {
        return json;
    }
    return {
        
        'hasElse': json['hasElse'] == null ? undefined : json['hasElse'],
        'options': json['options'] == null ? undefined : ((json['options'] as Array<any>).map(SpecificDateConditionTraceOptionFromJSON)),
    };
}

export function SpecificDateConditionTraceDataToJSON(json: any): SpecificDateConditionTraceData {
    return SpecificDateConditionTraceDataToJSONTyped(json, false);
}

export function SpecificDateConditionTraceDataToJSONTyped(value?: SpecificDateConditionTraceData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasElse': value['hasElse'],
        'options': value['options'] == null ? undefined : ((value['options'] as Array<any>).map(SpecificDateConditionTraceOptionToJSON)),
    };
}

