/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.91.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ThemeColor } from './ThemeColor';
import {
    ThemeColorFromJSON,
    ThemeColorFromJSONTyped,
    ThemeColorToJSON,
    ThemeColorToJSONTyped,
} from './ThemeColor';

/**
 * Theme override for a specific workflow step.
 * All fields are optional — only set fields override the global page theme
 * when this step is displayed to visitors.
 * @export
 * @interface StepThemeOverride
 */
export interface StepThemeOverride {
    /**
     * 
     * @type {boolean}
     * @memberof StepThemeOverride
     */
    badgeEnabled?: boolean;
    /**
     * 
     * @type {ThemeColor}
     * @memberof StepThemeOverride
     */
    badgeIconColor?: ThemeColor;
    /**
     * 
     * @type {string}
     * @memberof StepThemeOverride
     */
    badgeId?: string;
    /**
     * 
     * @type {StepThemeOverrideBadgeShapeEnum}
     * @memberof StepThemeOverride
     */
    badgeShape?: StepThemeOverrideBadgeShapeEnum;
}


/**
 * @export
 */
export const StepThemeOverrideBadgeShapeEnum = {
    PageThemeBadgeShapeUnspecified: 'PAGE_THEME_BADGE_SHAPE_UNSPECIFIED',
    PageThemeBadgeShapeCircle: 'PAGE_THEME_BADGE_SHAPE_CIRCLE',
    PageThemeBadgeShapeSquare: 'PAGE_THEME_BADGE_SHAPE_SQUARE',
    PageThemeBadgeShapeRounded: 'PAGE_THEME_BADGE_SHAPE_ROUNDED'
} as const;
export type StepThemeOverrideBadgeShapeEnum = typeof StepThemeOverrideBadgeShapeEnum[keyof typeof StepThemeOverrideBadgeShapeEnum];


/**
 * Check if a given object implements the StepThemeOverride interface.
 */
export function instanceOfStepThemeOverride(value: object): value is StepThemeOverride {
    return true;
}

export function StepThemeOverrideFromJSON(json: any): StepThemeOverride {
    return StepThemeOverrideFromJSONTyped(json, false);
}

export function StepThemeOverrideFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepThemeOverride {
    if (json == null) {
        return json;
    }
    return {
        
        'badgeEnabled': json['badgeEnabled'] == null ? undefined : json['badgeEnabled'],
        'badgeIconColor': json['badgeIconColor'] == null ? undefined : ThemeColorFromJSON(json['badgeIconColor']),
        'badgeId': json['badgeId'] == null ? undefined : json['badgeId'],
        'badgeShape': json['badgeShape'] == null ? undefined : json['badgeShape'],
    };
}

export function StepThemeOverrideToJSON(json: any): StepThemeOverride {
    return StepThemeOverrideToJSONTyped(json, false);
}

export function StepThemeOverrideToJSONTyped(value?: StepThemeOverride | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'badgeEnabled': value['badgeEnabled'],
        'badgeIconColor': ThemeColorToJSON(value['badgeIconColor']),
        'badgeId': value['badgeId'],
        'badgeShape': value['badgeShape'],
    };
}

