/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.87.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncGoogleFormsResponse
 */
export interface SyncGoogleFormsResponse {
    /**
     * 
     * @type {string}
     * @memberof SyncGoogleFormsResponse
     */
    responsesSynced?: string;
    /**
     * 
     * @type {string}
     * @memberof SyncGoogleFormsResponse
     */
    visitorsEnriched?: string;
}

/**
 * Check if a given object implements the SyncGoogleFormsResponse interface.
 */
export function instanceOfSyncGoogleFormsResponse(value: object): value is SyncGoogleFormsResponse {
    return true;
}

export function SyncGoogleFormsResponseFromJSON(json: any): SyncGoogleFormsResponse {
    return SyncGoogleFormsResponseFromJSONTyped(json, false);
}

export function SyncGoogleFormsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncGoogleFormsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'responsesSynced': json['responsesSynced'] == null ? undefined : json['responsesSynced'],
        'visitorsEnriched': json['visitorsEnriched'] == null ? undefined : json['visitorsEnriched'],
    };
}

export function SyncGoogleFormsResponseToJSON(json: any): SyncGoogleFormsResponse {
    return SyncGoogleFormsResponseToJSONTyped(json, false);
}

export function SyncGoogleFormsResponseToJSONTyped(value?: SyncGoogleFormsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'responsesSynced': value['responsesSynced'],
        'visitorsEnriched': value['visitorsEnriched'],
    };
}

