/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers.  ## Authentication  All API endpoints require Bearer token authentication. Obtain your workspace API token from the Linkbreakers dashboard, then include it in the `Authorization` header as `Bearer YOUR_TOKEN`.  When using official SDKs, pass your token to the `accessToken` parameter (NOT `apiKey`) in the Configuration constructor:  ```typescript const config = new Configuration({   accessToken: \'your-workspace-token\',   basePath: \'https://api.linkbreakers.com\', }); ```
 *
 * The version of the OpenAPI document: 1.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface UpdateLinkResponse
 */
export interface UpdateLinkResponse {
    /**
     * 
     * @type {Link}
     * @memberof UpdateLinkResponse
     */
    link?: Link;
}

/**
 * Check if a given object implements the UpdateLinkResponse interface.
 */
export function instanceOfUpdateLinkResponse(value: object): value is UpdateLinkResponse {
    return true;
}

export function UpdateLinkResponseFromJSON(json: any): UpdateLinkResponse {
    return UpdateLinkResponseFromJSONTyped(json, false);
}

export function UpdateLinkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLinkResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'] == null ? undefined : LinkFromJSON(json['link']),
    };
}

export function UpdateLinkResponseToJSON(json: any): UpdateLinkResponse {
    return UpdateLinkResponseToJSONTyped(json, false);
}

export function UpdateLinkResponseToJSONTyped(value?: UpdateLinkResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link': LinkToJSON(value['link']),
    };
}

