/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers.  ## Authentication  All API endpoints require Bearer token authentication. Obtain your workspace API token from the Linkbreakers dashboard, then include it in the `Authorization` header as `Bearer YOUR_TOKEN`.  When using official SDKs, pass your token to the `accessToken` parameter (NOT `apiKey`) in the Configuration constructor:  ```typescript const config = new Configuration({   accessToken: \'your-workspace-token\',   basePath: \'https://api.linkbreakers.com\', }); ```
 *
 * The version of the OpenAPI document: 1.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QrcodeDesign } from './QrcodeDesign';
import {
    QrcodeDesignFromJSON,
    QrcodeDesignFromJSONTyped,
    QrcodeDesignToJSON,
    QrcodeDesignToJSONTyped,
} from './QrcodeDesign';

/**
 * UpdateQrcodeDesignResponse returns the refreshed design after applying edits.
 * @export
 * @interface UpdateQrcodeDesignResponse
 */
export interface UpdateQrcodeDesignResponse {
    /**
     * 
     * @type {QrcodeDesign}
     * @memberof UpdateQrcodeDesignResponse
     */
    qrcodeDesign?: QrcodeDesign;
}

/**
 * Check if a given object implements the UpdateQrcodeDesignResponse interface.
 */
export function instanceOfUpdateQrcodeDesignResponse(value: object): value is UpdateQrcodeDesignResponse {
    return true;
}

export function UpdateQrcodeDesignResponseFromJSON(json: any): UpdateQrcodeDesignResponse {
    return UpdateQrcodeDesignResponseFromJSONTyped(json, false);
}

export function UpdateQrcodeDesignResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateQrcodeDesignResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'qrcodeDesign': json['qrcodeDesign'] == null ? undefined : QrcodeDesignFromJSON(json['qrcodeDesign']),
    };
}

export function UpdateQrcodeDesignResponseToJSON(json: any): UpdateQrcodeDesignResponse {
    return UpdateQrcodeDesignResponseToJSONTyped(json, false);
}

export function UpdateQrcodeDesignResponseToJSONTyped(value?: UpdateQrcodeDesignResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qrcodeDesign': QrcodeDesignToJSON(value['qrcodeDesign']),
    };
}

