/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers.  ## Authentication  All API endpoints require Bearer token authentication. Obtain your workspace API token from the Linkbreakers dashboard, then include it in the `Authorization` header as `Bearer YOUR_TOKEN`.  When using official SDKs, pass your token to the `accessToken` parameter (NOT `apiKey`) in the Configuration constructor:  ```typescript const config = new Configuration({   accessToken: \'your-workspace-token\',   basePath: \'https://api.linkbreakers.com\', }); ```
 *
 * The version of the OpenAPI document: 1.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QrcodeTemplate } from './QrcodeTemplate';
import {
    QrcodeTemplateFromJSON,
    QrcodeTemplateFromJSONTyped,
    QrcodeTemplateToJSON,
    QrcodeTemplateToJSONTyped,
} from './QrcodeTemplate';

/**
 * 
 * @export
 * @interface UpdateQrcodeTemplateResponse
 */
export interface UpdateQrcodeTemplateResponse {
    /**
     * 
     * @type {QrcodeTemplate}
     * @memberof UpdateQrcodeTemplateResponse
     */
    qrcodeTemplate?: QrcodeTemplate;
}

/**
 * Check if a given object implements the UpdateQrcodeTemplateResponse interface.
 */
export function instanceOfUpdateQrcodeTemplateResponse(value: object): value is UpdateQrcodeTemplateResponse {
    return true;
}

export function UpdateQrcodeTemplateResponseFromJSON(json: any): UpdateQrcodeTemplateResponse {
    return UpdateQrcodeTemplateResponseFromJSONTyped(json, false);
}

export function UpdateQrcodeTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateQrcodeTemplateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'qrcodeTemplate': json['qrcodeTemplate'] == null ? undefined : QrcodeTemplateFromJSON(json['qrcodeTemplate']),
    };
}

export function UpdateQrcodeTemplateResponseToJSON(json: any): UpdateQrcodeTemplateResponse {
    return UpdateQrcodeTemplateResponseToJSONTyped(json, false);
}

export function UpdateQrcodeTemplateResponseToJSONTyped(value?: UpdateQrcodeTemplateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'qrcodeTemplate': QrcodeTemplateToJSON(value['qrcodeTemplate']),
    };
}

