/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers.  ## Authentication  All API endpoints require Bearer token authentication. Obtain your workspace API token from the Linkbreakers dashboard, then include it in the `Authorization` header as `Bearer YOUR_TOKEN`.  When using official SDKs, pass your token to the `accessToken` parameter (NOT `apiKey`) in the Configuration constructor:  ```typescript const config = new Configuration({   accessToken: \'your-workspace-token\',   basePath: \'https://api.linkbreakers.com\', }); ```
 *
 * The version of the OpenAPI document: 1.35.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationInstructionsCustomDomainResponseValidationType } from './ValidationInstructionsCustomDomainResponseValidationType';
import {
    ValidationInstructionsCustomDomainResponseValidationTypeFromJSON,
    ValidationInstructionsCustomDomainResponseValidationTypeFromJSONTyped,
    ValidationInstructionsCustomDomainResponseValidationTypeToJSON,
    ValidationInstructionsCustomDomainResponseValidationTypeToJSONTyped,
} from './ValidationInstructionsCustomDomainResponseValidationType';
import type { ValidationPurpose } from './ValidationPurpose';
import {
    ValidationPurposeFromJSON,
    ValidationPurposeFromJSONTyped,
    ValidationPurposeToJSON,
    ValidationPurposeToJSONTyped,
} from './ValidationPurpose';

/**
 * 
 * @export
 * @interface ValidationInstructionsCustomDomainResponseValidation
 */
export interface ValidationInstructionsCustomDomainResponseValidation {
    /**
     * 
     * @type {string}
     * @memberof ValidationInstructionsCustomDomainResponseValidation
     */
    name?: string;
    /**
     * 
     * @type {ValidationPurpose}
     * @memberof ValidationInstructionsCustomDomainResponseValidation
     */
    purpose?: ValidationPurpose;
    /**
     * 
     * @type {ValidationInstructionsCustomDomainResponseValidationType}
     * @memberof ValidationInstructionsCustomDomainResponseValidation
     */
    type?: ValidationInstructionsCustomDomainResponseValidationType;
    /**
     * 
     * @type {string}
     * @memberof ValidationInstructionsCustomDomainResponseValidation
     */
    value?: string;
}



/**
 * Check if a given object implements the ValidationInstructionsCustomDomainResponseValidation interface.
 */
export function instanceOfValidationInstructionsCustomDomainResponseValidation(value: object): value is ValidationInstructionsCustomDomainResponseValidation {
    return true;
}

export function ValidationInstructionsCustomDomainResponseValidationFromJSON(json: any): ValidationInstructionsCustomDomainResponseValidation {
    return ValidationInstructionsCustomDomainResponseValidationFromJSONTyped(json, false);
}

export function ValidationInstructionsCustomDomainResponseValidationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationInstructionsCustomDomainResponseValidation {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'purpose': json['purpose'] == null ? undefined : ValidationPurposeFromJSON(json['purpose']),
        'type': json['type'] == null ? undefined : ValidationInstructionsCustomDomainResponseValidationTypeFromJSON(json['type']),
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function ValidationInstructionsCustomDomainResponseValidationToJSON(json: any): ValidationInstructionsCustomDomainResponseValidation {
    return ValidationInstructionsCustomDomainResponseValidationToJSONTyped(json, false);
}

export function ValidationInstructionsCustomDomainResponseValidationToJSONTyped(value?: ValidationInstructionsCustomDomainResponseValidation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'purpose': ValidationPurposeToJSON(value['purpose']),
        'type': ValidationInstructionsCustomDomainResponseValidationTypeToJSON(value['type']),
        'value': value['value'],
    };
}

