/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.46.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - TYPE_UNSPECIFIED: Record type not specified
 *  - TYPE_TXT: TXT DNS record used for validation
 * @export
 */
export const ValidationInstructionsCustomDomainResponseValidationType = {
    TypeUnspecified: 'TYPE_UNSPECIFIED',
    TypeTxt: 'TYPE_TXT'
} as const;
export type ValidationInstructionsCustomDomainResponseValidationType = typeof ValidationInstructionsCustomDomainResponseValidationType[keyof typeof ValidationInstructionsCustomDomainResponseValidationType];


export function instanceOfValidationInstructionsCustomDomainResponseValidationType(value: any): boolean {
    for (const key in ValidationInstructionsCustomDomainResponseValidationType) {
        if (Object.prototype.hasOwnProperty.call(ValidationInstructionsCustomDomainResponseValidationType, key)) {
            if (ValidationInstructionsCustomDomainResponseValidationType[key as keyof typeof ValidationInstructionsCustomDomainResponseValidationType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ValidationInstructionsCustomDomainResponseValidationTypeFromJSON(json: any): ValidationInstructionsCustomDomainResponseValidationType {
    return ValidationInstructionsCustomDomainResponseValidationTypeFromJSONTyped(json, false);
}

export function ValidationInstructionsCustomDomainResponseValidationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationInstructionsCustomDomainResponseValidationType {
    return json as ValidationInstructionsCustomDomainResponseValidationType;
}

export function ValidationInstructionsCustomDomainResponseValidationTypeToJSON(value?: ValidationInstructionsCustomDomainResponseValidationType | null): any {
    return value as any;
}

export function ValidationInstructionsCustomDomainResponseValidationTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ValidationInstructionsCustomDomainResponseValidationType {
    return value as ValidationInstructionsCustomDomainResponseValidationType;
}

