/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.42.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VCardData
 */
export interface VCardData {
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    buttonLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    postalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    streetAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof VCardData
     */
    website?: string;
}

/**
 * Check if a given object implements the VCardData interface.
 */
export function instanceOfVCardData(value: object): value is VCardData {
    return true;
}

export function VCardDataFromJSON(json: any): VCardData {
    return VCardDataFromJSONTyped(json, false);
}

export function VCardDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): VCardData {
    if (json == null) {
        return json;
    }
    return {
        
        'buttonLabel': json['buttonLabel'] == null ? undefined : json['buttonLabel'],
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'postalCode': json['postalCode'] == null ? undefined : json['postalCode'],
        'state': json['state'] == null ? undefined : json['state'],
        'streetAddress': json['streetAddress'] == null ? undefined : json['streetAddress'],
        'title': json['title'] == null ? undefined : json['title'],
        'website': json['website'] == null ? undefined : json['website'],
    };
}

export function VCardDataToJSON(json: any): VCardData {
    return VCardDataToJSONTyped(json, false);
}

export function VCardDataToJSONTyped(value?: VCardData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'buttonLabel': value['buttonLabel'],
        'city': value['city'],
        'country': value['country'],
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'organization': value['organization'],
        'phone': value['phone'],
        'postalCode': value['postalCode'],
        'state': value['state'],
        'streetAddress': value['streetAddress'],
        'title': value['title'],
        'website': value['website'],
    };
}

