/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.118.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * VisitorAttribute is one key/value pair on a visitor profile.
 * @export
 * @interface VisitorAttribute
 */
export interface VisitorAttribute {
    /**
     * 
     * @type {boolean}
     * @memberof VisitorAttribute
     */
    boolValue?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof VisitorAttribute
     */
    dateValue?: Date;
    /**
     * 
     * @type {string}
     * @memberof VisitorAttribute
     */
    key?: string;
    /**
     * Set only when the value parses as a number. Absent when it does not, so a
     * value that contradicts its type is still readable but not aggregatable.
     * @type {number}
     * @memberof VisitorAttribute
     */
    numberValue?: number;
    /**
     * VisitorAttributeType is what a value was captured as. It decides how the
     * value is parsed and which analytics the key can support, which the value
     * alone cannot tell you: "8" from a rating field and "8" typed into a text box
     * are different facts.
     * @type {VisitorAttributeTypeEnum}
     * @memberof VisitorAttribute
     */
    type?: VisitorAttributeTypeEnum;
    /**
     * The raw value as captured. Always populated, whatever the type.
     * @type {string}
     * @memberof VisitorAttribute
     */
    value?: string;
}


/**
 * @export
 */
export const VisitorAttributeTypeEnum = {
    VisitorAttributeTypeUnspecified: 'VISITOR_ATTRIBUTE_TYPE_UNSPECIFIED',
    VisitorAttributeTypeString: 'VISITOR_ATTRIBUTE_TYPE_STRING',
    VisitorAttributeTypeNumber: 'VISITOR_ATTRIBUTE_TYPE_NUMBER',
    VisitorAttributeTypeBoolean: 'VISITOR_ATTRIBUTE_TYPE_BOOLEAN',
    VisitorAttributeTypeDate: 'VISITOR_ATTRIBUTE_TYPE_DATE',
    VisitorAttributeTypeEnum: 'VISITOR_ATTRIBUTE_TYPE_ENUM'
} as const;
export type VisitorAttributeTypeEnum = typeof VisitorAttributeTypeEnum[keyof typeof VisitorAttributeTypeEnum];


/**
 * Check if a given object implements the VisitorAttribute interface.
 */
export function instanceOfVisitorAttribute(value: object): value is VisitorAttribute {
    return true;
}

export function VisitorAttributeFromJSON(json: any): VisitorAttribute {
    return VisitorAttributeFromJSONTyped(json, false);
}

export function VisitorAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisitorAttribute {
    if (json == null) {
        return json;
    }
    return {
        
        'boolValue': json['boolValue'] == null ? undefined : json['boolValue'],
        'dateValue': json['dateValue'] == null ? undefined : (new Date(json['dateValue'])),
        'key': json['key'] == null ? undefined : json['key'],
        'numberValue': json['numberValue'] == null ? undefined : json['numberValue'],
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function VisitorAttributeToJSON(json: any): VisitorAttribute {
    return VisitorAttributeToJSONTyped(json, false);
}

export function VisitorAttributeToJSONTyped(value?: VisitorAttribute | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'boolValue': value['boolValue'],
        'dateValue': value['dateValue'] == null ? value['dateValue'] : value['dateValue'].toISOString(),
        'key': value['key'],
        'numberValue': value['numberValue'],
        'type': value['type'],
        'value': value['value'],
    };
}

