/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * VisitorAttributeType is what a value was captured as. It decides how the
 * value is parsed and which analytics the key can support, which the value
 * alone cannot tell you: "8" from a rating field and "8" typed into a text box
 * are different facts.
 * @export
 */
export const VisitorAttributeType = {
    VisitorAttributeTypeUnspecified: 'VISITOR_ATTRIBUTE_TYPE_UNSPECIFIED',
    VisitorAttributeTypeString: 'VISITOR_ATTRIBUTE_TYPE_STRING',
    VisitorAttributeTypeNumber: 'VISITOR_ATTRIBUTE_TYPE_NUMBER',
    VisitorAttributeTypeBoolean: 'VISITOR_ATTRIBUTE_TYPE_BOOLEAN',
    VisitorAttributeTypeDate: 'VISITOR_ATTRIBUTE_TYPE_DATE',
    VisitorAttributeTypeEnum: 'VISITOR_ATTRIBUTE_TYPE_ENUM'
} as const;
export type VisitorAttributeType = typeof VisitorAttributeType[keyof typeof VisitorAttributeType];


export function instanceOfVisitorAttributeType(value: any): boolean {
    for (const key in VisitorAttributeType) {
        if (Object.prototype.hasOwnProperty.call(VisitorAttributeType, key)) {
            if (VisitorAttributeType[key as keyof typeof VisitorAttributeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function VisitorAttributeTypeFromJSON(json: any): VisitorAttributeType {
    return VisitorAttributeTypeFromJSONTyped(json, false);
}

export function VisitorAttributeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): VisitorAttributeType {
    return json as VisitorAttributeType;
}

export function VisitorAttributeTypeToJSON(value?: VisitorAttributeType | null): any {
    return value as any;
}

export function VisitorAttributeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): VisitorAttributeType {
    return value as VisitorAttributeType;
}

