/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.34.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - WEBHOOK_SOURCE_UNSPECIFIED: Webhook source not specified (defaults to LINKBREAKERS)
 *  - WEBHOOK_SOURCE_LINKBREAKERS: Webhook created manually through the Linkbreakers dashboard/platform
 *  - WEBHOOK_SOURCE_MAKE: Webhook created automatically via Make.com integration
 *  - WEBHOOK_SOURCE_ZAPIER: Webhook created automatically via Zapier integration
 * @export
 */
export const WebhookSource = {
    WebhookSourceUnspecified: 'WEBHOOK_SOURCE_UNSPECIFIED',
    WebhookSourceLinkbreakers: 'WEBHOOK_SOURCE_LINKBREAKERS',
    WebhookSourceMake: 'WEBHOOK_SOURCE_MAKE',
    WebhookSourceZapier: 'WEBHOOK_SOURCE_ZAPIER'
} as const;
export type WebhookSource = typeof WebhookSource[keyof typeof WebhookSource];


export function instanceOfWebhookSource(value: any): boolean {
    for (const key in WebhookSource) {
        if (Object.prototype.hasOwnProperty.call(WebhookSource, key)) {
            if (WebhookSource[key as keyof typeof WebhookSource] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WebhookSourceFromJSON(json: any): WebhookSource {
    return WebhookSourceFromJSONTyped(json, false);
}

export function WebhookSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookSource {
    return json as WebhookSource;
}

export function WebhookSourceToJSON(value?: WebhookSource | null): any {
    return value as any;
}

export function WebhookSourceToJSONTyped(value: any, ignoreDiscriminator: boolean): WebhookSource {
    return value as WebhookSource;
}

