/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.77.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WidgetFieldMapping
 */
export interface WidgetFieldMapping {
    /**
     * 
     * @type {string}
     * @memberof WidgetFieldMapping
     */
    chartRole?: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetFieldMapping
     */
    displayLabel?: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetFieldMapping
     */
    sourceField?: string;
}

/**
 * Check if a given object implements the WidgetFieldMapping interface.
 */
export function instanceOfWidgetFieldMapping(value: object): value is WidgetFieldMapping {
    return true;
}

export function WidgetFieldMappingFromJSON(json: any): WidgetFieldMapping {
    return WidgetFieldMappingFromJSONTyped(json, false);
}

export function WidgetFieldMappingFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetFieldMapping {
    if (json == null) {
        return json;
    }
    return {
        
        'chartRole': json['chartRole'] == null ? undefined : json['chartRole'],
        'displayLabel': json['displayLabel'] == null ? undefined : json['displayLabel'],
        'sourceField': json['sourceField'] == null ? undefined : json['sourceField'],
    };
}

export function WidgetFieldMappingToJSON(json: any): WidgetFieldMapping {
    return WidgetFieldMappingToJSONTyped(json, false);
}

export function WidgetFieldMappingToJSONTyped(value?: WidgetFieldMapping | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chartRole': value['chartRole'],
        'displayLabel': value['displayLabel'],
        'sourceField': value['sourceField'],
    };
}

