/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WidgetSize
 */
export interface WidgetSize {
    /**
     * 
     * @type {number}
     * @memberof WidgetSize
     */
    h?: number;
    /**
     * Column span. In an 8-column config: 8 = full width, 4 = half, 2 = quarter.
     * @type {number}
     * @memberof WidgetSize
     */
    w?: number;
}

/**
 * Check if a given object implements the WidgetSize interface.
 */
export function instanceOfWidgetSize(value: object): value is WidgetSize {
    return true;
}

export function WidgetSizeFromJSON(json: any): WidgetSize {
    return WidgetSizeFromJSONTyped(json, false);
}

export function WidgetSizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetSize {
    if (json == null) {
        return json;
    }
    return {
        
        'h': json['h'] == null ? undefined : json['h'],
        'w': json['w'] == null ? undefined : json['w'],
    };
}

export function WidgetSizeToJSON(json: any): WidgetSize {
    return WidgetSizeToJSONTyped(json, false);
}

export function WidgetSizeToJSONTyped(value?: WidgetSize | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'h': value['h'],
        'w': value['w'],
    };
}

