/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WidgetDataSource
 */
export interface WidgetDataSource {
    /**
     * 
     * @type {string}
     * @memberof WidgetDataSource
     */
    endpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof WidgetDataSource
     */
    method?: string;
    /**
     * 
     * @type {object}
     * @memberof WidgetDataSource
     */
    params?: object;
    /**
     * 
     * @type {string}
     * @memberof WidgetDataSource
     */
    responseDataPath?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WidgetDataSource
     */
    usesDateRange?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WidgetDataSource
     */
    usesInterval?: boolean;
}

/**
 * Check if a given object implements the WidgetDataSource interface.
 */
export function instanceOfWidgetDataSource(value: object): value is WidgetDataSource {
    return true;
}

export function WidgetDataSourceFromJSON(json: any): WidgetDataSource {
    return WidgetDataSourceFromJSONTyped(json, false);
}

export function WidgetDataSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetDataSource {
    if (json == null) {
        return json;
    }
    return {
        
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : json['params'],
        'responseDataPath': json['responseDataPath'] == null ? undefined : json['responseDataPath'],
        'usesDateRange': json['usesDateRange'] == null ? undefined : json['usesDateRange'],
        'usesInterval': json['usesInterval'] == null ? undefined : json['usesInterval'],
    };
}

export function WidgetDataSourceToJSON(json: any): WidgetDataSource {
    return WidgetDataSourceToJSONTyped(json, false);
}

export function WidgetDataSourceToJSONTyped(value?: WidgetDataSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoint': value['endpoint'],
        'method': value['method'],
        'params': value['params'],
        'responseDataPath': value['responseDataPath'],
        'usesDateRange': value['usesDateRange'],
        'usesInterval': value['usesInterval'],
    };
}

