/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * WidgetTabView says how a tab draws what it fetched.
 * 
 *  - WIDGET_TAB_VIEW_UNSPECIFIED: The widget's own chart type.
 *  - WIDGET_TAB_VIEW_MAP: A world map, which needs rows carrying a country code.
 * @export
 */
export const WidgetTabView = {
    WidgetTabViewUnspecified: 'WIDGET_TAB_VIEW_UNSPECIFIED',
    WidgetTabViewChart: 'WIDGET_TAB_VIEW_CHART',
    WidgetTabViewMap: 'WIDGET_TAB_VIEW_MAP'
} as const;
export type WidgetTabView = typeof WidgetTabView[keyof typeof WidgetTabView];


export function instanceOfWidgetTabView(value: any): boolean {
    for (const key in WidgetTabView) {
        if (Object.prototype.hasOwnProperty.call(WidgetTabView, key)) {
            if (WidgetTabView[key as keyof typeof WidgetTabView] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WidgetTabViewFromJSON(json: any): WidgetTabView {
    return WidgetTabViewFromJSONTyped(json, false);
}

export function WidgetTabViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetTabView {
    return json as WidgetTabView;
}

export function WidgetTabViewToJSON(value?: WidgetTabView | null): any {
    return value as any;
}

export function WidgetTabViewToJSONTyped(value: any, ignoreDiscriminator: boolean): WidgetTabView {
    return value as WidgetTabView;
}

