/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.87.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WidgetTab } from './WidgetTab';
import {
    WidgetTabFromJSON,
    WidgetTabFromJSONTyped,
    WidgetTabToJSON,
    WidgetTabToJSONTyped,
} from './WidgetTab';
import type { WidgetFieldMapping } from './WidgetFieldMapping';
import {
    WidgetFieldMappingFromJSON,
    WidgetFieldMappingFromJSONTyped,
    WidgetFieldMappingToJSON,
    WidgetFieldMappingToJSONTyped,
} from './WidgetFieldMapping';

/**
 * 
 * @export
 * @interface WidgetVisualization
 */
export interface WidgetVisualization {
    /**
     * 
     * @type {string}
     * @memberof WidgetVisualization
     */
    chartType?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WidgetVisualization
     */
    colors?: Array<string>;
    /**
     * 
     * @type {Array<WidgetFieldMapping>}
     * @memberof WidgetVisualization
     */
    fieldMappings?: Array<WidgetFieldMapping>;
    /**
     * Optional tabs for grouped views. Each tab has label and params that override the base params.
     * @type {Array<WidgetTab>}
     * @memberof WidgetVisualization
     */
    tabs?: Array<WidgetTab>;
}

/**
 * Check if a given object implements the WidgetVisualization interface.
 */
export function instanceOfWidgetVisualization(value: object): value is WidgetVisualization {
    return true;
}

export function WidgetVisualizationFromJSON(json: any): WidgetVisualization {
    return WidgetVisualizationFromJSONTyped(json, false);
}

export function WidgetVisualizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetVisualization {
    if (json == null) {
        return json;
    }
    return {
        
        'chartType': json['chartType'] == null ? undefined : json['chartType'],
        'colors': json['colors'] == null ? undefined : json['colors'],
        'fieldMappings': json['fieldMappings'] == null ? undefined : ((json['fieldMappings'] as Array<any>).map(WidgetFieldMappingFromJSON)),
        'tabs': json['tabs'] == null ? undefined : ((json['tabs'] as Array<any>).map(WidgetTabFromJSON)),
    };
}

export function WidgetVisualizationToJSON(json: any): WidgetVisualization {
    return WidgetVisualizationToJSONTyped(json, false);
}

export function WidgetVisualizationToJSONTyped(value?: WidgetVisualization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chartType': value['chartType'],
        'colors': value['colors'],
        'fieldMappings': value['fieldMappings'] == null ? undefined : ((value['fieldMappings'] as Array<any>).map(WidgetFieldMappingToJSON)),
        'tabs': value['tabs'] == null ? undefined : ((value['tabs'] as Array<any>).map(WidgetTabToJSON)),
    };
}

