/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanLimitKind } from './PlanLimitKind';
import {
    PlanLimitKindFromJSON,
    PlanLimitKindFromJSONTyped,
    PlanLimitKindToJSON,
    PlanLimitKindToJSONTyped,
} from './PlanLimitKind';
import type { PlanLimitKey } from './PlanLimitKey';
import {
    PlanLimitKeyFromJSON,
    PlanLimitKeyFromJSONTyped,
    PlanLimitKeyToJSON,
    PlanLimitKeyToJSONTyped,
} from './PlanLimitKey';

/**
 * One limit the workspace's plan sets, with what the workspace has used of it.
 * @export
 * @interface WorkspaceAllowance
 */
export interface WorkspaceAllowance {
    /**
     * When the allowance refills. Absent for totals that never refill and when nothing has been counted yet.
     * @type {Date}
     * @memberof WorkspaceAllowance
     */
    cycleEndAt?: Date;
    /**
     * Start of the current cycle. Absent when nothing has been counted yet.
     * @type {Date}
     * @memberof WorkspaceAllowance
     */
    cycleStartAt?: Date;
    /**
     * 
     * @type {PlanLimitKey}
     * @memberof WorkspaceAllowance
     */
    key?: PlanLimitKey;
    /**
     * 
     * @type {PlanLimitKind}
     * @memberof WorkspaceAllowance
     */
    kind?: PlanLimitKind;
    /**
     * The ceiling. Absent when kind is PLAN_LIMIT_KIND_UNLIMITED or PLAN_LIMIT_KIND_METERED.
     * @type {number}
     * @memberof WorkspaceAllowance
     */
    limit?: number;
    /**
     * 
     * @type {boolean}
     * @memberof WorkspaceAllowance
     */
    noticeDismissed?: boolean;
    /**
     * Whether the limit is used up for the current cycle. Platform credits count as reached only once purchased top-up credits are used up too.
     * @type {boolean}
     * @memberof WorkspaceAllowance
     */
    reached?: boolean;
    /**
     * Units used in the current cycle. For a total such as custom domains, what the workspace holds.
     * @type {number}
     * @memberof WorkspaceAllowance
     */
    used?: number;
}



/**
 * Check if a given object implements the WorkspaceAllowance interface.
 */
export function instanceOfWorkspaceAllowance(value: object): value is WorkspaceAllowance {
    return true;
}

export function WorkspaceAllowanceFromJSON(json: any): WorkspaceAllowance {
    return WorkspaceAllowanceFromJSONTyped(json, false);
}

export function WorkspaceAllowanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceAllowance {
    if (json == null) {
        return json;
    }
    return {
        
        'cycleEndAt': json['cycleEndAt'] == null ? undefined : (new Date(json['cycleEndAt'])),
        'cycleStartAt': json['cycleStartAt'] == null ? undefined : (new Date(json['cycleStartAt'])),
        'key': json['key'] == null ? undefined : PlanLimitKeyFromJSON(json['key']),
        'kind': json['kind'] == null ? undefined : PlanLimitKindFromJSON(json['kind']),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'noticeDismissed': json['noticeDismissed'] == null ? undefined : json['noticeDismissed'],
        'reached': json['reached'] == null ? undefined : json['reached'],
        'used': json['used'] == null ? undefined : json['used'],
    };
}

export function WorkspaceAllowanceToJSON(json: any): WorkspaceAllowance {
    return WorkspaceAllowanceToJSONTyped(json, false);
}

export function WorkspaceAllowanceToJSONTyped(value?: WorkspaceAllowance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cycleEndAt': value['cycleEndAt'] == null ? value['cycleEndAt'] : value['cycleEndAt'].toISOString(),
        'cycleStartAt': value['cycleStartAt'] == null ? value['cycleStartAt'] : value['cycleStartAt'].toISOString(),
        'key': PlanLimitKeyToJSON(value['key']),
        'kind': PlanLimitKindToJSON(value['kind']),
        'limit': value['limit'],
        'noticeDismissed': value['noticeDismissed'],
        'reached': value['reached'],
        'used': value['used'],
    };
}

