/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers  ## Entry points  `GET https://api.linkbreakers.com/` and `GET https://api.linkbreakers.com/v1` answer without credentials with the API\'s name, version and links. This document is served at `https://api.linkbreakers.com/openapi.json`.  ## Rate limits  Every response describes where the caller stands in the IETF `RateLimit-Policy` and `RateLimit` header fields (draft-ietf-httpapi-ratelimit-headers), and in `RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset` and `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` (a Unix timestamp) for clients that read those. A request past the limit gets `429 Too Many Requests` with `Retry-After` in seconds.  - Workspace API token: 600 requests per 60 seconds, per token. - Dashboard session or OAuth token: 500 requests per 60 seconds, per token. - No credentials: 300 requests per 60 seconds, per client IP.  Each plan also includes a number of API calls per billing cycle. Past it, calls answer `429` with the code `MAX_PUBLIC_API_QUERIED_REACHED` until the cycle renews or the plan changes.
 *
 * The version of the OpenAPI document: 1.150.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The node type says how many exits a step has. Whatever the answer, you
 * connect every one of them the same way, with workflow_steps_connect: name
 * the branch, name the step it leads to. Read a step's branches field for its
 * branch ids.
 * 
 * Example: a multi-link with 3 buttons has 3 branches, with the buttons' ids.
 * A redirect has one branch, "next". A country condition has one branch per
 * country plus "else".
 * 
 *  - NODE_TYPE_UNSPECIFIED: Workflow step node type not specified
 *  - NODE_TYPE_COMPOSITE: Composite steps have one exit per button, option or range, plus "else"
 * for a condition's fallback.
 * Examples: MULTI_LINK, VISIT_TYPE_CONDITION, COUNTRY_CONDITION,
 * DAY_OF_WEEK_CONDITION, TIME_OF_DAY_CONDITION, DAY_OF_MONTH_CONDITION,
 * SPECIFIC_DATE_CONDITION, DEVICE_*_CONDITION, VISITOR_DATA_CONDITION
 *  - NODE_TYPE_ATOMIC: Atomic steps have exactly one exit, branch id "next". Exit steps
 * (THANK_YOU_PAGE, CONTACT_CARD, SOCIAL_LINKS_PAGE, CLIENT_REDIRECT) are
 * atomic but end the journey, so they have no branches at all.
 * Examples: LINK_VISIT, PASSWORD_VERIFY, FORM_SUBMIT, MESSAGE_PAGE
 * @export
 */
export const WorkflowStepNodeType = {
    NodeTypeUnspecified: 'NODE_TYPE_UNSPECIFIED',
    NodeTypeComposite: 'NODE_TYPE_COMPOSITE',
    NodeTypeAtomic: 'NODE_TYPE_ATOMIC'
} as const;
export type WorkflowStepNodeType = typeof WorkflowStepNodeType[keyof typeof WorkflowStepNodeType];


export function instanceOfWorkflowStepNodeType(value: any): boolean {
    for (const key in WorkflowStepNodeType) {
        if (Object.prototype.hasOwnProperty.call(WorkflowStepNodeType, key)) {
            if (WorkflowStepNodeType[key as keyof typeof WorkflowStepNodeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkflowStepNodeTypeFromJSON(json: any): WorkflowStepNodeType {
    return WorkflowStepNodeTypeFromJSONTyped(json, false);
}

export function WorkflowStepNodeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowStepNodeType {
    return json as WorkflowStepNodeType;
}

export function WorkflowStepNodeTypeToJSON(value?: WorkflowStepNodeType | null): any {
    return value as any;
}

export function WorkflowStepNodeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkflowStepNodeType {
    return value as WorkflowStepNodeType;
}

