/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.123.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowStepPayload } from './WorkflowStepPayload';
import {
    WorkflowStepPayloadFromJSON,
    WorkflowStepPayloadFromJSONTyped,
    WorkflowStepPayloadToJSON,
    WorkflowStepPayloadToJSONTyped,
} from './WorkflowStepPayload';
import type { WorkflowStepBranch } from './WorkflowStepBranch';
import {
    WorkflowStepBranchFromJSON,
    WorkflowStepBranchFromJSONTyped,
    WorkflowStepBranchToJSON,
    WorkflowStepBranchToJSONTyped,
} from './WorkflowStepBranch';
import type { CanvasPosition } from './CanvasPosition';
import {
    CanvasPositionFromJSON,
    CanvasPositionFromJSONTyped,
    CanvasPositionToJSON,
    CanvasPositionToJSONTyped,
} from './CanvasPosition';

/**
 * Models a node in the Linkbreakers workflow canvas, defining what should occur after a scan (redirects, gates,
 * forms) and how it connects to other steps in the visitor journey.
 * @export
 * @interface WorkflowStep
 */
export interface WorkflowStep {
    /**
     * Every exit of this step, with its current destination.
     * 
     * This is the vocabulary for connecting the step: pass one of these
     * branch_ids to workflow_steps_connect. An atomic step has exactly one
     * branch, "next". A composite step has one per button, option or range,
     * plus "else" for a condition's fallback. An exit step has none.
     * @type {Array<WorkflowStepBranch>}
     * @memberof WorkflowStep
     */
    branches?: Array<WorkflowStepBranch>;
    /**
     * 
     * @type {CanvasPosition}
     * @memberof WorkflowStep
     */
    canvasPosition?: CanvasPosition;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkflowStep
     */
    childStepIds?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowStep
     */
    readonly createdAt?: Date;
    /**
     * - EVENT_ACTION_UNSPECIFIED: Event action not specified
     *  - EVENT_ACTION_CLIENT_REDIRECT: Redirect visitors to a destination URL
     *  - EVENT_ACTION_LINK_VISIT: Entry step triggered when the link is visited.
     *  - EVENT_ACTION_PASSWORD_VERIFY: Require visitors to enter a password before proceeding
     *  - EVENT_ACTION_FORM_SUBMIT: Present a data collection form to visitors
     *  - EVENT_ACTION_CONTACT_CARD: Generate a vCard (VCF) response with contact information
     *  - EVENT_ACTION_MULTI_LINK: A page of buttons where each one continues into more workflow: the button
     * leads to a next step, not straight out. Records which button the visitor
     * pressed, so use it over SOCIAL_LINKS_PAGE when that choice is worth
     * measuring or when a branch needs to do more than redirect.
     *  - EVENT_ACTION_VISIT_TYPE_CONDITION: Route visitors based on whether it's a first or returning visit
     *  - EVENT_ACTION_COUNTRY_CONDITION: Route visitors based on their country location
     *  - EVENT_ACTION_DAY_OF_WEEK_CONDITION: Route visitors based on day of week
     *  - EVENT_ACTION_TIME_OF_DAY_CONDITION: Route visitors based on time of day
     *  - EVENT_ACTION_DAY_OF_MONTH_CONDITION: Route visitors based on day of month
     *  - EVENT_ACTION_SPECIFIC_DATE_CONDITION: Route visitors based on specific calendar dates
     *  - EVENT_ACTION_SOCIAL_LINKS_PAGE: A page of buttons that each leave for an external URL. Social profiles are
     * the common case, not the only one: app stores, docs, booking pages and
     * storefronts all work, and the name is the only thing about it that is
     * social. It is an exit step, so the visitor leaves from here.
     *  - EVENT_ACTION_DEVICE_TYPE_CONDITION: Route visitors based on device type (e.g. MOBILE, DESKTOP, TABLET)
     *  - EVENT_ACTION_DEVICE_PLATFORM_CONDITION: Route visitors based on device platform / operating system (e.g. iOS, Android, macOS)
     *  - EVENT_ACTION_DEVICE_BROWSER_CONDITION: Route visitors based on browser family (e.g. Chrome, Safari, Firefox)
     *  - EVENT_ACTION_DEVICE_BRAND_CONDITION: Route visitors based on hardware brand (e.g. Apple, Samsung, Google)
     *  - EVENT_ACTION_DEVICE_ACTOR_CONDITION: Route visitors based on actor classification (e.g. HUMAN, BOT, AGENT)
     *  - EVENT_ACTION_VISITOR_DATA_CONDITION: Route visitors based on their profile data or custom attributes
     *  - EVENT_ACTION_THANK_YOU_PAGE: Display a final thank you / completion message (exit step)
     *  - EVENT_ACTION_MESSAGE_PAGE: Text with ONE way onward: a single button, or a timer that moves the
     * visitor automatically. It carries no list of destinations, so a page that
     * should offer a choice between two or more places is not this step. Use
     * SOCIAL_LINKS_PAGE when the choices leave for external URLs, or MULTI_LINK
     * when each choice continues into more workflow.
     * @type {WorkflowStepEventActionEnum}
     * @memberof WorkflowStep
     */
    eventAction?: WorkflowStepEventActionEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    id?: string;
    /**
     * - KIND_UNSPECIFIED: Workflow step kind not specified
     *  - KIND_ENTRY: Entry steps are automatically triggered when a visitor reaches the workflow
     *  - KIND_EXIT: Exit steps finalize the workflow (commonly a redirect)
     *  - KIND_INTERACTION: Interaction steps require visitor input (forms, passwords, etc.)
     *  - KIND_CONDITION: Condition steps evaluate logic and route to different next steps
     * @type {WorkflowStepKindEnum}
     * @memberof WorkflowStep
     */
    readonly kind?: WorkflowStepKindEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    linkId?: string;
    /**
     * The node type says how many exits a step has. Whatever the answer, you
     * connect every one of them the same way, with workflow_steps_connect: name
     * the branch, name the step it leads to. Read a step's branches field for its
     * branch ids.
     * 
     * Example: a multi-link with 3 buttons has 3 branches, with the buttons' ids.
     * A redirect has one branch, "next". A country condition has one branch per
     * country plus "else".
     * 
     *  - NODE_TYPE_UNSPECIFIED: Workflow step node type not specified
     *  - NODE_TYPE_COMPOSITE: Composite steps have one exit per button, option or range, plus "else"
     * for a condition's fallback.
     * Examples: MULTI_LINK, VISIT_TYPE_CONDITION, COUNTRY_CONDITION,
     * DAY_OF_WEEK_CONDITION, TIME_OF_DAY_CONDITION, DAY_OF_MONTH_CONDITION,
     * SPECIFIC_DATE_CONDITION, DEVICE_*_CONDITION, VISITOR_DATA_CONDITION
     *  - NODE_TYPE_ATOMIC: Atomic steps have exactly one exit, branch id "next". Exit steps
     * (THANK_YOU_PAGE, CONTACT_CARD, SOCIAL_LINKS_PAGE, CLIENT_REDIRECT) are
     * atomic but end the journey, so they have no branches at all.
     * Examples: LINK_VISIT, PASSWORD_VERIFY, FORM_SUBMIT, MESSAGE_PAGE
     * @type {WorkflowStepNodeTypeEnum}
     * @memberof WorkflowStep
     */
    readonly nodeType?: WorkflowStepNodeTypeEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkflowStep
     */
    parentStepIds?: Array<string>;
    /**
     * 
     * @type {WorkflowStepPayload}
     * @memberof WorkflowStep
     */
    payload?: WorkflowStepPayload;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowStep
     */
    readonly updatedAt?: Date;
}


/**
 * @export
 */
export const WorkflowStepEventActionEnum = {
    EventActionUnspecified: 'EVENT_ACTION_UNSPECIFIED',
    EventActionClientRedirect: 'EVENT_ACTION_CLIENT_REDIRECT',
    EventActionLinkVisit: 'EVENT_ACTION_LINK_VISIT',
    EventActionPasswordVerify: 'EVENT_ACTION_PASSWORD_VERIFY',
    EventActionFormSubmit: 'EVENT_ACTION_FORM_SUBMIT',
    EventActionContactCard: 'EVENT_ACTION_CONTACT_CARD',
    EventActionMultiLink: 'EVENT_ACTION_MULTI_LINK',
    EventActionVisitTypeCondition: 'EVENT_ACTION_VISIT_TYPE_CONDITION',
    EventActionCountryCondition: 'EVENT_ACTION_COUNTRY_CONDITION',
    EventActionDayOfWeekCondition: 'EVENT_ACTION_DAY_OF_WEEK_CONDITION',
    EventActionTimeOfDayCondition: 'EVENT_ACTION_TIME_OF_DAY_CONDITION',
    EventActionDayOfMonthCondition: 'EVENT_ACTION_DAY_OF_MONTH_CONDITION',
    EventActionSpecificDateCondition: 'EVENT_ACTION_SPECIFIC_DATE_CONDITION',
    EventActionSocialLinksPage: 'EVENT_ACTION_SOCIAL_LINKS_PAGE',
    EventActionDeviceTypeCondition: 'EVENT_ACTION_DEVICE_TYPE_CONDITION',
    EventActionDevicePlatformCondition: 'EVENT_ACTION_DEVICE_PLATFORM_CONDITION',
    EventActionDeviceBrowserCondition: 'EVENT_ACTION_DEVICE_BROWSER_CONDITION',
    EventActionDeviceBrandCondition: 'EVENT_ACTION_DEVICE_BRAND_CONDITION',
    EventActionDeviceActorCondition: 'EVENT_ACTION_DEVICE_ACTOR_CONDITION',
    EventActionVisitorDataCondition: 'EVENT_ACTION_VISITOR_DATA_CONDITION',
    EventActionThankYouPage: 'EVENT_ACTION_THANK_YOU_PAGE',
    EventActionMessagePage: 'EVENT_ACTION_MESSAGE_PAGE'
} as const;
export type WorkflowStepEventActionEnum = typeof WorkflowStepEventActionEnum[keyof typeof WorkflowStepEventActionEnum];

/**
 * @export
 */
export const WorkflowStepKindEnum = {
    KindUnspecified: 'KIND_UNSPECIFIED',
    KindEntry: 'KIND_ENTRY',
    KindExit: 'KIND_EXIT',
    KindInteraction: 'KIND_INTERACTION',
    KindCondition: 'KIND_CONDITION'
} as const;
export type WorkflowStepKindEnum = typeof WorkflowStepKindEnum[keyof typeof WorkflowStepKindEnum];

/**
 * @export
 */
export const WorkflowStepNodeTypeEnum = {
    NodeTypeUnspecified: 'NODE_TYPE_UNSPECIFIED',
    NodeTypeComposite: 'NODE_TYPE_COMPOSITE',
    NodeTypeAtomic: 'NODE_TYPE_ATOMIC'
} as const;
export type WorkflowStepNodeTypeEnum = typeof WorkflowStepNodeTypeEnum[keyof typeof WorkflowStepNodeTypeEnum];


/**
 * Check if a given object implements the WorkflowStep interface.
 */
export function instanceOfWorkflowStep(value: object): value is WorkflowStep {
    return true;
}

export function WorkflowStepFromJSON(json: any): WorkflowStep {
    return WorkflowStepFromJSONTyped(json, false);
}

export function WorkflowStepFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowStep {
    if (json == null) {
        return json;
    }
    return {
        
        'branches': json['branches'] == null ? undefined : ((json['branches'] as Array<any>).map(WorkflowStepBranchFromJSON)),
        'canvasPosition': json['canvasPosition'] == null ? undefined : CanvasPositionFromJSON(json['canvasPosition']),
        'childStepIds': json['childStepIds'] == null ? undefined : json['childStepIds'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'eventAction': json['eventAction'] == null ? undefined : json['eventAction'],
        'id': json['id'] == null ? undefined : json['id'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'linkId': json['linkId'] == null ? undefined : json['linkId'],
        'nodeType': json['nodeType'] == null ? undefined : json['nodeType'],
        'parentStepIds': json['parentStepIds'] == null ? undefined : json['parentStepIds'],
        'payload': json['payload'] == null ? undefined : WorkflowStepPayloadFromJSON(json['payload']),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function WorkflowStepToJSON(json: any): WorkflowStep {
    return WorkflowStepToJSONTyped(json, false);
}

export function WorkflowStepToJSONTyped(value?: Omit<WorkflowStep, 'createdAt'|'kind'|'nodeType'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branches': value['branches'] == null ? undefined : ((value['branches'] as Array<any>).map(WorkflowStepBranchToJSON)),
        'canvasPosition': CanvasPositionToJSON(value['canvasPosition']),
        'childStepIds': value['childStepIds'],
        'eventAction': value['eventAction'],
        'id': value['id'],
        'linkId': value['linkId'],
        'parentStepIds': value['parentStepIds'],
        'payload': WorkflowStepPayloadToJSON(value['payload']),
    };
}

