/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.43.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serves as the tenant boundary in Linkbreakers, grouping links, members, settings, billing state,
 * and analytics under a single organization's environment.
 * @export
 * @interface Workspace
 */
export interface Workspace {
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    country?: string;
    /**
     * 
     * @type {Date}
     * @memberof Workspace
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Workspace
     */
    enforceMfa?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Workspace
     */
    enrollRequestedAt?: Date;
    /**
     * Frequently Asked Questions about this workspace stored as JSON
     * @type {string}
     * @memberof Workspace
     */
    faq?: string;
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Workspace
     */
    inactiveSince?: Date;
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    linkSettingId?: string;
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof Workspace
     */
    publishedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    shortDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    slug?: string;
    /**
     * - SUBSCRIPTION_TYPE_UNSPECIFIED: Subscription plan not yet assigned
     *  - SUBSCRIPTION_TYPE_FREE_TRIAL: Workspace is currently in the free trial period
     *  - SUBSCRIPTION_TYPE_SPONSORED_PRO: Workspace is on the sponsored pro plan with full pro features
     *  - SUBSCRIPTION_TYPE_PRO_PLAN: Workspace has an active Pro plan subscription
     *  - SUBSCRIPTION_TYPE_ENTERPRISE_PLAN: Workspace is managed under an Enterprise contract
     *  - SUBSCRIPTION_TYPE_LIGHT_PLAN: Workspace has an active Light plan subscription
     * @type {WorkspaceSubscriptionTypeEnum}
     * @memberof Workspace
     */
    subscriptionType?: WorkspaceSubscriptionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    tags?: string;
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    timezone?: string;
    /**
     * 
     * @type {Date}
     * @memberof Workspace
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Workspace
     */
    verifiedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Workspace
     */
    website?: string;
}


/**
 * @export
 */
export const WorkspaceSubscriptionTypeEnum = {
    SubscriptionTypeUnspecified: 'SUBSCRIPTION_TYPE_UNSPECIFIED',
    SubscriptionTypeFreeTrial: 'SUBSCRIPTION_TYPE_FREE_TRIAL',
    SubscriptionTypeSponsoredPro: 'SUBSCRIPTION_TYPE_SPONSORED_PRO',
    SubscriptionTypeProPlan: 'SUBSCRIPTION_TYPE_PRO_PLAN',
    SubscriptionTypeEnterprisePlan: 'SUBSCRIPTION_TYPE_ENTERPRISE_PLAN',
    SubscriptionTypeLightPlan: 'SUBSCRIPTION_TYPE_LIGHT_PLAN'
} as const;
export type WorkspaceSubscriptionTypeEnum = typeof WorkspaceSubscriptionTypeEnum[keyof typeof WorkspaceSubscriptionTypeEnum];


/**
 * Check if a given object implements the Workspace interface.
 */
export function instanceOfWorkspace(value: object): value is Workspace {
    return true;
}

export function WorkspaceFromJSON(json: any): Workspace {
    return WorkspaceFromJSONTyped(json, false);
}

export function WorkspaceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Workspace {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'] == null ? undefined : json['country'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'description': json['description'] == null ? undefined : json['description'],
        'enforceMfa': json['enforceMfa'] == null ? undefined : json['enforceMfa'],
        'enrollRequestedAt': json['enrollRequestedAt'] == null ? undefined : (new Date(json['enrollRequestedAt'])),
        'faq': json['faq'] == null ? undefined : json['faq'],
        'id': json['id'] == null ? undefined : json['id'],
        'inactiveSince': json['inactiveSince'] == null ? undefined : (new Date(json['inactiveSince'])),
        'linkSettingId': json['linkSettingId'] == null ? undefined : json['linkSettingId'],
        'name': json['name'] == null ? undefined : json['name'],
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'shortDescription': json['shortDescription'] == null ? undefined : json['shortDescription'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'subscriptionType': json['subscriptionType'] == null ? undefined : json['subscriptionType'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'verifiedAt': json['verifiedAt'] == null ? undefined : (new Date(json['verifiedAt'])),
        'website': json['website'] == null ? undefined : json['website'],
    };
}

export function WorkspaceToJSON(json: any): Workspace {
    return WorkspaceToJSONTyped(json, false);
}

export function WorkspaceToJSONTyped(value?: Workspace | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'description': value['description'],
        'enforceMfa': value['enforceMfa'],
        'enrollRequestedAt': value['enrollRequestedAt'] == null ? value['enrollRequestedAt'] : value['enrollRequestedAt'].toISOString(),
        'faq': value['faq'],
        'id': value['id'],
        'inactiveSince': value['inactiveSince'] == null ? value['inactiveSince'] : value['inactiveSince'].toISOString(),
        'linkSettingId': value['linkSettingId'],
        'name': value['name'],
        'publishedAt': value['publishedAt'] == null ? value['publishedAt'] : value['publishedAt'].toISOString(),
        'shortDescription': value['shortDescription'],
        'slug': value['slug'],
        'subscriptionType': value['subscriptionType'],
        'tags': value['tags'],
        'timezone': value['timezone'],
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
        'verifiedAt': value['verifiedAt'] == null ? value['verifiedAt'] : value['verifiedAt'].toISOString(),
        'website': value['website'],
    };
}

