/* tslint:disable */
/* eslint-disable */
/**
 * Linkbreakers API
 * This is a documentation of all the APIs of Linkbreakers
 *
 * The version of the OpenAPI document: 1.39.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowStepPayload } from './WorkflowStepPayload';
import {
    WorkflowStepPayloadFromJSON,
    WorkflowStepPayloadFromJSONTyped,
    WorkflowStepPayloadToJSON,
    WorkflowStepPayloadToJSONTyped,
} from './WorkflowStepPayload';
import type { CanvasPosition } from './CanvasPosition';
import {
    CanvasPositionFromJSON,
    CanvasPositionFromJSONTyped,
    CanvasPositionToJSON,
    CanvasPositionToJSONTyped,
} from './CanvasPosition';

/**
 * 
 * @export
 * @interface WorkflowStepsServiceCreateBody
 */
export interface WorkflowStepsServiceCreateBody {
    /**
     * 
     * @type {CanvasPosition}
     * @memberof WorkflowStepsServiceCreateBody
     */
    canvasPosition?: CanvasPosition;
    /**
     * - EVENT_ACTION_UNSPECIFIED: Event action not specified
     *  - EVENT_ACTION_CLIENT_REDIRECT: Redirect visitors to a destination URL
     *  - EVENT_ACTION_LINK_VISIT: Entry step triggered when the link is visited.
     *  - EVENT_ACTION_PASSWORD_VERIFY: Require visitors to enter a password before proceeding
     *  - EVENT_ACTION_FORM_SUBMIT: Present a data collection form to visitors
     *  - EVENT_ACTION_CONTACT_CARD: Generate a vCard (VCF) response with contact information
     *  - EVENT_ACTION_MULTI_LINK: Present a multi-link page with multiple buttons for different destinations
     *  - EVENT_ACTION_VISIT_TYPE_CONDITION: Route visitors based on whether it's a first or returning visit
     *  - EVENT_ACTION_COUNTRY_CONDITION: Route visitors based on their country location
     *  - EVENT_ACTION_DAY_OF_WEEK_CONDITION: Route visitors based on day of week
     *  - EVENT_ACTION_TIME_OF_DAY_CONDITION: Route visitors based on time of day
     *  - EVENT_ACTION_DAY_OF_MONTH_CONDITION: Route visitors based on day of month
     *  - EVENT_ACTION_SPECIFIC_DATE_CONDITION: Route visitors based on specific calendar dates
     *  - EVENT_ACTION_SOCIAL_LINKS_PAGE: Display a social links page (like Linktree)
     * @type {WorkflowStepsServiceCreateBodyEventActionEnum}
     * @memberof WorkflowStepsServiceCreateBody
     */
    eventAction?: WorkflowStepsServiceCreateBodyEventActionEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStepsServiceCreateBody
     */
    id?: string;
    /**
     * 
     * @type {WorkflowStepPayload}
     * @memberof WorkflowStepsServiceCreateBody
     */
    payload?: WorkflowStepPayload;
}


/**
 * @export
 */
export const WorkflowStepsServiceCreateBodyEventActionEnum = {
    EventActionUnspecified: 'EVENT_ACTION_UNSPECIFIED',
    EventActionClientRedirect: 'EVENT_ACTION_CLIENT_REDIRECT',
    EventActionLinkVisit: 'EVENT_ACTION_LINK_VISIT',
    EventActionPasswordVerify: 'EVENT_ACTION_PASSWORD_VERIFY',
    EventActionFormSubmit: 'EVENT_ACTION_FORM_SUBMIT',
    EventActionContactCard: 'EVENT_ACTION_CONTACT_CARD',
    EventActionMultiLink: 'EVENT_ACTION_MULTI_LINK',
    EventActionVisitTypeCondition: 'EVENT_ACTION_VISIT_TYPE_CONDITION',
    EventActionCountryCondition: 'EVENT_ACTION_COUNTRY_CONDITION',
    EventActionDayOfWeekCondition: 'EVENT_ACTION_DAY_OF_WEEK_CONDITION',
    EventActionTimeOfDayCondition: 'EVENT_ACTION_TIME_OF_DAY_CONDITION',
    EventActionDayOfMonthCondition: 'EVENT_ACTION_DAY_OF_MONTH_CONDITION',
    EventActionSpecificDateCondition: 'EVENT_ACTION_SPECIFIC_DATE_CONDITION',
    EventActionSocialLinksPage: 'EVENT_ACTION_SOCIAL_LINKS_PAGE'
} as const;
export type WorkflowStepsServiceCreateBodyEventActionEnum = typeof WorkflowStepsServiceCreateBodyEventActionEnum[keyof typeof WorkflowStepsServiceCreateBodyEventActionEnum];


/**
 * Check if a given object implements the WorkflowStepsServiceCreateBody interface.
 */
export function instanceOfWorkflowStepsServiceCreateBody(value: object): value is WorkflowStepsServiceCreateBody {
    return true;
}

export function WorkflowStepsServiceCreateBodyFromJSON(json: any): WorkflowStepsServiceCreateBody {
    return WorkflowStepsServiceCreateBodyFromJSONTyped(json, false);
}

export function WorkflowStepsServiceCreateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowStepsServiceCreateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'canvasPosition': json['canvasPosition'] == null ? undefined : CanvasPositionFromJSON(json['canvasPosition']),
        'eventAction': json['eventAction'] == null ? undefined : json['eventAction'],
        'id': json['id'] == null ? undefined : json['id'],
        'payload': json['payload'] == null ? undefined : WorkflowStepPayloadFromJSON(json['payload']),
    };
}

export function WorkflowStepsServiceCreateBodyToJSON(json: any): WorkflowStepsServiceCreateBody {
    return WorkflowStepsServiceCreateBodyToJSONTyped(json, false);
}

export function WorkflowStepsServiceCreateBodyToJSONTyped(value?: WorkflowStepsServiceCreateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'canvasPosition': CanvasPositionToJSON(value['canvasPosition']),
        'eventAction': value['eventAction'],
        'id': value['id'],
        'payload': WorkflowStepPayloadToJSON(value['payload']),
    };
}

